// AUTO-GENERATED by bdc_inventory/scripts/accuracy_goldens.py — do not edit by hand.
// The hand-audited golden set (tests/fixtures/accuracy_goldens.json): 280 positions
// read cell by cell against their filings on the audit date, re-checked against the
// database on every rebuild. "before" is what the auditors found; "after" is the
// same filing values re-checked against the data now published.
/* eslint-disable */

export interface AccuracyField {
  field: string; label: string; short: string;
  before_correct: number | null; before_checked: number | null; before_pct: number | null;
  before_wrong: number; before_blank: number;
  after_correct: number; after_checked: number; after_pct: number | null;
  after_wrong: number; after_blank: number;
}
export interface AccuracyRemaining {
  id: string; ticker: string; period_end: string; company: string | null;
  field: string; label: string; short: string; result: string; reason: string;
}
export interface AccuracyAuditData {
  audited_on: string; checked_on: string; before_recheck_note: string;
  positions: number; bdcs: number; filings: number; design: string;
  sample_first_period: string; sample_last_period: string;
  values_checked: number; values_correct: number;
  before_values_checked: number; before_values_correct: number;
  fields: AccuracyField[]; remaining: AccuracyRemaining[]; regressions: number;
}

export const accuracyAudit: AccuracyAuditData = {
  "audited_on": "2026-10-01",
  "checked_on": "2026-10-02",
  "before_recheck_note": "As a cross-check of the method, the same check run on the database as it stood on the audit date, before the fixes, gives a picture close to the auditors': industry 93.9%, par 99.1%, non-accrual flag 98.6%, PIK 97.2%.",
  "positions": 280,
  "bdcs": 19,
  "filings": 216,
  "design": "stratified across the 19 parsed BDCs and every parser era (2014 to 2026-06)",
  "sample_first_period": "2013-12-31",
  "sample_last_period": "2026-06-30",
  "values_checked": 2970,
  "values_correct": 2969,
  "before_values_checked": 3621,
  "before_values_correct": 3347,
  "fields": [
    {
      "field": "company",
      "label": "Borrower name",
      "short": "borrower name",
      "before_correct": 273,
      "before_checked": 280,
      "before_pct": 97.5,
      "before_wrong": 7,
      "before_blank": 0,
      "after_correct": 280,
      "after_checked": 280,
      "after_pct": 100.0,
      "after_wrong": 0,
      "after_blank": 0
    },
    {
      "field": "investment_type",
      "label": "Instrument as printed",
      "short": "instrument as printed",
      "before_correct": 252,
      "before_checked": 252,
      "before_pct": 100.0,
      "before_wrong": 0,
      "before_blank": 0,
      "after_correct": 220,
      "after_checked": 220,
      "after_pct": 100.0,
      "after_wrong": 0,
      "after_blank": 0
    },
    {
      "field": "instrument",
      "label": "Asset class (first lien, second lien, equity…)",
      "short": "asset class",
      "before_correct": 165,
      "before_checked": 223,
      "before_pct": 74.0,
      "before_wrong": 10,
      "before_blank": 48,
      "after_correct": 279,
      "after_checked": 279,
      "after_pct": 100.0,
      "after_wrong": 0,
      "after_blank": 0
    },
    {
      "field": "industry",
      "label": "Industry",
      "short": "industry",
      "before_correct": 246,
      "before_checked": 264,
      "before_pct": 93.2,
      "before_wrong": 16,
      "before_blank": 2,
      "after_correct": 262,
      "after_checked": 262,
      "after_pct": 100.0,
      "after_wrong": 0,
      "after_blank": 0
    },
    {
      "field": "par",
      "label": "Par (principal)",
      "short": "par",
      "before_correct": 275,
      "before_checked": 277,
      "before_pct": 99.3,
      "before_wrong": 1,
      "before_blank": 1,
      "after_correct": 229,
      "after_checked": 229,
      "after_pct": 100.0,
      "after_wrong": 0,
      "after_blank": 0
    },
    {
      "field": "amortized_cost",
      "label": "Amortized cost",
      "short": "amortized cost",
      "before_correct": 280,
      "before_checked": 280,
      "before_pct": 100.0,
      "before_wrong": 0,
      "before_blank": 0,
      "after_correct": 279,
      "after_checked": 279,
      "after_pct": 100.0,
      "after_wrong": 0,
      "after_blank": 0
    },
    {
      "field": "fair_value",
      "label": "Fair value",
      "short": "fair value",
      "before_correct": 280,
      "before_checked": 280,
      "before_pct": 100.0,
      "before_wrong": 0,
      "before_blank": 0,
      "after_correct": 279,
      "after_checked": 279,
      "after_pct": 100.0,
      "after_wrong": 0,
      "after_blank": 0
    },
    {
      "field": "spread",
      "label": "Interest rate and spread",
      "short": "rate terms",
      "before_correct": 418,
      "before_checked": 439,
      "before_pct": 95.2,
      "before_wrong": 1,
      "before_blank": 20,
      "after_correct": 172,
      "after_checked": 172,
      "after_pct": 100.0,
      "after_wrong": 0,
      "after_blank": 0
    },
    {
      "field": "floor_pct",
      "label": "Interest-rate floor",
      "short": "floor",
      "before_correct": 19,
      "before_checked": 63,
      "before_pct": 30.2,
      "before_wrong": 0,
      "before_blank": 44,
      "after_correct": 60,
      "after_checked": 60,
      "after_pct": 100.0,
      "after_wrong": 0,
      "after_blank": 0
    },
    {
      "field": "maturity_date",
      "label": "Maturity date",
      "short": "maturity date",
      "before_correct": 266,
      "before_checked": 267,
      "before_pct": 99.6,
      "before_wrong": 1,
      "before_blank": 0,
      "after_correct": 230,
      "after_checked": 230,
      "after_pct": 100.0,
      "after_wrong": 0,
      "after_blank": 0
    },
    {
      "field": "acquisition_date",
      "label": "Acquisition date",
      "short": "acquisition date",
      "before_correct": 109,
      "before_checked": 111,
      "before_pct": 98.2,
      "before_wrong": 0,
      "before_blank": 2,
      "after_correct": 102,
      "after_checked": 102,
      "after_pct": 100.0,
      "after_wrong": 0,
      "after_blank": 0
    },
    {
      "field": "non_accrual",
      "label": "Non-accrual flag",
      "short": "non-accrual flag",
      "before_correct": 275,
      "before_checked": 280,
      "before_pct": 98.2,
      "before_wrong": 1,
      "before_blank": 4,
      "after_correct": 277,
      "after_checked": 278,
      "after_pct": 99.6,
      "after_wrong": 0,
      "after_blank": 1
    },
    {
      "field": "pik",
      "label": "PIK (interest paid in kind)",
      "short": "PIK",
      "before_correct": 378,
      "before_checked": 396,
      "before_pct": 95.5,
      "before_wrong": 9,
      "before_blank": 9,
      "after_correct": 214,
      "after_checked": 214,
      "after_pct": 100.0,
      "after_wrong": 0,
      "after_blank": 0
    },
    {
      "field": "unfunded_commitment",
      "label": "Undrawn-commitment flag",
      "short": "undrawn-commitment flag",
      "before_correct": 111,
      "before_checked": 209,
      "before_pct": 53.1,
      "before_wrong": 0,
      "before_blank": 98,
      "after_correct": 86,
      "after_checked": 86,
      "after_pct": 100.0,
      "after_wrong": 0,
      "after_blank": 0
    }
  ],
  "remaining": [
    {
      "id": "S235",
      "ticker": "OCSL",
      "period_end": "2015-09-30",
      "company": "First Star Aviation, LLC",
      "field": "non_accrual",
      "label": "Non-accrual flag",
      "short": "non-accrual flag",
      "result": "left blank",
      "reason": "OCSL's fiscal-year-end 10-K for 2015-09-30 lists its non-accrual loans in a form the pipeline does not yet read, so that quarter shows OCSL's own total (4.92% of its debt at cost) and each loan's status is unknown rather than zero."
    }
  ],
  "regressions": 0
};
