// AUTO-GENERATED by bdc_inventory/scripts/accuracy_goldens.py — do not edit by hand.
// The hand-audited golden set (tests/fixtures/accuracy_goldens.json): 280 positions
// read cell by cell against their filings on the audit date, re-checked against the
// database on every rebuild. "before" is what the auditors found; "after" is the
// same filing values re-checked against the data now published.
/* eslint-disable */

export interface AccuracyField {
  field: string; label: string; short: string;
  before_correct: number | null; before_checked: number | null; before_pct: number | null;
  before_wrong: number; before_blank: number;
  after_correct: number; after_checked: number; after_pct: number | null;
  after_wrong: number; after_blank: number;
}
export interface AccuracyRemaining {
  id: string; ticker: string; period_end: string; company: string | null;
  field: string; label: string; short: string; result: string; reason: string;
}
export interface AccuracyRecheck {
  field: string; short: string; auditors_pct: number; recheck_pct: number; agrees: boolean; reason: string;
}
export interface AccuracyCountNote {
  field: string; short: string; before_checked: number; after_checked: number; reason: string;
}
export interface AccuracyAuditData {
  audited_on: string; checked_on: string; before_recheck_note: string;
  before_recheck: AccuracyRecheck[]; count_notes: AccuracyCountNote[];
  positions: number; bdcs: number; filings: number; design: string;
  sample_first_period: string; sample_last_period: string;
  values_checked: number; values_correct: number;
  before_values_checked: number; before_values_correct: number;
  fields: AccuracyField[]; remaining: AccuracyRemaining[]; regressions: number;
  not_published: { id: string; ticker: string; period_end: string }[];
}

export const accuracyAudit: AccuracyAuditData = {
  "audited_on": "2026-10-01",
  "checked_on": "2026-10-02",
  "before_recheck_note": "As a cross-check of the method, the same check was run on the database as it stood on the audit date, before the fixes. For 10 of 14 fields it lands within 3 points of the auditors' own count (borrower name 99.6% against 97.5%, instrument as printed 100% against 100%, industry 93.9% against 93.2%, par 99.1% against 99.3%, amortized cost 100% against 100%, fair value 100% against 100%, maturity date 100% against 99.6%, acquisition date 100% against 98.2%, non-accrual flag 98.6% against 98.2%, PIK 97.2% against 95.5%). It differs for asset class (97.5% against the auditors' 74%: the re-check reads the old labels with today's shared instrument rule, which credits them with the new classification; the auditors scored the old database's own asset-class labels, many of them blank); rate terms (98.8% against the auditors' 95.2%: the auditors' readings count the index and the coupon as well as the spread, the answer key the spread alone); floor (0% against the auditors' 30.2%: the old database stored a floor only where FSK's parser read one, so every floor in the answer key reads blank); undrawn-commitment flag (0% against the auditors' 53.1%: the old database set the undrawn-commitment flag for FSK only, so every other row reads blank).",
  "before_recheck": [
    {
      "field": "company",
      "short": "borrower name",
      "auditors_pct": 97.5,
      "recheck_pct": 99.6,
      "agrees": true,
      "reason": ""
    },
    {
      "field": "investment_type",
      "short": "instrument as printed",
      "auditors_pct": 100.0,
      "recheck_pct": 100.0,
      "agrees": true,
      "reason": ""
    },
    {
      "field": "instrument",
      "short": "asset class",
      "auditors_pct": 74.0,
      "recheck_pct": 97.5,
      "agrees": false,
      "reason": "the re-check reads the old labels with today's shared instrument rule, which credits them with the new classification; the auditors scored the old database's own asset-class labels, many of them blank"
    },
    {
      "field": "industry",
      "short": "industry",
      "auditors_pct": 93.2,
      "recheck_pct": 93.9,
      "agrees": true,
      "reason": ""
    },
    {
      "field": "par",
      "short": "par",
      "auditors_pct": 99.3,
      "recheck_pct": 99.1,
      "agrees": true,
      "reason": ""
    },
    {
      "field": "amortized_cost",
      "short": "amortized cost",
      "auditors_pct": 100.0,
      "recheck_pct": 100.0,
      "agrees": true,
      "reason": ""
    },
    {
      "field": "fair_value",
      "short": "fair value",
      "auditors_pct": 100.0,
      "recheck_pct": 100.0,
      "agrees": true,
      "reason": ""
    },
    {
      "field": "spread",
      "short": "rate terms",
      "auditors_pct": 95.2,
      "recheck_pct": 98.8,
      "agrees": false,
      "reason": "the auditors' readings count the index and the coupon as well as the spread, the answer key the spread alone"
    },
    {
      "field": "floor_pct",
      "short": "floor",
      "auditors_pct": 30.2,
      "recheck_pct": 0.0,
      "agrees": false,
      "reason": "the old database stored a floor only where FSK's parser read one, so every floor in the answer key reads blank"
    },
    {
      "field": "maturity_date",
      "short": "maturity date",
      "auditors_pct": 99.6,
      "recheck_pct": 100.0,
      "agrees": true,
      "reason": ""
    },
    {
      "field": "acquisition_date",
      "short": "acquisition date",
      "auditors_pct": 98.2,
      "recheck_pct": 100.0,
      "agrees": true,
      "reason": ""
    },
    {
      "field": "non_accrual",
      "short": "non-accrual flag",
      "auditors_pct": 98.2,
      "recheck_pct": 98.6,
      "agrees": true,
      "reason": ""
    },
    {
      "field": "pik",
      "short": "PIK",
      "auditors_pct": 95.5,
      "recheck_pct": 97.2,
      "agrees": true,
      "reason": ""
    },
    {
      "field": "unfunded_commitment",
      "short": "undrawn-commitment flag",
      "auditors_pct": 53.1,
      "recheck_pct": 0.0,
      "agrees": false,
      "reason": "the old database set the undrawn-commitment flag for FSK only, so every other row reads blank"
    }
  ],
  "count_notes": [
    {
      "field": "investment_type",
      "short": "instrument as printed",
      "before_checked": 252,
      "after_checked": 220,
      "reason": "BXSL, BCRED, CGBD and FSK print the instrument in the name or a class heading, not a type column, so the answer key has no type for those rows"
    },
    {
      "field": "instrument",
      "short": "asset class",
      "before_checked": 223,
      "after_checked": 279,
      "reason": "the auditors scored only rows whose filing prints an asset-class heading; the answer key reads the instrument from the type text for every holding"
    },
    {
      "field": "industry",
      "short": "industry",
      "before_checked": 264,
      "after_checked": 262,
      "reason": "a cash fund and a row that is not a holding have no industry"
    },
    {
      "field": "par",
      "short": "par",
      "before_checked": 277,
      "after_checked": 229,
      "reason": "an equity or fund row prints no par: the auditors counted its blank as a match, the answer key leaves it out"
    },
    {
      "field": "amortized_cost",
      "short": "amortized cost",
      "before_checked": 280,
      "after_checked": 279,
      "reason": "one sampled row is not a holding (a page title the old parser stored), so it has no cost to check"
    },
    {
      "field": "fair_value",
      "short": "fair value",
      "before_checked": 280,
      "after_checked": 279,
      "reason": "one sampled row is not a holding (a page title the old parser stored), so it has no fair value to check"
    },
    {
      "field": "spread",
      "short": "rate terms",
      "before_checked": 439,
      "after_checked": 172,
      "reason": "the auditors also read each row's index and coupon"
    },
    {
      "field": "floor_pct",
      "short": "floor",
      "before_checked": 63,
      "after_checked": 60,
      "reason": "the answer key keeps only values it could re-read from the raw row itself"
    },
    {
      "field": "maturity_date",
      "short": "maturity date",
      "before_checked": 267,
      "after_checked": 230,
      "reason": "an equity or fund row prints no maturity: the auditors counted its blank as a match, the answer key leaves it out"
    },
    {
      "field": "acquisition_date",
      "short": "acquisition date",
      "before_checked": 111,
      "after_checked": 102,
      "reason": "the answer key keeps only values it could re-read from the raw row itself"
    },
    {
      "field": "non_accrual",
      "short": "non-accrual flag",
      "before_checked": 280,
      "after_checked": 278,
      "reason": "a cash fund and a row that is not a holding have no non-accrual status"
    },
    {
      "field": "pik",
      "short": "PIK",
      "before_checked": 396,
      "after_checked": 214,
      "reason": "the auditors also read each PIK rate and severity, the answer key the PIK type alone"
    },
    {
      "field": "unfunded_commitment",
      "short": "undrawn-commitment flag",
      "before_checked": 209,
      "after_checked": 86,
      "reason": "the answer key covers the 86 positions the undrawn-commitment fix was accepted on, not every sampled row"
    }
  ],
  "positions": 280,
  "bdcs": 19,
  "filings": 216,
  "design": "stratified across the 19 parsed BDCs and every parser era (2014 to 2026-06)",
  "sample_first_period": "2013-12-31",
  "sample_last_period": "2026-06-30",
  "values_checked": 2970,
  "values_correct": 2969,
  "before_values_checked": 3621,
  "before_values_correct": 3347,
  "fields": [
    {
      "field": "company",
      "label": "Borrower name",
      "short": "borrower name",
      "before_correct": 273,
      "before_checked": 280,
      "before_pct": 97.5,
      "before_wrong": 7,
      "before_blank": 0,
      "after_correct": 280,
      "after_checked": 280,
      "after_pct": 100.0,
      "after_wrong": 0,
      "after_blank": 0
    },
    {
      "field": "investment_type",
      "label": "Instrument as printed",
      "short": "instrument as printed",
      "before_correct": 252,
      "before_checked": 252,
      "before_pct": 100.0,
      "before_wrong": 0,
      "before_blank": 0,
      "after_correct": 220,
      "after_checked": 220,
      "after_pct": 100.0,
      "after_wrong": 0,
      "after_blank": 0
    },
    {
      "field": "instrument",
      "label": "Asset class (first lien, second lien, equity…)",
      "short": "asset class",
      "before_correct": 165,
      "before_checked": 223,
      "before_pct": 74.0,
      "before_wrong": 10,
      "before_blank": 48,
      "after_correct": 279,
      "after_checked": 279,
      "after_pct": 100.0,
      "after_wrong": 0,
      "after_blank": 0
    },
    {
      "field": "industry",
      "label": "Industry",
      "short": "industry",
      "before_correct": 246,
      "before_checked": 264,
      "before_pct": 93.2,
      "before_wrong": 16,
      "before_blank": 2,
      "after_correct": 262,
      "after_checked": 262,
      "after_pct": 100.0,
      "after_wrong": 0,
      "after_blank": 0
    },
    {
      "field": "par",
      "label": "Par (principal)",
      "short": "par",
      "before_correct": 275,
      "before_checked": 277,
      "before_pct": 99.3,
      "before_wrong": 1,
      "before_blank": 1,
      "after_correct": 229,
      "after_checked": 229,
      "after_pct": 100.0,
      "after_wrong": 0,
      "after_blank": 0
    },
    {
      "field": "amortized_cost",
      "label": "Amortized cost",
      "short": "amortized cost",
      "before_correct": 280,
      "before_checked": 280,
      "before_pct": 100.0,
      "before_wrong": 0,
      "before_blank": 0,
      "after_correct": 279,
      "after_checked": 279,
      "after_pct": 100.0,
      "after_wrong": 0,
      "after_blank": 0
    },
    {
      "field": "fair_value",
      "label": "Fair value",
      "short": "fair value",
      "before_correct": 280,
      "before_checked": 280,
      "before_pct": 100.0,
      "before_wrong": 0,
      "before_blank": 0,
      "after_correct": 279,
      "after_checked": 279,
      "after_pct": 100.0,
      "after_wrong": 0,
      "after_blank": 0
    },
    {
      "field": "spread",
      "label": "Interest rate and spread",
      "short": "rate terms",
      "before_correct": 418,
      "before_checked": 439,
      "before_pct": 95.2,
      "before_wrong": 1,
      "before_blank": 20,
      "after_correct": 172,
      "after_checked": 172,
      "after_pct": 100.0,
      "after_wrong": 0,
      "after_blank": 0
    },
    {
      "field": "floor_pct",
      "label": "Interest-rate floor",
      "short": "floor",
      "before_correct": 19,
      "before_checked": 63,
      "before_pct": 30.2,
      "before_wrong": 0,
      "before_blank": 44,
      "after_correct": 60,
      "after_checked": 60,
      "after_pct": 100.0,
      "after_wrong": 0,
      "after_blank": 0
    },
    {
      "field": "maturity_date",
      "label": "Maturity date",
      "short": "maturity date",
      "before_correct": 266,
      "before_checked": 267,
      "before_pct": 99.6,
      "before_wrong": 1,
      "before_blank": 0,
      "after_correct": 230,
      "after_checked": 230,
      "after_pct": 100.0,
      "after_wrong": 0,
      "after_blank": 0
    },
    {
      "field": "acquisition_date",
      "label": "Acquisition date",
      "short": "acquisition date",
      "before_correct": 109,
      "before_checked": 111,
      "before_pct": 98.2,
      "before_wrong": 0,
      "before_blank": 2,
      "after_correct": 102,
      "after_checked": 102,
      "after_pct": 100.0,
      "after_wrong": 0,
      "after_blank": 0
    },
    {
      "field": "non_accrual",
      "label": "Non-accrual flag",
      "short": "non-accrual flag",
      "before_correct": 275,
      "before_checked": 280,
      "before_pct": 98.2,
      "before_wrong": 1,
      "before_blank": 4,
      "after_correct": 277,
      "after_checked": 278,
      "after_pct": 99.6,
      "after_wrong": 0,
      "after_blank": 1
    },
    {
      "field": "pik",
      "label": "PIK (interest paid in kind)",
      "short": "PIK",
      "before_correct": 378,
      "before_checked": 396,
      "before_pct": 95.5,
      "before_wrong": 9,
      "before_blank": 9,
      "after_correct": 214,
      "after_checked": 214,
      "after_pct": 100.0,
      "after_wrong": 0,
      "after_blank": 0
    },
    {
      "field": "unfunded_commitment",
      "label": "Undrawn-commitment flag",
      "short": "undrawn-commitment flag",
      "before_correct": 111,
      "before_checked": 209,
      "before_pct": 53.1,
      "before_wrong": 0,
      "before_blank": 98,
      "after_correct": 86,
      "after_checked": 86,
      "after_pct": 100.0,
      "after_wrong": 0,
      "after_blank": 0
    }
  ],
  "remaining": [
    {
      "id": "S235",
      "ticker": "OCSL",
      "period_end": "2015-09-30",
      "company": "First Star Aviation, LLC",
      "field": "non_accrual",
      "label": "Non-accrual flag",
      "short": "non-accrual flag",
      "result": "left blank",
      "reason": "OCSL's fiscal-year-end 10-K for 2015-09-30 lists its non-accrual loans in a form the pipeline does not yet read, so that quarter shows OCSL's own total (4.92% of its debt at cost) and each loan's status is unknown rather than zero."
    }
  ],
  "not_published": [
    {
      "id": "S158",
      "ticker": "MAIN",
      "period_end": "2013-12-31"
    }
  ],
  "regressions": 0
};
