// AUTO-GENERATED by scripts/57 (model-curated). High-confidence borrower
// enrichment for the largest holdings: canonical sector, sub-sector and a
// one-line factual business description. NO financials (revenue/EBITDA) —
// those would be hallucination-prone in a model-curated source. Keyed by the
// borrowers_index slug. Cryptic PE codename SPVs are intentionally absent.

export interface BorrowerEnrichment {
  sector: string;
  sub_sector: string;
  description: string;
}

export const borrowerEnrichment: Record<string, BorrowerEnrichment> = {
  "inovalon": {
    "sector": "Healthcare",
    "sub_sector": "Healthcare IT / data analytics",
    "description": "Cloud-based healthcare data analytics for payers and providers."
  },
  "zendesk-inc": {
    "sector": "Software & IT",
    "sub_sector": "Application software (CX/CRM)",
    "description": "Customer-service and CRM software delivered as SaaS."
  },
  "guidehouse": {
    "sector": "Professional Services",
    "sub_sector": "Management consulting",
    "description": "Management and public-sector advisory / consulting firm."
  },
  "dropbox": {
    "sector": "Software & IT",
    "sub_sector": "Application software (storage)",
    "description": "Cloud file storage and collaboration platform (SaaS)."
  },
  "unified-women-s-healthcare": {
    "sector": "Healthcare",
    "sub_sector": "Provider / physician group",
    "description": "Women's-health (OB-GYN) physician practice management group."
  },
  "anaplan": {
    "sector": "Software & IT",
    "sub_sector": "Application software (planning)",
    "description": "Cloud connected-planning and performance-management software."
  },
  "circana": {
    "sector": "Professional Services",
    "sub_sector": "Market data & analytics",
    "description": "Consumer / retail market measurement and analytics (IRI + NPD)."
  },
  "auctane": {
    "sector": "Software & IT",
    "sub_sector": "E-commerce / shipping software",
    "description": "E-commerce shipping software (Stamps.com, ShipStation)."
  },
  "cambium-learning": {
    "sector": "Education",
    "sub_sector": "EdTech / curriculum",
    "description": "K-12 education software, assessment and curriculum."
  },
  "amerilife-holdings-llc": {
    "sector": "Insurance",
    "sub_sector": "Insurance distribution",
    "description": "Distributor / marketer of life, health and retirement products."
  },
  "medallia-inc": {
    "sector": "Software & IT",
    "sub_sector": "Application software (CX)",
    "description": "Customer- and employee-experience management software (SaaS)."
  },
  "baker-tilly-advisory": {
    "sector": "Professional Services",
    "sub_sector": "Accounting & advisory",
    "description": "Accounting, tax and advisory firm."
  },
  "loar": {
    "sector": "Industrial",
    "sub_sector": "Aerospace & defense",
    "description": "Manufacturer of niche aerospace & defense components."
  },
  "packaging-coordinators": {
    "sector": "Healthcare",
    "sub_sector": "Pharma services (CDMO)",
    "description": "Pharma contract development, manufacturing and packaging (PCI Pharma)."
  },
  "mantech-international-cp": {
    "sector": "Professional Services",
    "sub_sector": "Defense / federal IT",
    "description": "Defense and federal-government IT and engineering services."
  },
  "deerfield-dakota": {
    "sector": "Professional Services",
    "sub_sector": "Risk & financial advisory",
    "description": "Risk, governance and financial advisory (Kroll)."
  },
  "databricks": {
    "sector": "Software & IT",
    "sub_sector": "Data & AI platform",
    "description": "Data-lakehouse and AI/analytics platform."
  },
  "flexera": {
    "sector": "Software & IT",
    "sub_sector": "IT software management",
    "description": "Software asset management and IT spend optimization."
  },
  "cambrex": {
    "sector": "Healthcare",
    "sub_sector": "Pharma services (CDMO)",
    "description": "Small-molecule pharma contract development and manufacturing."
  },
  "teneo": {
    "sector": "Professional Services",
    "sub_sector": "Consulting / advisory",
    "description": "CEO advisory, communications and management consulting."
  },
  "west-monroe-partners-llc": {
    "sector": "Professional Services",
    "sub_sector": "Digital consulting",
    "description": "Digital and management consulting firm."
  },
  "pike": {
    "sector": "Utilities & Energy",
    "sub_sector": "Infrastructure services",
    "description": "Electric and telecom infrastructure construction and maintenance."
  },
  "smile-doctors-llc": {
    "sector": "Healthcare",
    "sub_sector": "Dental / orthodontics DSO",
    "description": "Orthodontics-focused dental support organization."
  },
  "bazaarvoice": {
    "sector": "Software & IT",
    "sub_sector": "Application software (retail)",
    "description": "Retail ratings, reviews and user-generated-content platform."
  },
  "cornerstone-ondemand": {
    "sector": "Software & IT",
    "sub_sector": "Application software (HCM)",
    "description": "Talent-management and corporate learning software (SaaS)."
  },
  "nintex-topco-limited": {
    "sector": "Software & IT",
    "sub_sector": "Application software (automation)",
    "description": "Process automation and workflow software."
  },
  "discovery-education-inc": {
    "sector": "Education",
    "sub_sector": "EdTech / curriculum",
    "description": "K-12 digital curriculum and instruction platform."
  },
  "petvet-care-centers": {
    "sector": "Healthcare",
    "sub_sector": "Veterinary services",
    "description": "Network of veterinary hospitals and clinics."
  },
  "proofpoint": {
    "sector": "Software & IT",
    "sub_sector": "Cybersecurity",
    "description": "Email security, compliance and data-protection software (SaaS)."
  },
  "gigamon-inc": {
    "sector": "Software & IT",
    "sub_sector": "Network security",
    "description": "Network visibility and security appliances / software."
  },
  "mri-software": {
    "sector": "Software & IT",
    "sub_sector": "Application software (real estate)",
    "description": "Real-estate and property-management software."
  },
  "monotype-imaging": {
    "sector": "Software & IT",
    "sub_sector": "Application software (fonts)",
    "description": "Typeface / font licensing and creative software."
  },
  "kaseya-inc": {
    "sector": "Software & IT",
    "sub_sector": "IT management software",
    "description": "IT management and security software for MSPs / SMBs."
  },
  "certinia": {
    "sector": "Software & IT",
    "sub_sector": "Application software (ERP)",
    "description": "ERP and professional-services automation on Salesforce."
  },
  "conservice": {
    "sector": "Professional Services",
    "sub_sector": "Utility management",
    "description": "Utility billing and expense management services."
  },
  "vensure-employer": {
    "sector": "Professional Services",
    "sub_sector": "HR outsourcing (PEO)",
    "description": "Professional employer organization / HR outsourcing."
  },
  "reddy-ice": {
    "sector": "Consumer / Retail",
    "sub_sector": "Packaged food / ice",
    "description": "Manufacturer and distributor of packaged ice."
  },
  "troon-golf-l-l-c": {
    "sector": "Consumer / Retail",
    "sub_sector": "Leisure / golf",
    "description": "Golf-course and club management services."
  },
  "sonny-s": {
    "sector": "Industrial",
    "sub_sector": "Car-wash equipment",
    "description": "Manufacturer of conveyorized car-wash equipment."
  },
  "big-brand-tire-service": {
    "sector": "Consumer / Retail",
    "sub_sector": "Auto services / retail",
    "description": "Tire and automotive service retail chain."
  },
  "audiotonix": {
    "sector": "Industrial",
    "sub_sector": "Professional audio",
    "description": "Professional audio mixing consoles and equipment."
  },
  "partssource": {
    "sector": "Healthcare",
    "sub_sector": "Medical supply marketplace",
    "description": "Marketplace for medical replacement parts and devices."
  },
  "winland-foods": {
    "sector": "Consumer / Retail",
    "sub_sector": "Packaged food (private label)",
    "description": "Private-label and contract food manufacturing."
  },
  "jeppesen": {
    "sector": "Software & IT",
    "sub_sector": "Aviation data / software",
    "description": "Aviation navigation charts and flight-planning data."
  },
  "integrity-marketing-group": {
    "sector": "Insurance",
    "sub_sector": "Insurance distribution",
    "description": "Life and health insurance distribution / marketing."
  },
  "associations": {
    "sector": "Real Estate",
    "sub_sector": "Community / HOA management",
    "description": "Community-association (HOA) management services."
  },
  "qualus-power": {
    "sector": "Utilities & Energy",
    "sub_sector": "Power services",
    "description": "Electric power engineering, testing and field services."
  },
  "cenexel": {
    "sector": "Healthcare",
    "sub_sector": "Clinical research",
    "description": "Network of clinical-trial research sites."
  },
  "apex-service-partners": {
    "sector": "Consumer / Retail",
    "sub_sector": "Home services",
    "description": "Residential HVAC, plumbing and electrical home services."
  },
  "banyan-software": {
    "sector": "Software & IT",
    "sub_sector": "Vertical-market software",
    "description": "Acquirer / operator of vertical-market software businesses."
  },
  "galway-borrower-llc": {
    "sector": "Insurance",
    "sub_sector": "Insurance brokerage",
    "description": "Retail and wholesale insurance brokerage (EPIC / Galway)."
  },
  "trucordia-insurance": {
    "sector": "Insurance",
    "sub_sector": "Insurance brokerage",
    "description": "Retail insurance brokerage / agency platform."
  },
  "smarsh": {
    "sector": "Software & IT",
    "sub_sector": "Compliance / archiving",
    "description": "Communications compliance, capture and archiving software."
  }
};
