// AUTO-GENERATED by scripts/52_build_dual_axis.py — do not edit.
// Dual-axis sector: every position's DELIVERY MODEL (what it IS) layered on
// the parser-cleaned end-market vertical. Model from a rule map over the
// enriched industry + an LLM override for software-hiding-in-a-vertical names.
// $ are USD millions, latest quarter.
export const deliveryModelAsOf = "2026-06-30";
export const deliveryModels = ["Software", "Tech-enabled services", "Healthcare provider", "Pharma / life sciences", "Insurance", "Financial services", "Industrial / manufacturing", "Consumer / retail", "Media / telecom", "Real estate", "Energy / utilities", "Fund / structured", "Other"];
export interface ModelRow { key: string; total_m: number; software_pct: number; [m: string]: number | string; }
export const modelByBdc: ModelRow[] = [{"key": "ARCC", "total_m": 29331.7, "Software": 11526.3, "Tech-enabled services": 2199.6, "Healthcare provider": 1487.0, "Pharma / life sciences": 835.2, "Insurance": 1530.4, "Financial services": 814.6, "Industrial / manufacturing": 2732.8, "Consumer / retail": 3124.3, "Media / telecom": 1174.5, "Real estate": 43.3, "Energy / utilities": 754.8, "Fund / structured": 1173.5, "Other": 1935.4, "software_pct": 39.3}];
export const modelByManager: ModelRow[] = [{"key": "Ares", "total_m": 29331.7, "Software": 11526.3, "Tech-enabled services": 2199.6, "Healthcare provider": 1487.0, "Pharma / life sciences": 835.2, "Insurance": 1530.4, "Financial services": 814.6, "Industrial / manufacturing": 2732.8, "Consumer / retail": 3124.3, "Media / telecom": 1174.5, "Real estate": 43.3, "Energy / utilities": 754.8, "Fund / structured": 1173.5, "Other": 1935.4, "software_pct": 39.3}];
export const softwareByVertical = [{"vertical": "Horizontal", "fv_m": 9056.2}, {"vertical": "Healthcare", "fv_m": 1213.1}, {"vertical": "Financial", "fv_m": 421.2}, {"vertical": "Consumer", "fv_m": 316.0}, {"vertical": "Government", "fv_m": 259.5}, {"vertical": "Education", "fv_m": 154.7}, {"vertical": "Energy", "fv_m": 79.4}, {"vertical": "Aerospace/Defense", "fv_m": 13.9}, {"vertical": "Real estate", "fv_m": 12.3}];
