// AUTO-GENERATED by scripts/78_early_warning_score.py — do not edit.
// Backtested early-warning score: P(first non-accrual within 2 quarters).
// Points per signal = measured lift on training history (≤2023-12-31),
// validated out-of-sample on 2024-2025 BEFORE publishing current scores.
// See ewsMeta for the measured multipliers and the validation table.

export interface EwsRow {
  ticker: string;
  borrower: string;
  score: number;
  signals: string[];
  fv_m: number;
  mark: number | null;
}

export const ewsMeta = {
  "as_of": "2026-03-31",
  "trained_through": "2023-12-31",
  "validated": "2024-03-31..2025-09-30",
  "train_base_rate_pct": 0.93,
  "validation_base_rate_pct": 0.66,
  "signal_multipliers": {
    "mark_below_90": 5.07,
    "mark_drop_3pt": 4.34,
    "pik_flip": 2.19,
    "modified": 0.84,
    "xholder_na": 1.3,
    "junior": 0.51
  },
  "signal_points": {
    "mark_below_90": 5,
    "mark_drop_3pt": 4,
    "pik_flip": 2,
    "modified": 0,
    "xholder_na": 1,
    "junior": 0
  },
  "validation_buckets": [
    {
      "bucket": "0",
      "n": 49581,
      "hit_rate_pct": 0.2
    },
    {
      "bucket": "1-2",
      "n": 3052,
      "hit_rate_pct": 0.95
    },
    {
      "bucket": "3-4",
      "n": 662,
      "hit_rate_pct": 2.42
    },
    {
      "bucket": "5-+",
      "n": 2410,
      "hit_rate_pct": 9.09
    }
  ],
  "precision_at_50_pct": 10.0
} as const;

export const ewsRows: EwsRow[] = [
  {"ticker": "GBDC", "borrower": "ERC Topco Holdings, LLC+(25)", "score": 12, "signals": ["mark_below_90", "mark_drop_3pt", "pik_flip", "xholder_na"], "fv_m": 6.5, "mark": 0.8},
  {"ticker": "BBDC", "borrower": "entertainment", "score": 12, "signals": ["mark_below_90", "mark_drop_3pt", "pik_flip", "xholder_na"], "fv_m": 4.3, "mark": 0.792},
  {"ticker": "BCRED", "borrower": "al gcx", "score": 11, "signals": ["mark_below_90", "mark_drop_3pt", "pik_flip"], "fv_m": 493.0, "mark": 0.795},
  {"ticker": "BCRED", "borrower": "rocket", "score": 11, "signals": ["mark_below_90", "mark_drop_3pt", "pik_flip"], "fv_m": 133.7, "mark": 0.89},
  {"ticker": "OTF", "borrower": "rocket", "score": 11, "signals": ["mark_below_90", "mark_drop_3pt", "pik_flip"], "fv_m": 69.4, "mark": 0.873},
  {"ticker": "ADS", "borrower": "mag ds", "score": 11, "signals": ["mark_below_90", "mark_drop_3pt", "pik_flip"], "fv_m": 47.6, "mark": 0.882},
  {"ticker": "BXSL", "borrower": "al gcx", "score": 11, "signals": ["mark_below_90", "mark_drop_3pt", "pik_flip"], "fv_m": 27.8, "mark": 0.795},
  {"ticker": "CGBD", "borrower": "xcentric mold", "score": 11, "signals": ["mark_below_90", "mark_drop_3pt", "pik_flip"], "fv_m": 18.6, "mark": 0.867},
  {"ticker": "BXSL", "borrower": "rocket", "score": 11, "signals": ["mark_below_90", "mark_drop_3pt", "pik_flip"], "fv_m": 14.8, "mark": 0.89},
  {"ticker": "BBDC", "borrower": "dunlipharder b v", "score": 11, "signals": ["mark_below_90", "mark_drop_3pt", "pik_flip"], "fv_m": 9.0, "mark": 0.747},
  {"ticker": "ARCC", "borrower": "openmarket", "score": 11, "signals": ["mark_below_90", "mark_drop_3pt", "pik_flip"], "fv_m": 8.7, "mark": 0.897},
  {"ticker": "MAIN", "borrower": "clad-rex steel", "score": 11, "signals": ["mark_below_90", "mark_drop_3pt", "pik_flip"], "fv_m": 7.8, "mark": 0.857},
  {"ticker": "ARCC", "borrower": "alphasense", "score": 11, "signals": ["mark_below_90", "mark_drop_3pt", "pik_flip"], "fv_m": 5.3, "mark": 0.898},
  {"ticker": "BBDC", "borrower": "powergem", "score": 11, "signals": ["mark_below_90", "mark_drop_3pt", "pik_flip"], "fv_m": 4.7, "mark": 0.836},
  {"ticker": "FSK", "borrower": "aerospace coatings", "score": 11, "signals": ["mark_below_90", "mark_drop_3pt", "pik_flip"], "fv_m": 3.3, "mark": 0.846},
  {"ticker": "ADS", "borrower": "MLN US Holdco LLC", "score": 11, "signals": ["mark_below_90", "mark_drop_3pt", "pik_flip"], "fv_m": 3.1, "mark": 0.45},
  {"ticker": "ARCC", "borrower": "Clarion Home Services Group, LLC and LBC Breeze Holdings LLC", "score": 11, "signals": ["mark_below_90", "mark_drop_3pt", "pik_flip"], "fv_m": 3.0, "mark": 0.857},
  {"ticker": "MAIN", "borrower": "quality lease", "score": 11, "signals": ["mark_below_90", "mark_drop_3pt", "pik_flip"], "fv_m": 2.7, "mark": 0.716},
  {"ticker": "GBDC", "borrower": "amalthea ^&", "score": 11, "signals": ["mark_below_90", "mark_drop_3pt", "pik_flip"], "fv_m": 2.7, "mark": 0.76},
  {"ticker": "BBDC", "borrower": "aviation technical", "score": 11, "signals": ["mark_below_90", "mark_drop_3pt", "pik_flip"], "fv_m": 1.3, "mark": 0.454},
  {"ticker": "BBDC", "borrower": "Scaled Agile, Inc.", "score": 11, "signals": ["mark_below_90", "mark_drop_3pt", "pik_flip"], "fv_m": 1.2, "mark": 0.638},
  {"ticker": "BBDC", "borrower": "powergem", "score": 11, "signals": ["mark_below_90", "mark_drop_3pt", "pik_flip"], "fv_m": 0.8, "mark": 0.836},
  {"ticker": "ASIF", "borrower": "alphasense", "score": 11, "signals": ["mark_below_90", "mark_drop_3pt", "pik_flip"], "fv_m": 0.6, "mark": 0.9},
  {"ticker": "ARCC", "borrower": "utility pipeline", "score": 11, "signals": ["mark_below_90", "mark_drop_3pt", "pik_flip"], "fv_m": 0.6, "mark": 0.75},
  {"ticker": "GBDC", "borrower": "connexin software", "score": 11, "signals": ["mark_below_90", "mark_drop_3pt", "pik_flip"], "fv_m": 0.6, "mark": 0.477},
  {"ticker": "BBDC", "borrower": "Scaled Agile, Inc.", "score": 11, "signals": ["mark_below_90", "mark_drop_3pt", "pik_flip"], "fv_m": 0.2, "mark": 0.638},
  {"ticker": "ARCC", "borrower": "arctic us", "score": 11, "signals": ["mark_below_90", "mark_drop_3pt", "pik_flip"], "fv_m": 0.2, "mark": 0.5},
  {"ticker": "ARCC", "borrower": "arctic us", "score": 11, "signals": ["mark_below_90", "mark_drop_3pt", "pik_flip"], "fv_m": 0.2, "mark": 0.5},
  {"ticker": "BBDC", "borrower": "dunlipharder b v", "score": 11, "signals": ["mark_below_90", "mark_drop_3pt", "pik_flip"], "fv_m": 0.2, "mark": 0.21},
  {"ticker": "GBDC", "borrower": "wildcat", "score": 11, "signals": ["mark_below_90", "mark_drop_3pt", "pik_flip"], "fv_m": 0.2, "mark": 0.702},
  {"ticker": "BBDC", "borrower": "artemis", "score": 11, "signals": ["mark_below_90", "mark_drop_3pt", "pik_flip"], "fv_m": 0.0, "mark": 0.0},
  {"ticker": "ARCC", "borrower": "calabrio", "score": 10, "signals": ["mark_below_90", "mark_drop_3pt", "xholder_na"], "fv_m": 54.9, "mark": 0.72},
  {"ticker": "ARCC", "borrower": "calabrio", "score": 10, "signals": ["mark_below_90", "mark_drop_3pt", "xholder_na"], "fv_m": 19.9, "mark": 0.701},
  {"ticker": "NMFC", "borrower": "wideopenwest finance", "score": 10, "signals": ["mark_below_90", "mark_drop_3pt", "xholder_na"], "fv_m": 14.8, "mark": 0.655},
  {"ticker": "ARCC", "borrower": "calabrio", "score": 10, "signals": ["mark_below_90", "mark_drop_3pt", "xholder_na"], "fv_m": 4.4, "mark": 0.71},
  {"ticker": "NMFC", "borrower": "wideopenwest finance", "score": 10, "signals": ["mark_below_90", "mark_drop_3pt", "xholder_na"], "fv_m": 2.8, "mark": 0.655},
  {"ticker": "NMFC", "borrower": "wideopenwest finance", "score": 10, "signals": ["mark_below_90", "mark_drop_3pt", "xholder_na"], "fv_m": 1.5, "mark": 0.65},
  {"ticker": "ARCC", "borrower": "calabrio", "score": 10, "signals": ["mark_below_90", "mark_drop_3pt", "xholder_na"], "fv_m": 0.6, "mark": 0.75},
  {"ticker": "BCRED", "borrower": "scientian 2 spain s l", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 433.3, "mark": 0.797},
  {"ticker": "BXSL", "borrower": "scientian 2 spain s l", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 213.2, "mark": 0.797},
  {"ticker": "BCRED", "borrower": "mitchell", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 114.5, "mark": 0.883},
  {"ticker": "OCIC", "borrower": "rocket", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 109.3, "mark": 0.872},
  {"ticker": "OBDC", "borrower": "Cornerstone OnDemand, Inc.(3)(4)(8)", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 109.1, "mark": 0.68},
  {"ticker": "ARCC", "borrower": "Cornerstone OnDemand, Inc. and Sunshine Software Holdings, I", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 103.1, "mark": 0.75},
  {"ticker": "BCRED", "borrower": "kaseya", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 100.5, "mark": 0.804},
  {"ticker": "BCRED", "borrower": "ppm clo 4 - class er", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 82.7, "mark": 0.629},
  {"ticker": "ADS", "borrower": "Excelligence Learning Corporation", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 72.1, "mark": 0.861},
  {"ticker": "OCIC", "borrower": "mitchell", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 71.7, "mark": 0.873},
  {"ticker": "OCIC", "borrower": "amerivet management", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 70.2, "mark": 0.9},
  {"ticker": "BCRED", "borrower": "HMH Education, Inc.", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 65.6, "mark": 0.815},
  {"ticker": "OTF", "borrower": "azurite", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 60.5, "mark": 0.715},
  {"ticker": "ASIF", "borrower": "citrin cooperman advisors", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 58.6, "mark": 0.878},
  {"ticker": "OBDC", "borrower": "rocket", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 57.0, "mark": 0.872},
  {"ticker": "BCRED", "borrower": "chg healthcare", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 51.9, "mark": 0.778},
  {"ticker": "OTF", "borrower": "Cornerstone OnDemand, Inc.(3)(4)(8)", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 48.7, "mark": 0.68},
  {"ticker": "OCIC", "borrower": "ruffalo noel levitz", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 47.5, "mark": 0.74},
  {"ticker": "BCRED", "borrower": "parexel", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 47.3, "mark": 0.762},
  {"ticker": "BCRED", "borrower": "Dcert Buyer, Inc.", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 47.1, "mark": 0.772},
  {"ticker": "ADS", "borrower": "citrin cooperman advisors", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 46.9, "mark": 0.883},
  {"ticker": "BCRED", "borrower": "ensemble rcm", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 46.8, "mark": 0.843},
  {"ticker": "BCRED", "borrower": "inhabit iq", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 46.3, "mark": 0.78},
  {"ticker": "OBDC", "borrower": "azurite", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 43.2, "mark": 0.715},
  {"ticker": "OCIC", "borrower": "denali onceforall", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 42.5, "mark": 0.888},
  {"ticker": "OCSL", "borrower": "northwoods capital 20", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 41.5, "mark": 0.712},
  {"ticker": "BXSL", "borrower": "inhabit iq", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 41.1, "mark": 0.78},
  {"ticker": "OCIC", "borrower": "parexel", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 40.1, "mark": 0.753},
  {"ticker": "BCRED", "borrower": "auditboard", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 37.1, "mark": 0.863},
  {"ticker": "BCRED", "borrower": "diagnostic", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 34.0, "mark": 0.797},
  {"ticker": "BCRED", "borrower": "wall street systems delaware", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 33.9, "mark": 0.852},
  {"ticker": "OCIC", "borrower": "premise health", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 33.7, "mark": 0.895},
  {"ticker": "CGBD", "borrower": "AQA Acquisition Holdings, Inc.", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 33.4, "mark": 0.834},
  {"ticker": "ARCC", "borrower": "elevation", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 31.4, "mark": 0.629},
  {"ticker": "BCRED", "borrower": "azurite", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 31.4, "mark": 0.725},
  {"ticker": "BCRED", "borrower": "parexel", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 30.4, "mark": 0.613},
  {"ticker": "OCIC", "borrower": "Cornerstone OnDemand, Inc.(3)(4)(8)", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 30.3, "mark": 0.68},
  {"ticker": "OCIC", "borrower": "ppt iii", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 30.3, "mark": 0.325},
  {"ticker": "OCIC", "borrower": "Learning Care Group (US) No. 2 Inc.(3)(9)", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 30.0, "mark": 0.721},
  {"ticker": "BCRED", "borrower": "belk common stock", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 29.4, "mark": 0.777},
  {"ticker": "ASIF", "borrower": "premise health", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 29.3, "mark": 0.895},
  {"ticker": "ASIF", "borrower": "anchc 2021-19", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 29.2, "mark": 0.787},
  {"ticker": "ASIF", "borrower": "anchc 2020-15", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 28.5, "mark": 0.879},
  {"ticker": "ARCC", "borrower": "athenahealth vvc virence", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 27.7, "mark": 0.868},
  {"ticker": "FSK", "borrower": "consolidated precision products", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 26.6, "mark": 0.884},
  {"ticker": "OTF", "borrower": "mitchell", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 26.2, "mark": 0.873},
  {"ticker": "ASIF", "borrower": "kaseya", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 26.1, "mark": 0.791},
  {"ticker": "OCIC", "borrower": "clydesdale", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 25.0, "mark": 0.805},
  {"ticker": "NMFC", "borrower": "peraton", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 23.9, "mark": 0.859},
  {"ticker": "BCRED", "borrower": "medx amcp", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 22.9, "mark": 0.88},
  {"ticker": "ADS", "borrower": "archduke", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 21.8, "mark": 0.681},
  {"ticker": "CGBD", "borrower": "bonterra", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 21.8, "mark": 0.882},
  {"ticker": "BCRED", "borrower": "Century Casinos, Inc.", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 21.5, "mark": 0.7},
  {"ticker": "ARCC", "borrower": "marco polo fund scsp-raif", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 21.3, "mark": 0.722},
  {"ticker": "HTGC", "borrower": "andesa", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 21.2, "mark": 0.747},
  {"ticker": "BCRED", "borrower": "trestles clo iv", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 20.6, "mark": 0.734},
  {"ticker": "OCIC", "borrower": "kaseya", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 19.9, "mark": 0.791},
  {"ticker": "OCIC", "borrower": "Plano HoldCo, Inc. (dba Perficient)(3)(9)", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 19.8, "mark": 0.8},
  {"ticker": "ASIF", "borrower": "amerivet management", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 19.6, "mark": 0.9},
  {"ticker": "OCIC", "borrower": "vensure employer", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 19.4, "mark": 0.778},
  {"ticker": "BCRED", "borrower": "chg healthcare", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 19.3, "mark": 0.896},
  {"ticker": "BCRED", "borrower": "diagnostic", "score": 9, "signals": ["mark_below_90", "mark_drop_3pt"], "fv_m": 18.9, "mark": 0.699}
];
