// AUTO-GENERATED by bdc_inventory/scripts/81_export_pnav.py — do not edit by hand.
// Equity issuance history + likely-issuer model.
/* eslint-disable */

export interface IssuerRow { ticker: string; pb: number; persistence: number; ttm_issuance_m: number; ttm_drip_m: number; ttm_buyback_m: number; ttm_pct_nav: number | null; leverage: number | null; score: number; est_12m_m: number; }

export const issuerModel: IssuerRow[] = [
  {"ticker": "CSWC", "pb": 1.496, "persistence": 100.0, "ttm_issuance_m": 179.3, "ttm_drip_m": 0.0, "ttm_buyback_m": 0.0, "ttm_pct_nav": 16.94, "leverage": 1.19, "score": 89.0, "est_12m_m": 224.0},
  {"ticker": "TRIN", "pb": 1.318, "persistence": 100.0, "ttm_issuance_m": 355.8, "ttm_drip_m": 2.8, "ttm_buyback_m": 0.0, "ttm_pct_nav": 28.08, "leverage": 1.21, "score": 89.0, "est_12m_m": 445.0},
  {"ticker": "MAIN", "pb": 1.721, "persistence": 100.0, "ttm_issuance_m": 149.9, "ttm_drip_m": 39.0, "ttm_buyback_m": 0.0, "ttm_pct_nav": 4.85, "leverage": 0.88, "score": 88.0, "est_12m_m": 187.0},
  {"ticker": "OXSQ", "pb": 1.144, "persistence": 89.0, "ttm_issuance_m": 32.4, "ttm_drip_m": 0.9, "ttm_buyback_m": 0.0, "ttm_pct_nav": 26.3, "leverage": 1.26, "score": 85.0, "est_12m_m": 41.0},
  {"ticker": "HTGC", "pb": 1.413, "persistence": 100.0, "ttm_issuance_m": 68.8, "ttm_drip_m": 12.3, "ttm_buyback_m": 6.2, "ttm_pct_nav": 3.02, "leverage": 1.06, "score": 77.0, "est_12m_m": 86.0},
  {"ticker": "FDUS", "pb": 1.061, "persistence": 30.0, "ttm_issuance_m": 78.2, "ttm_drip_m": 2.0, "ttm_buyback_m": 0.0, "ttm_pct_nav": 10.54, "leverage": 0.95, "score": 65.0, "est_12m_m": 78.0},
  {"ticker": "TSLX", "pb": 1.153, "persistence": 98.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 32.9, "ttm_buyback_m": 0.5, "ttm_pct_nav": 0.0, "leverage": 1.29, "score": 61.0, "est_12m_m": 31.0},
  {"ticker": "GAIN", "pb": 1.011, "persistence": 15.0, "ttm_issuance_m": 31.6, "ttm_drip_m": 0.0, "ttm_buyback_m": 0.0, "ttm_pct_nav": 4.72, "leverage": 0.98, "score": 37.0, "est_12m_m": 32.0},
  {"ticker": "ARCC", "pb": 1.002, "persistence": 3.0, "ttm_issuance_m": 226.0, "ttm_drip_m": 114.0, "ttm_buyback_m": 0.0, "ttm_pct_nav": 1.61, "leverage": 1.18, "score": 17.0, "est_12m_m": 226.0},
  {"ticker": "EQS", "pb": 0.931, "persistence": 71.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 0.0, "ttm_buyback_m": 0.0, "ttm_pct_nav": 0.0, "leverage": 0.29, "score": 7.0, "est_12m_m": 0.0},
  {"ticker": "MFIC", "pb": 0.725, "persistence": 0.0, "ttm_issuance_m": 440.1, "ttm_drip_m": 0.0, "ttm_buyback_m": 196.8, "ttm_pct_nav": 39.96, "leverage": 1.6, "score": 6.0, "est_12m_m": 44.0},
  {"ticker": "NSLR", "pb": 0.751, "persistence": 5.0, "ttm_issuance_m": 10.6, "ttm_drip_m": 0.0, "ttm_buyback_m": 5.9, "ttm_pct_nav": 2.98, "leverage": 0.18, "score": 6.0, "est_12m_m": 1.0},
  {"ticker": "GECC", "pb": 0.712, "persistence": 0.0, "ttm_issuance_m": 27.0, "ttm_drip_m": 0.0, "ttm_buyback_m": 0.0, "ttm_pct_nav": 24.46, "leverage": 1.54, "score": 6.0, "est_12m_m": 3.0},
  {"ticker": "RAND", "pb": 0.586, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 0.0, "ttm_buyback_m": 0.0, "ttm_pct_nav": 0.0, "leverage": 0.12, "score": 4.0, "est_12m_m": 0.0},
  {"ticker": "GLAD", "pb": 0.916, "persistence": 0.0, "ttm_issuance_m": 7.1, "ttm_drip_m": 0.0, "ttm_buyback_m": 0.0, "ttm_pct_nav": 1.46, "leverage": 1.0, "score": 4.0, "est_12m_m": 1.0},
  {"ticker": "HRZN", "pb": 0.744, "persistence": 0.0, "ttm_issuance_m": 10.5, "ttm_drip_m": 3.5, "ttm_buyback_m": 18.7, "ttm_pct_nav": 2.52, "leverage": 0.99, "score": 4.0, "est_12m_m": 1.0},
  {"ticker": "SCM", "pb": 0.671, "persistence": 0.0, "ttm_issuance_m": 17.8, "ttm_drip_m": 0.0, "ttm_buyback_m": 0.0, "ttm_pct_nav": 4.91, "leverage": 1.76, "score": 4.0, "est_12m_m": 2.0},
  {"ticker": "LIEN", "pb": 0.708, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 0.0, "ttm_buyback_m": 0.0, "ttm_pct_nav": 0.0, "leverage": 0.23, "score": 4.0, "est_12m_m": 0.0},
  {"ticker": "SAR", "pb": 0.845, "persistence": 0.0, "ttm_issuance_m": 12.6, "ttm_drip_m": 0.0, "ttm_buyback_m": 0.1, "ttm_pct_nav": 3.33, "leverage": 2.16, "score": 3.0, "est_12m_m": 1.0},
  {"ticker": "PFX", "pb": 0.558, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 0.0, "ttm_buyback_m": 6.5, "ttm_pct_nav": 0.0, "leverage": 0.96, "score": 3.0, "est_12m_m": 0.0},
  {"ticker": "MSIF", "pb": 0.744, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 9.2, "ttm_buyback_m": 30.2, "ttm_pct_nav": 0.0, "leverage": 0.96, "score": 3.0, "est_12m_m": 0.0},
  {"ticker": "OCSL", "pb": 0.808, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 6.8, "ttm_buyback_m": 6.8, "ttm_pct_nav": 0.0, "leverage": 1.07, "score": 2.0, "est_12m_m": 0.0},
  {"ticker": "RWAY", "pb": 0.494, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 0.0, "ttm_buyback_m": 8.7, "ttm_pct_nav": 0.0, "leverage": 1.06, "score": 2.0, "est_12m_m": 0.0},
  {"ticker": "KBDC", "pb": 0.861, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 0.0, "ttm_buyback_m": 74.1, "ttm_pct_nav": 0.0, "leverage": 1.09, "score": 2.0, "est_12m_m": 0.0},
  {"ticker": "OTF", "pb": 0.686, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 146.9, "ttm_buyback_m": 242.8, "ttm_pct_nav": 0.0, "leverage": 1.0, "score": 2.0, "est_12m_m": 0.0},
  {"ticker": "PSEC", "pb": 0.364, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 33.6, "ttm_buyback_m": 0.0, "ttm_pct_nav": 0.0, "leverage": 1.16, "score": 1.0, "est_12m_m": 0.0},
  {"ticker": "BBDC", "pb": 0.838, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 0.0, "ttm_buyback_m": 4.0, "ttm_pct_nav": 0.0, "leverage": 1.26, "score": 1.0, "est_12m_m": 0.0},
  {"ticker": "GBDC", "pb": 0.918, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 0.0, "ttm_buyback_m": 164.7, "ttm_pct_nav": 0.0, "leverage": 1.25, "score": 1.0, "est_12m_m": 0.0},
  {"ticker": "OBDC", "pb": 0.789, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 0.0, "ttm_buyback_m": 253.6, "ttm_pct_nav": 0.0, "leverage": 1.18, "score": 1.0, "est_12m_m": 0.0},
  {"ticker": "BXSL", "pb": 0.949, "persistence": 0.0, "ttm_issuance_m": 47.6, "ttm_drip_m": 43.5, "ttm_buyback_m": 0.0, "ttm_pct_nav": 0.8, "leverage": 1.32, "score": 1.0, "est_12m_m": 5.0},
  {"ticker": "MSDL", "pb": 0.785, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 0.0, "ttm_buyback_m": 26.7, "ttm_pct_nav": 0.0, "leverage": 1.26, "score": 1.0, "est_12m_m": 0.0},
  {"ticker": "TCPC", "pb": 0.581, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 2.1, "ttm_buyback_m": 5.6, "ttm_pct_nav": 0.0, "leverage": 1.67, "score": 0.0, "est_12m_m": 0.0},
  {"ticker": "BCIC", "pb": 0.471, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 0.3, "ttm_buyback_m": 20.6, "ttm_pct_nav": 0.0, "leverage": 1.82, "score": 0.0, "est_12m_m": 0.0},
  {"ticker": "PNNT", "pb": 0.542, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 0.0, "ttm_buyback_m": 0.0, "ttm_pct_nav": 0.0, "leverage": 1.86, "score": 0.0, "est_12m_m": 0.0},
  {"ticker": "SLRC", "pb": 0.723, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 0.0, "ttm_buyback_m": 0.0, "ttm_pct_nav": 0.0, "leverage": 1.61, "score": 0.0, "est_12m_m": 0.0},
  {"ticker": "FSK", "pb": 0.646, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 0.0, "ttm_buyback_m": 8.0, "ttm_pct_nav": 0.0, "leverage": 1.34, "score": 0.0, "est_12m_m": 0.0},
  {"ticker": "OFS", "pb": 0.446, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 0.0, "ttm_buyback_m": 0.0, "ttm_pct_nav": 0.0, "leverage": 1.7, "score": 0.0, "est_12m_m": 0.0},
  {"ticker": "NMFC", "pb": 0.707, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 0.0, "ttm_buyback_m": 107.9, "ttm_pct_nav": 0.0, "leverage": 1.35, "score": 0.0, "est_12m_m": 0.0},
  {"ticker": "PFLT", "pb": 0.699, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 0.0, "ttm_buyback_m": 0.0, "ttm_pct_nav": 0.0, "leverage": 1.65, "score": 0.0, "est_12m_m": 0.0},
  {"ticker": "CION", "pb": 0.547, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 0.0, "ttm_buyback_m": 64.3, "ttm_pct_nav": 0.0, "leverage": 1.77, "score": 0.0, "est_12m_m": 0.0},
  {"ticker": "CGBD", "pb": 0.671, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 0.0, "ttm_buyback_m": 32.4, "ttm_pct_nav": 0.0, "leverage": 1.29, "score": 0.0, "est_12m_m": 0.0},
  {"ticker": "WHF", "pb": 0.578, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 0.0, "ttm_buyback_m": 20.9, "ttm_pct_nav": 0.0, "leverage": 1.42, "score": 0.0, "est_12m_m": 0.0},
  {"ticker": "GSBD", "pb": 0.751, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 0.0, "ttm_buyback_m": 55.1, "ttm_pct_nav": 0.0, "leverage": 1.44, "score": 0.0, "est_12m_m": 0.0},
  {"ticker": "ICMB", "pb": 0.239, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 0.0, "ttm_buyback_m": 0.0, "ttm_pct_nav": 0.0, "leverage": 2.12, "score": 0.0, "est_12m_m": 0.0},
  {"ticker": "TPVG", "pb": 0.593, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 2.9, "ttm_buyback_m": 0.0, "ttm_pct_nav": 0.0, "leverage": 1.29, "score": 0.0, "est_12m_m": 0.0},
  {"ticker": "CCAP", "pb": 0.643, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 0.0, "ttm_buyback_m": 2.7, "ttm_pct_nav": 0.0, "leverage": 1.4, "score": 0.0, "est_12m_m": 0.0},
  {"ticker": "BCSF", "pb": 0.765, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 0.0, "ttm_buyback_m": 0.0, "ttm_pct_nav": 0.0, "leverage": 1.38, "score": 0.0, "est_12m_m": 0.0},
  {"ticker": "NCDL", "pb": 0.732, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 0.0, "ttm_buyback_m": 5.4, "ttm_pct_nav": 0.0, "leverage": 1.34, "score": 0.0, "est_12m_m": 0.0},
  {"ticker": "PSBD", "pb": 0.79, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 0.0, "ttm_buyback_m": 26.8, "ttm_pct_nav": 0.0, "leverage": 1.79, "score": 0.0, "est_12m_m": 0.0}
];

export const issuanceStackTickers: string[] = ["MFIC", "TRIN", "ARCC", "CSWC", "MAIN", "FDUS"];

export const issuanceByQuarter: Record<string, number | string>[] = [
  {"quarter": "2023-Q1", "CSWC": 28.8, "ARCC": 477.0, "MAIN": 40.9, "TRIN": 4.0, "Other": 208.3},
  {"quarter": "2023-Q2", "CSWC": 44.9, "ARCC": 227.0, "MAIN": 43.2, "TRIN": 9.5, "Other": 457.4},
  {"quarter": "2023-Q3", "CSWC": 22.5, "ARCC": 215.0, "MAIN": 81.1, "TRIN": 91.7, "Other": 582.3},
  {"quarter": "2023-Q4", "CSWC": 65.5, "ARCC": 236.0, "MAIN": 38.5, "TRIN": 45.0, "Other": 850.2},
  {"quarter": "2024-Q1", "CSWC": 48.5, "ARCC": 85.0, "MAIN": 5.7, "TRIN": 24.2, "Other": 1174.1},
  {"quarter": "2024-Q2", "CSWC": 37.8, "ARCC": 449.0, "MAIN": 42.2, "TRIN": 46.9, "Other": 880.8},
  {"quarter": "2024-Q3", "CSWC": 20.2, "MFIC": 440.1, "ARCC": 302.0, "MAIN": 65.8, "TRIN": 79.4, "Other": 433.7},
  {"quarter": "2024-Q4", "CSWC": 52.9, "ARCC": 528.0, "MAIN": 9.0, "TRIN": 49.7, "Other": 660.1},
  {"quarter": "2025-Q1", "CSWC": 67.5, "ARCC": 384.0, "MAIN": 5.2, "TRIN": 30.5, "Other": 643.9},
  {"quarter": "2025-Q2", "CSWC": 41.2, "ARCC": 318.0, "MAIN": 10.8, "TRIN": 81.5, "Other": 301.9},
  {"quarter": "2025-Q3", "CSWC": 39.7, "ARCC": 204.0, "MAIN": 6.9, "TRIN": 83.0, "Other": 133.1},
  {"quarter": "2025-Q4", "CSWC": 51.8, "MFIC": 440.1, "ARCC": 22.0, "MAIN": 8.8, "TRIN": 95.1, "Other": 46.4},
  {"quarter": "2026-Q1", "CSWC": 25.2, "MAIN": 134.3, "TRIN": 78.3, "Other": 65.4},
  {"quarter": "2026-Q2", "CSWC": 62.6, "TRIN": 99.5, "Other": 0.0}
];
