// AUTO-GENERATED by bdc_inventory/scripts/81_export_pnav.py — do not edit by hand.
// Equity issuance history + likely-issuer model.
/* eslint-disable */

export interface IssuerRow { ticker: string; pb: number; persistence: number; ttm_issuance_m: number; ttm_drip_m: number; ttm_buyback_m: number; ttm_pct_nav: number | null; leverage: number | null; score: number; est_12m_m: number; }

export const issuerModel: IssuerRow[] = [
  {"ticker": "MAIN", "pb": 1.725, "persistence": 100.0, "ttm_issuance_m": 168.8, "ttm_drip_m": 60.3, "ttm_buyback_m": 0.0, "ttm_pct_nav": 5.33, "leverage": 0.88, "score": 90.0, "est_12m_m": 211.0},
  {"ticker": "CSWC", "pb": 1.512, "persistence": 100.0, "ttm_issuance_m": 179.3, "ttm_drip_m": 0.0, "ttm_buyback_m": 0.0, "ttm_pct_nav": 16.94, "leverage": 1.19, "score": 89.0, "est_12m_m": 224.0},
  {"ticker": "TRIN", "pb": 1.358, "persistence": 100.0, "ttm_issuance_m": 355.8, "ttm_drip_m": 2.8, "ttm_buyback_m": 0.0, "ttm_pct_nav": 28.08, "leverage": 1.21, "score": 89.0, "est_12m_m": 445.0},
  {"ticker": "HTGC", "pb": 1.366, "persistence": 100.0, "ttm_issuance_m": 68.8, "ttm_drip_m": 12.3, "ttm_buyback_m": 6.2, "ttm_pct_nav": 3.02, "leverage": 1.06, "score": 77.0, "est_12m_m": 86.0},
  {"ticker": "TSLX", "pb": 1.158, "persistence": 98.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 32.9, "ttm_buyback_m": 0.5, "ttm_pct_nav": 0.0, "leverage": 1.29, "score": 61.0, "est_12m_m": 31.0},
  {"ticker": "FDUS", "pb": 1.013, "persistence": 35.0, "ttm_issuance_m": 78.2, "ttm_drip_m": 2.0, "ttm_buyback_m": 0.0, "ttm_pct_nav": 10.59, "leverage": 1.03, "score": 50.0, "est_12m_m": 78.0},
  {"ticker": "GAIN", "pb": 1.011, "persistence": 15.0, "ttm_issuance_m": 31.6, "ttm_drip_m": 0.0, "ttm_buyback_m": 0.0, "ttm_pct_nav": 4.88, "leverage": 1.01, "score": 36.0, "est_12m_m": 32.0},
  {"ticker": "ARCC", "pb": 1.027, "persistence": 9.0, "ttm_issuance_m": 226.0, "ttm_drip_m": 114.0, "ttm_buyback_m": 0.0, "ttm_pct_nav": 1.63, "leverage": 1.2, "score": 25.0, "est_12m_m": 226.0},
  {"ticker": "MFIC", "pb": 0.722, "persistence": 0.0, "ttm_issuance_m": 440.1, "ttm_drip_m": 0.0, "ttm_buyback_m": 196.8, "ttm_pct_nav": 39.96, "leverage": 1.6, "score": 6.0, "est_12m_m": 44.0},
  {"ticker": "RWAY", "pb": 0.569, "persistence": 0.0, "ttm_issuance_m": 87.2, "ttm_drip_m": 0.0, "ttm_buyback_m": 11.6, "ttm_pct_nav": 17.36, "leverage": 1.43, "score": 6.0, "est_12m_m": 9.0},
  {"ticker": "GLAD", "pb": 0.915, "persistence": 0.0, "ttm_issuance_m": 7.1, "ttm_drip_m": 0.0, "ttm_buyback_m": 0.0, "ttm_pct_nav": 1.46, "leverage": 1.0, "score": 4.0, "est_12m_m": 1.0},
  {"ticker": "HRZN", "pb": 0.798, "persistence": 0.0, "ttm_issuance_m": 10.5, "ttm_drip_m": 3.5, "ttm_buyback_m": 18.7, "ttm_pct_nav": 2.52, "leverage": 0.99, "score": 4.0, "est_12m_m": 1.0},
  {"ticker": "SCM", "pb": 0.684, "persistence": 0.0, "ttm_issuance_m": 17.8, "ttm_drip_m": 0.0, "ttm_buyback_m": 2.4, "ttm_pct_nav": 4.86, "leverage": 1.68, "score": 4.0, "est_12m_m": 2.0},
  {"ticker": "LIEN", "pb": 0.728, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 0.0, "ttm_buyback_m": 0.0, "ttm_pct_nav": 0.0, "leverage": 0.23, "score": 4.0, "est_12m_m": 0.0},
  {"ticker": "SAR", "pb": 0.834, "persistence": 0.0, "ttm_issuance_m": 12.6, "ttm_drip_m": 0.0, "ttm_buyback_m": 0.1, "ttm_pct_nav": 3.33, "leverage": 2.16, "score": 3.0, "est_12m_m": 1.0},
  {"ticker": "MSIF", "pb": 0.747, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 9.2, "ttm_buyback_m": 30.2, "ttm_pct_nav": 0.0, "leverage": 0.93, "score": 3.0, "est_12m_m": 0.0},
  {"ticker": "OCSL", "pb": 0.811, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 6.8, "ttm_buyback_m": 6.8, "ttm_pct_nav": 0.0, "leverage": 1.07, "score": 2.0, "est_12m_m": 0.0},
  {"ticker": "OTF", "pb": 0.698, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 146.9, "ttm_buyback_m": 242.8, "ttm_pct_nav": 0.0, "leverage": 1.0, "score": 2.0, "est_12m_m": 0.0},
  {"ticker": "PSEC", "pb": 0.379, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 33.6, "ttm_buyback_m": 0.0, "ttm_pct_nav": 0.0, "leverage": 1.16, "score": 1.0, "est_12m_m": 0.0},
  {"ticker": "BBDC", "pb": 0.844, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 0.0, "ttm_buyback_m": 4.0, "ttm_pct_nav": 0.0, "leverage": 1.26, "score": 1.0, "est_12m_m": 0.0},
  {"ticker": "GBDC", "pb": 0.919, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 0.0, "ttm_buyback_m": 164.7, "ttm_pct_nav": 0.0, "leverage": 1.25, "score": 1.0, "est_12m_m": 0.0},
  {"ticker": "CGBD", "pb": 0.711, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 0.0, "ttm_buyback_m": 44.9, "ttm_pct_nav": 0.0, "leverage": 1.26, "score": 1.0, "est_12m_m": 0.0},
  {"ticker": "OBDC", "pb": 0.818, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 0.0, "ttm_buyback_m": 253.6, "ttm_pct_nav": 0.0, "leverage": 1.18, "score": 1.0, "est_12m_m": 0.0},
  {"ticker": "BXSL", "pb": 0.956, "persistence": 0.0, "ttm_issuance_m": 47.6, "ttm_drip_m": 43.5, "ttm_buyback_m": 0.0, "ttm_pct_nav": 0.8, "leverage": 1.32, "score": 1.0, "est_12m_m": 19.0},
  {"ticker": "KBDC", "pb": 0.85, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 0.0, "ttm_buyback_m": 81.7, "ttm_pct_nav": 0.0, "leverage": 1.21, "score": 1.0, "est_12m_m": 0.0},
  {"ticker": "MSDL", "pb": 0.783, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 0.0, "ttm_buyback_m": 39.2, "ttm_pct_nav": 0.0, "leverage": 1.25, "score": 1.0, "est_12m_m": 0.0},
  {"ticker": "TCPC", "pb": 0.608, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 2.1, "ttm_buyback_m": 5.6, "ttm_pct_nav": 0.0, "leverage": 1.67, "score": 0.0, "est_12m_m": 0.0},
  {"ticker": "PNNT", "pb": 0.582, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 0.0, "ttm_buyback_m": 0.0, "ttm_pct_nav": 0.0, "leverage": 1.95, "score": 0.0, "est_12m_m": 0.0},
  {"ticker": "SLRC", "pb": 0.713, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 0.0, "ttm_buyback_m": 0.0, "ttm_pct_nav": 0.0, "leverage": 1.61, "score": 0.0, "est_12m_m": 0.0},
  {"ticker": "FSK", "pb": 0.665, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 0.0, "ttm_buyback_m": 8.0, "ttm_pct_nav": 0.0, "leverage": 1.34, "score": 0.0, "est_12m_m": 0.0},
  {"ticker": "NMFC", "pb": 0.708, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 0.0, "ttm_buyback_m": 107.9, "ttm_pct_nav": 0.0, "leverage": 1.35, "score": 0.0, "est_12m_m": 0.0},
  {"ticker": "PFLT", "pb": 0.729, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 0.0, "ttm_buyback_m": 0.0, "ttm_pct_nav": 0.0, "leverage": 1.59, "score": 0.0, "est_12m_m": 0.0},
  {"ticker": "CION", "pb": 0.548, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 0.0, "ttm_buyback_m": 64.3, "ttm_pct_nav": 0.0, "leverage": 1.77, "score": 0.0, "est_12m_m": 0.0},
  {"ticker": "WHF", "pb": 0.601, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 0.0, "ttm_buyback_m": 26.0, "ttm_pct_nav": 0.0, "leverage": 1.39, "score": 0.0, "est_12m_m": 0.0},
  {"ticker": "GSBD", "pb": 0.794, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 0.0, "ttm_buyback_m": 55.1, "ttm_pct_nav": 0.0, "leverage": 1.42, "score": 0.0, "est_12m_m": 0.0},
  {"ticker": "TPVG", "pb": 0.624, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 2.9, "ttm_buyback_m": 0.0, "ttm_pct_nav": 0.0, "leverage": 1.29, "score": 0.0, "est_12m_m": 0.0},
  {"ticker": "CCAP", "pb": 0.622, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 0.0, "ttm_buyback_m": 4.0, "ttm_pct_nav": 0.0, "leverage": 1.47, "score": 0.0, "est_12m_m": 0.0},
  {"ticker": "BCSF", "pb": 0.76, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 0.0, "ttm_buyback_m": 0.0, "ttm_pct_nav": 0.0, "leverage": 1.43, "score": 0.0, "est_12m_m": 0.0},
  {"ticker": "NCDL", "pb": 0.72, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 0.0, "ttm_buyback_m": 5.4, "ttm_pct_nav": 0.0, "leverage": 1.34, "score": 0.0, "est_12m_m": 0.0},
  {"ticker": "PSBD", "pb": 0.787, "persistence": 0.0, "ttm_issuance_m": 0.0, "ttm_drip_m": 0.0, "ttm_buyback_m": 26.8, "ttm_pct_nav": 0.0, "leverage": 1.79, "score": 0.0, "est_12m_m": 0.0}
];

export const issuanceStackTickers: string[] = ["MFIC", "TRIN", "ARCC", "CSWC", "MAIN", "RWAY"];

export const issuanceByQuarter: Record<string, number | string>[] = [
  {"quarter": "2023-Q1", "CSWC": 28.8, "ARCC": 477.0, "MAIN": 40.9, "TRIN": 4.0, "Other": 208.3},
  {"quarter": "2023-Q2", "CSWC": 44.9, "ARCC": 227.0, "MAIN": 43.2, "TRIN": 9.5, "Other": 457.4},
  {"quarter": "2023-Q3", "CSWC": 22.5, "ARCC": 215.0, "MAIN": 81.1, "TRIN": 91.7, "Other": 577.9},
  {"quarter": "2023-Q4", "CSWC": 65.5, "ARCC": 236.0, "MAIN": 38.5, "TRIN": 45.0, "Other": 846.5},
  {"quarter": "2024-Q1", "CSWC": 48.5, "ARCC": 85.0, "MAIN": 5.7, "TRIN": 24.2, "Other": 1149.3},
  {"quarter": "2024-Q2", "CSWC": 37.8, "ARCC": 449.0, "MAIN": 42.2, "TRIN": 46.9, "Other": 859.9},
  {"quarter": "2024-Q3", "CSWC": 20.2, "MFIC": 440.1, "ARCC": 302.0, "MAIN": 65.8, "TRIN": 79.4, "Other": 419.0},
  {"quarter": "2024-Q4", "CSWC": 52.9, "ARCC": 528.0, "MAIN": 9.0, "TRIN": 49.7, "Other": 642.1},
  {"quarter": "2025-Q1", "CSWC": 67.5, "ARCC": 384.0, "MAIN": 5.2, "TRIN": 30.5, "Other": 640.3},
  {"quarter": "2025-Q2", "CSWC": 41.2, "ARCC": 318.0, "MAIN": 10.8, "TRIN": 81.5, "Other": 290.1},
  {"quarter": "2025-Q3", "CSWC": 39.7, "ARCC": 204.0, "MAIN": 6.9, "TRIN": 83.0, "Other": 94.1},
  {"quarter": "2025-Q4", "CSWC": 51.8, "MFIC": 440.1, "ARCC": 22.0, "MAIN": 8.8, "TRIN": 95.1, "Other": 38.4},
  {"quarter": "2026-Q1", "CSWC": 25.2, "MAIN": 134.3, "TRIN": 78.3, "Other": 52.9},
  {"quarter": "2026-Q2", "CSWC": 62.6, "MAIN": 18.9, "TRIN": 99.5, "Other": 0.0}
];
