// AUTO-GENERATED by scripts/50_export_dashboard_data.py — do not edit by hand.
// Long-tail BDCs sourced from SEC DERA bulk data (via edgartools.bdc).
// These are BDCs we don't parse in-house. Use for cross-issuer borrower
// search and broader universe context. Dollar amounts are RAW USD.

export interface LongTailBDC {
  cik: number;
  name: string;
  n_periods: number;
  earliest_period: string;
  latest_period: string;
  latest_n_positions: number;
  latest_fair_value_b: number;
  latest_cost_b: number;
}

export const longTailBDCs: LongTailBDC[] = [
  { cik: 1930087, name: "GOLUB CAPITAL PRIVATE CREDIT FUND", n_periods: 11, earliest_period: "2023-06-30", latest_period: "2025-12-31", latest_n_positions: 1002, latest_fair_value_b: 9.829, latest_cost_b: 9.756 },
  { cik: 1925309, name: "SIXTH STREET LENDING PARTNERS", n_periods: 16, earliest_period: "2022-03-31", latest_period: "2025-12-31", latest_n_positions: 120, latest_fair_value_b: 8.111, latest_cost_b: 7.893 },
  { cik: 1872371, name: "OAKTREE STRATEGIC CREDIT FUND", n_periods: 15, earliest_period: "2022-09-30", latest_period: "2025-12-31", latest_n_positions: 385, latest_fair_value_b: 7.434, latest_cost_b: 7.429 },
  { cik: 1889668, name: "BLUE OWL TECHNOLOGY FINANCE CORP. II", n_periods: 10, earliest_period: "2021-12-31", latest_period: "2024-12-31", latest_n_positions: 298, latest_fair_value_b: 5.557, latest_cost_b: 5.371 },
  { cik: 1859919, name: "BARINGS PRIVATE CREDIT CORP", n_periods: 30, earliest_period: "2021-04-30", latest_period: "2025-12-31", latest_n_positions: 808, latest_fair_value_b: 5.125, latest_cost_b: 4.898 },
  { cik: 1807427, name: "BLUE OWL CAPITAL CORP III", n_periods: 9, earliest_period: "2021-12-31", latest_period: "2024-09-30", latest_n_positions: 452, latest_fair_value_b: 4.376, latest_cost_b: 4.233 },
  { cik: 1504619, name: "PENNANTPARK FLOATING RATE CAPITAL LTD.", n_periods: 15, earliest_period: "2021-09-30", latest_period: "2025-12-31", latest_n_positions: 683, latest_fair_value_b: 3.994, latest_cost_b: 3.953 },
  { cik: 1782524, name: "MORGAN STANLEY DIRECT LENDING FUND", n_periods: 14, earliest_period: "2019-12-31", latest_period: "2025-12-31", latest_n_positions: 608, latest_fair_value_b: 3.767, latest_cost_b: 3.839 },
  { cik: 1377936, name: "SARATOGA INVESTMENT CORP.", n_periods: 20, earliest_period: "2008-01-31", latest_period: "2025-11-30", latest_n_positions: 162, latest_fair_value_b: 3.048, latest_cost_b: 3.081 },
  { cik: 1383414, name: "PENNANTPARK INVESTMENT CORP", n_periods: 16, earliest_period: "2021-09-30", latest_period: "2025-12-31", latest_n_positions: 594, latest_fair_value_b: 2.942, latest_cost_b: 2.62 },
  { cik: 1786108, name: "TRINITY CAPITAL INC.", n_periods: 16, earliest_period: "2020-12-31", latest_period: "2025-12-31", latest_n_positions: 456, latest_fair_value_b: 2.941, latest_cost_b: 2.373 },
  { cik: 1572694, name: "GOLDMAN SACHS BDC, INC.", n_periods: 15, earliest_period: "2021-12-31", latest_period: "2025-12-31", latest_n_positions: 524, latest_fair_value_b: 2.909, latest_cost_b: 3.2 },
  { cik: 1715268, name: "GOLUB CAPITAL BDC 3, INC.", n_periods: 6, earliest_period: "2022-09-30", latest_period: "2024-03-31", latest_n_positions: 1350, latest_fair_value_b: 2.699, latest_cost_b: 2.712 },
  { cik: 1655050, name: "BAIN CAPITAL SPECIALTY FINANCE, INC.", n_periods: 20, earliest_period: "2020-12-31", latest_period: "2025-12-31", latest_n_positions: 475, latest_fair_value_b: 2.508, latest_cost_b: 2.485 },
  { cik: 17313, name: "CAPITAL SOUTHWEST CORP", n_periods: 15, earliest_period: "2022-03-31", latest_period: "2025-12-31", latest_n_positions: 531, latest_fair_value_b: 2.405, latest_cost_b: 2.031 },
  { cik: 1901612, name: "GOLUB CAPITAL BDC 4, INC.", n_periods: 13, earliest_period: "2022-09-30", latest_period: "2025-12-31", latest_n_positions: 841, latest_fair_value_b: 2.372, latest_cost_b: 2.341 },
  { cik: 1418076, name: "SLR INVESTMENT CORP.", n_periods: 17, earliest_period: "2020-12-31", latest_period: "2025-12-31", latest_n_positions: 132, latest_fair_value_b: 2.306, latest_cost_b: 2.335 },
  { cik: 2037804, name: "NEW MOUNTAIN PRIVATE CREDIT FUND", n_periods: 7, earliest_period: "2023-12-31", latest_period: "2025-12-31", latest_n_positions: 382, latest_fair_value_b: 2.078, latest_cost_b: 2.143 },
  { cik: 1737924, name: "NUVEEN CHURCHILL DIRECT LENDING CORP.", n_periods: 14, earliest_period: "2022-12-31", latest_period: "2025-12-31", latest_n_positions: 528, latest_fair_value_b: 1.962, latest_cost_b: 2.001 },
  { cik: 1501729, name: "FS SPECIALTY LENDING FUND", n_periods: 14, earliest_period: "2019-12-31", latest_period: "2025-06-30", latest_n_positions: 123, latest_fair_value_b: 1.928, latest_cost_b: 1.78 },
  { cik: 1370755, name: "BLACKROCK TCP CAPITAL CORP.", n_periods: 15, earliest_period: "2021-12-31", latest_period: "2025-12-31", latest_n_positions: 363, latest_fair_value_b: 1.706, latest_cost_b: 1.678 },
  { cik: 1885968, name: "T SERIES MIDDLE MARKET LOAN FUND LLC", n_periods: 5, earliest_period: "2021-09-30", latest_period: "2023-09-30", latest_n_positions: 275, latest_fair_value_b: 1.544, latest_cost_b: 1.562 },
  { cik: 1781870, name: "NEW MOUNTAIN GUARDIAN III BDC, L.L.C.", n_periods: 8, earliest_period: "2022-12-31", latest_period: "2024-09-30", latest_n_positions: 196, latest_fair_value_b: 1.539, latest_cost_b: 1.561 },
  { cik: 2049733, name: "BLACKSTONE PRIVATE REAL ESTATE CREDIT & INCOME FUND", n_periods: 3, earliest_period: "2025-06-30", latest_period: "2025-12-31", latest_n_positions: 113, latest_fair_value_b: 1.528, latest_cost_b: 1.516 },
  { cik: 1535778, name: "MSC INCOME FUND, INC.", n_periods: 17, earliest_period: "2021-12-31", latest_period: "2025-12-31", latest_n_positions: 505, latest_fair_value_b: 1.41, latest_cost_b: 1.26 },
  { cik: 1811972, name: "BARINGS CAPITAL INVESTMENT CORP", n_periods: 18, earliest_period: "2021-06-30", latest_period: "2025-12-31", latest_n_positions: 608, latest_fair_value_b: 1.366, latest_cost_b: 1.35 },
  { cik: 2018545, name: "FRANKLIN BSP REAL ESTATE DEBT BDC", n_periods: 5, earliest_period: "2024-06-30", latest_period: "2025-06-30", latest_n_positions: 65, latest_fair_value_b: 1.275, latest_cost_b: 1.265 },
  { cik: 1321741, name: "GLADSTONE INVESTMENT CORPORATIONDE", n_periods: 25, earliest_period: "2012-08-31", latest_period: "2025-12-31", latest_n_positions: 64, latest_fair_value_b: 1.223, latest_cost_b: 1.059 },
  { cik: 1794776, name: "PALMER SQUARE CAPITAL BDC INC.", n_periods: 13, earliest_period: "2021-12-31", latest_period: "2025-12-31", latest_n_positions: 264, latest_fair_value_b: 1.204, latest_cost_b: 1.295 },
  { cik: 1490349, name: "PHENIXFIN CORP", n_periods: 19, earliest_period: "2020-09-30", latest_period: "2025-12-31", latest_n_positions: 94, latest_fair_value_b: 1.183, latest_cost_b: 1.27 },
  { cik: 1825590, name: "SL INVESTMENT CORP.", n_periods: 5, earliest_period: "2022-03-31", latest_period: "2023-09-30", latest_n_positions: 347, latest_fair_value_b: 1.149, latest_cost_b: 1.16 },
  { cik: 1587987, name: "NEWTEK BUSINESS SERVICES CORP.", n_periods: 4, earliest_period: "2016-06-30", latest_period: "2022-09-30", latest_n_positions: 3611, latest_fair_value_b: 1.119, latest_cost_b: 0.693 }
];
