// AUTO-GENERATED by scripts/54_export_maturity.py — do not edit by hand.
// Maturity wall: each covered BDC's DEBT bucketed by the calendar year it
// comes due, in USD millions of AMORTIZED COST (par_amount is misparsed in
// several BDCs, so cost — the field every 'at cost' metric uses — is the
// trusted size measure; fair value is carried for a mark-adjusted toggle).
// Equity/warrants/JV (no fixed maturity) are excluded. A BDC is dropped from
// the aggregate when <10% of its debt has a parseable maturity (see meta.excluded).

export interface MaturityBucket { ticker: string; bucket: string; cost_m: number; fv_m: number; n_loans: number; }
export interface MaturityAggRow { bucket: string; cost_m: number; fv_m: number; n_loans: number; }
export interface MaturityCompare {
  ticker: string;
  debt_cost_m: number;
  debt_fv_m: number;
  n_debt: number;
  coverage_pct: number;
  wavg_years: number | null;
  pct_near24m: number;
  pct_le2025: number;
  pct_2026: number;
  pct_2027: number;
  pct_2028: number;
  pct_2029: number;
  pct_2030: number;
  pct_2031: number;
  pct_2032: number;
  pct_2033plus: number;
}
export interface MaturityMeta {
  as_of: string; n_bdcs: number; buckets: string[]; weighting: string;
  excluded: Array<{ ticker: string; reason: string; coverage_pct: number }>;
}

export const maturityByBdc: MaturityBucket[] = [{"ticker": "ARCC", "bucket": "2026", "cost_m": 182.7, "fv_m": 139.9, "n_loans": 17}, {"ticker": "ARCC", "bucket": "2027", "cost_m": 1069.9, "fv_m": 986.6, "n_loans": 84}, {"ticker": "ARCC", "bucket": "2028", "cost_m": 2288.6, "fv_m": 2084.9, "n_loans": 150}, {"ticker": "ARCC", "bucket": "2029", "cost_m": 3203.4, "fv_m": 3022.5, "n_loans": 190}, {"ticker": "ARCC", "bucket": "2030", "cost_m": 4751.3, "fv_m": 4656.6, "n_loans": 178}, {"ticker": "ARCC", "bucket": "2031", "cost_m": 4294.4, "fv_m": 4232.2, "n_loans": 194}, {"ticker": "ARCC", "bucket": "2032", "cost_m": 4524.8, "fv_m": 4431.1, "n_loans": 147}, {"ticker": "ARCC", "bucket": "2033+", "cost_m": 3017.9, "fv_m": 2999.2, "n_loans": 47}];

export const maturityAggregate: MaturityAggRow[] = [{"bucket": "<=2025", "cost_m": 0.0, "fv_m": 0.0, "n_loans": 0}, {"bucket": "2026", "cost_m": 182.7, "fv_m": 139.9, "n_loans": 17}, {"bucket": "2027", "cost_m": 1069.9, "fv_m": 986.6, "n_loans": 84}, {"bucket": "2028", "cost_m": 2288.6, "fv_m": 2084.9, "n_loans": 150}, {"bucket": "2029", "cost_m": 3203.4, "fv_m": 3022.5, "n_loans": 190}, {"bucket": "2030", "cost_m": 4751.3, "fv_m": 4656.6, "n_loans": 178}, {"bucket": "2031", "cost_m": 4294.4, "fv_m": 4232.2, "n_loans": 194}, {"bucket": "2032", "cost_m": 4524.8, "fv_m": 4431.1, "n_loans": 147}, {"bucket": "2033+", "cost_m": 3017.9, "fv_m": 2999.2, "n_loans": 47}];

export const maturityComparison: MaturityCompare[] = [{"ticker": "ARCC", "debt_cost_m": 23333.0, "debt_fv_m": 22553.0, "n_debt": 1007, "coverage_pct": 92.0, "wavg_years": 4.61, "pct_near24m": 5.4, "pct_le2025": 0.0, "pct_2026": 0.8, "pct_2027": 4.6, "pct_2028": 9.8, "pct_2029": 13.7, "pct_2030": 20.4, "pct_2031": 18.4, "pct_2032": 19.4, "pct_2033plus": 12.9}];

export const maturityMeta: MaturityMeta = {"as_of": "2026-06-30", "n_bdcs": 1, "buckets": ["<=2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033+"], "weighting": "amortized_cost", "excluded": []};
