// AUTO-GENERATED by scripts/83_forecast_non_accrual.py — do not edit by hand.
// Forward non-accrual rate per BDC, % of amortized cost, 1 and 2 quarters out.
//
// forecast = na - k*(na - own 8-quarter mean) + b * watchlist-High %
//
// Non-accrual rates are highly persistent (corr 0.77 q/q), so this is
// persistence adjusted for the two measurable effects: mean reversion as
// workouts resolve, and inflow from the watchlist High tier. Coefficients were
// picked by walk-forward grid search; naFcMeta carries the measured accuracy
// against simply carrying the current rate forward, INCLUDING where naive still
// wins. lo/hi are the empirical 10th-90th percentile of walk-forward signed
// errors — calibrated on realised misses, not an assumed distribution.
/* eslint-disable */

export interface NaForecastRow {
  ticker: string; period_end: string;
  na_now: number; na_mean8: number; wl_high_pct: number; has_watchlist: boolean;
  q1_label: string; na_q1: number; lo_q1: number; hi_q1: number;
  q2_label: string; na_q2: number; lo_q2: number; hi_q2: number;
  // Direction, which ranks better than the level does. p_rise is
  // P(rate rises >= 0.5pp next quarter); xh_pp is the share of cost in
  // borrowers ALREADY non-accrual at another BDC — the strongest single
  // input (17x lift at the name level).
  p_rise: number | null; xh_pp: number | null; b90_pp: number | null;
  // HEADLINE: expected NEW non-accrual formation over the next four
  // quarters, % of cost, with an empirical 80% band. Ranks far better
  // than any next-quarter number — see naFcMeta.formation.quartiles.
  form_4q: number | null; form_lo: number | null; form_hi: number | null;
  form_trailing: number | null;
}

export const naForecast: NaForecastRow[] = [
  {"ticker": "FSK", "period_end": "2026-06-30", "na_now": 6.55, "na_mean8": 5.226, "wl_high_pct": 0.0, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 6.087, "lo_q1": 5.388, "hi_q1": 7.043, "q2_label": "2026-Q4", "na_q2": 6.087, "lo_q2": 5.215, "hi_q2": 7.364, "p_rise": 0.362, "xh_pp": 0.0, "b90_pp": 31.69, "form_4q": 4.867, "form_lo": 3.937, "form_hi": 7.236, "form_trailing": 6.115},
  {"ticker": "BXSL", "period_end": "2026-06-30", "na_now": 3.51, "na_mean8": 1.232, "wl_high_pct": 0.473, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 2.76, "lo_q1": 2.061, "hi_q1": 3.716, "q2_label": "2026-Q4", "na_q2": 2.855, "lo_q2": 1.983, "hi_q2": 4.132, "p_rise": 0.234, "xh_pp": 0.655, "b90_pp": 7.431, "form_4q": 3.53, "form_lo": 2.6, "form_hi": 5.899, "form_trailing": 4.77},
  {"ticker": "NMFC", "period_end": "2026-06-30", "na_now": 2.79, "na_mean8": 2.153, "wl_high_pct": 0.256, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 2.592, "lo_q1": 1.894, "hi_q1": 3.549, "q2_label": "2026-Q4", "na_q2": 2.644, "lo_q2": 1.772, "hi_q2": 3.921, "p_rise": 0.524, "xh_pp": 3.57, "b90_pp": 21.259, "form_4q": 3.348, "form_lo": 2.418, "form_hi": 5.717, "form_trailing": 2.325},
  {"ticker": "BCRED", "period_end": "2026-06-30", "na_now": 2.08, "na_mean8": 0.86, "wl_high_pct": 1.606, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 1.814, "lo_q1": 1.115, "hi_q1": 2.77, "q2_label": "2026-Q4", "na_q2": 2.135, "lo_q2": 1.264, "hi_q2": 3.412, "p_rise": 0.233, "xh_pp": 0.405, "b90_pp": 10.098, "form_4q": 2.769, "form_lo": 1.839, "form_hi": 5.138, "form_trailing": 2.962},
  {"ticker": "CGBD", "period_end": "2026-06-30", "na_now": 1.22, "na_mean8": 1.647, "wl_high_pct": 0.802, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 1.45, "lo_q1": 0.751, "hi_q1": 2.406, "q2_label": "2026-Q4", "na_q2": 1.61, "lo_q2": 0.739, "hi_q2": 2.887, "p_rise": 0.332, "xh_pp": 1.694, "b90_pp": 6.431, "form_4q": 2.332, "form_lo": 1.402, "form_hi": 4.702, "form_trailing": 1.886},
  {"ticker": "OCSL", "period_end": "2026-06-30", "na_now": 3.82, "na_mean8": 5.404, "wl_high_pct": 1.354, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 4.51, "lo_q1": 3.811, "hi_q1": 5.466, "q2_label": "2026-Q4", "na_q2": 4.78, "lo_q2": 3.909, "hi_q2": 6.058, "p_rise": 0.207, "xh_pp": 0.589, "b90_pp": 15.741, "form_4q": 2.121, "form_lo": 1.191, "form_hi": 4.49, "form_trailing": 1.533},
  {"ticker": "ARCC", "period_end": "2026-06-30", "na_now": 2.38, "na_mean8": 1.806, "wl_high_pct": 0.977, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 2.277, "lo_q1": 1.578, "hi_q1": 3.233, "q2_label": "2026-Q4", "na_q2": 2.472, "lo_q2": 1.601, "hi_q2": 3.749, "p_rise": 0.364, "xh_pp": 1.779, "b90_pp": 11.351, "form_4q": 2.112, "form_lo": 1.182, "form_hi": 4.481, "form_trailing": 1.268},
  {"ticker": "MAIN", "period_end": "2026-06-30", "na_now": 3.99, "na_mean8": 3.975, "wl_high_pct": 0.923, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 4.077, "lo_q1": 3.378, "hi_q1": 5.033, "q2_label": "2026-Q4", "na_q2": 4.262, "lo_q2": 3.39, "hi_q2": 5.539, "p_rise": 0.213, "xh_pp": 0.387, "b90_pp": 10.176, "form_4q": 2.055, "form_lo": 1.125, "form_hi": 4.425, "form_trailing": 1.752},
  {"ticker": "BBDC", "period_end": "2026-06-30", "na_now": 1.53, "na_mean8": 1.662, "wl_high_pct": 0.879, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 1.664, "lo_q1": 0.966, "hi_q1": 2.62, "q2_label": "2026-Q4", "na_q2": 1.84, "lo_q2": 0.969, "hi_q2": 3.118, "p_rise": 0.192, "xh_pp": 0.216, "b90_pp": 8.892, "form_4q": 1.832, "form_lo": 0.902, "form_hi": 4.201, "form_trailing": 1.218},
  {"ticker": "GBDC", "period_end": "2026-06-30", "na_now": 2.94, "na_mean8": 1.531, "wl_high_pct": 0.558, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 2.503, "lo_q1": 1.804, "hi_q1": 3.459, "q2_label": "2026-Q4", "na_q2": 2.614, "lo_q2": 1.743, "hi_q2": 3.892, "p_rise": 0.485, "xh_pp": 3.828, "b90_pp": 3.544, "form_4q": 1.706, "form_lo": 0.775, "form_hi": 4.075, "form_trailing": 0.0},
  {"ticker": "HTGC", "period_end": "2026-06-30", "na_now": 0.35, "na_mean8": 1.034, "wl_high_pct": 0.0, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 0.589, "lo_q1": 0.0, "hi_q1": 1.545, "q2_label": "2026-Q4", "na_q2": 0.589, "lo_q2": 0.0, "hi_q2": 1.867, "p_rise": 0.144, "xh_pp": 0.0, "b90_pp": 5.446, "form_4q": 1.457, "form_lo": 0.527, "form_hi": 3.826, "form_trailing": 1.324},
  {"ticker": "CCAP", "period_end": "2026-06-30", "na_now": 4.47, "na_mean8": 3.294, "wl_high_pct": 0.484, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 4.107, "lo_q1": 3.408, "hi_q1": 5.063, "q2_label": "2026-Q4", "na_q2": 4.203, "lo_q2": 3.332, "hi_q2": 5.481, "p_rise": 0.223, "xh_pp": 0.539, "b90_pp": 10.833, "form_4q": 1.233, "form_lo": 0.303, "form_hi": 3.602, "form_trailing": 0.0},
  {"ticker": "ADS", "period_end": "2026-06-30", "na_now": 0.79, "na_mean8": 0.659, "wl_high_pct": 0.802, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 0.824, "lo_q1": 0.126, "hi_q1": 1.78, "q2_label": "2026-Q4", "na_q2": 0.985, "lo_q2": 0.113, "hi_q2": 2.262, "p_rise": 0.23, "xh_pp": 0.969, "b90_pp": 2.736, "form_4q": 1.191, "form_lo": 0.261, "form_hi": 3.56, "form_trailing": 0.765},
  {"ticker": "OTF", "period_end": "2026-06-30", "na_now": 0.58, "na_mean8": 0.28, "wl_high_pct": 1.344, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 0.609, "lo_q1": 0.0, "hi_q1": 1.565, "q2_label": "2026-Q4", "na_q2": 0.878, "lo_q2": 0.007, "hi_q2": 2.155, "p_rise": 0.256, "xh_pp": 1.195, "b90_pp": 9.664, "form_4q": 1.161, "form_lo": 0.231, "form_hi": 3.53, "form_trailing": 0.0},
  {"ticker": "MFIC", "period_end": "2026-06-30", "na_now": 0.0, "na_mean8": 0.0, "wl_high_pct": 0.25, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 0.025, "lo_q1": 0.0, "hi_q1": 0.981, "q2_label": "2026-Q4", "na_q2": 0.075, "lo_q2": 0.0, "hi_q2": 1.352, "p_rise": 0.227, "xh_pp": 0.373, "b90_pp": 23.358, "form_4q": 1.134, "form_lo": 0.204, "form_hi": 3.503, "form_trailing": 0.0},
  {"ticker": "ASIF", "period_end": "2026-06-30", "na_now": 0.32, "na_mean8": 0.12, "wl_high_pct": 1.136, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 0.364, "lo_q1": 0.0, "hi_q1": 1.32, "q2_label": "2026-Q4", "na_q2": 0.591, "lo_q2": 0.0, "hi_q2": 1.868, "p_rise": 0.2, "xh_pp": 0.413, "b90_pp": 5.804, "form_4q": 1.031, "form_lo": 0.101, "form_hi": 3.4, "form_trailing": 0.251},
  {"ticker": "OBDC", "period_end": "2026-06-30", "na_now": 2.84, "na_mean8": 2.055, "wl_high_pct": 0.389, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 2.604, "lo_q1": 1.905, "hi_q1": 3.56, "q2_label": "2026-Q4", "na_q2": 2.682, "lo_q2": 1.811, "hi_q2": 3.959, "p_rise": 0.167, "xh_pp": 0.223, "b90_pp": 5.666, "form_4q": 1.002, "form_lo": 0.072, "form_hi": 3.371, "form_trailing": 0.0},
  {"ticker": "OCIC", "period_end": "2026-06-30", "na_now": 0.35, "na_mean8": 0.367, "wl_high_pct": 0.503, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 0.406, "lo_q1": 0.0, "hi_q1": 1.363, "q2_label": "2026-Q4", "na_q2": 0.507, "lo_q2": 0.0, "hi_q2": 1.784, "p_rise": 0.176, "xh_pp": 0.317, "b90_pp": 5.455, "form_4q": 0.985, "form_lo": 0.055, "form_hi": 3.354, "form_trailing": 0.0},
  {"ticker": "TSLX", "period_end": "2026-06-30", "na_now": 1.92, "na_mean8": 2.636, "wl_high_pct": 0.017, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 2.172, "lo_q1": 1.474, "hi_q1": 3.128, "q2_label": "2026-Q4", "na_q2": 2.176, "lo_q2": 1.305, "hi_q2": 3.453, "p_rise": 0.147, "xh_pp": 0.017, "b90_pp": 3.996, "form_4q": 0.924, "form_lo": 0.0, "form_hi": 3.293, "form_trailing": 0.158}
];

// Predicted loss content by quartile, per quarter, across the whole BDC
// universe. Quartiles are cut WITHIN each quarter (a pooled cut would just
// re-rank the universe by calendar time), equal-weighted across the BDCs in
// each bucket. `actual` is the realised 4-quarter formation for the same
// BDCs and is only populated where four quarters have since elapsed.
export interface NaQuartilePoint {
  period_end: string; q: number; pred: number; actual: number | null; n: number;
}

export const naQuartileSeries: NaQuartilePoint[] = [
  {"period_end": "2022-03-31", "q": 1, "pred": 0.167, "actual": 0.0, "n": 4},
  {"period_end": "2022-03-31", "q": 2, "pred": 0.201, "actual": 0.297, "n": 4},
  {"period_end": "2022-03-31", "q": 3, "pred": 0.244, "actual": 1.567, "n": 3},
  {"period_end": "2022-03-31", "q": 4, "pred": 0.633, "actual": 1.277, "n": 4},
  {"period_end": "2022-06-30", "q": 1, "pred": 0.263, "actual": 0.0, "n": 4},
  {"period_end": "2022-06-30", "q": 2, "pred": 0.297, "actual": 0.046, "n": 4},
  {"period_end": "2022-06-30", "q": 3, "pred": 0.36, "actual": 1.05, "n": 4},
  {"period_end": "2022-06-30", "q": 4, "pred": 0.757, "actual": 2.695, "n": 4},
  {"period_end": "2022-09-30", "q": 1, "pred": 0.274, "actual": 0.552, "n": 5},
  {"period_end": "2022-09-30", "q": 2, "pred": 0.305, "actual": 0.0, "n": 4},
  {"period_end": "2022-09-30", "q": 3, "pred": 0.4, "actual": 0.574, "n": 4},
  {"period_end": "2022-09-30", "q": 4, "pred": 1.088, "actual": 2.605, "n": 4},
  {"period_end": "2022-12-31", "q": 1, "pred": 0.295, "actual": 0.0, "n": 5},
  {"period_end": "2022-12-31", "q": 2, "pred": 0.344, "actual": 0.054, "n": 4},
  {"period_end": "2022-12-31", "q": 3, "pred": 0.561, "actual": 2.678, "n": 4},
  {"period_end": "2022-12-31", "q": 4, "pred": 1.283, "actual": 3.425, "n": 4},
  {"period_end": "2023-03-31", "q": 1, "pred": 0.355, "actual": 0.067, "n": 5},
  {"period_end": "2023-03-31", "q": 2, "pred": 0.427, "actual": 0.174, "n": 4},
  {"period_end": "2023-03-31", "q": 3, "pred": 0.591, "actual": 2.917, "n": 4},
  {"period_end": "2023-03-31", "q": 4, "pred": 1.532, "actual": 2.967, "n": 5},
  {"period_end": "2023-06-30", "q": 1, "pred": 0.415, "actual": 0.112, "n": 5},
  {"period_end": "2023-06-30", "q": 2, "pred": 0.504, "actual": 0.0, "n": 4},
  {"period_end": "2023-06-30", "q": 3, "pred": 0.66, "actual": 4.906, "n": 4},
  {"period_end": "2023-06-30", "q": 4, "pred": 2.074, "actual": 3.392, "n": 5},
  {"period_end": "2023-09-30", "q": 1, "pred": 0.496, "actual": 0.488, "n": 5},
  {"period_end": "2023-09-30", "q": 2, "pred": 0.689, "actual": 0.0, "n": 4},
  {"period_end": "2023-09-30", "q": 3, "pred": 1.089, "actual": 3.286, "n": 4},
  {"period_end": "2023-09-30", "q": 4, "pred": 2.311, "actual": 3.392, "n": 5},
  {"period_end": "2023-12-31", "q": 1, "pred": 0.584, "actual": 0.662, "n": 5},
  {"period_end": "2023-12-31", "q": 2, "pred": 0.729, "actual": 1.946, "n": 4},
  {"period_end": "2023-12-31", "q": 3, "pred": 1.262, "actual": 1.211, "n": 4},
  {"period_end": "2023-12-31", "q": 4, "pred": 3.351, "actual": 2.123, "n": 5},
  {"period_end": "2024-03-31", "q": 1, "pred": 0.699, "actual": 0.592, "n": 5},
  {"period_end": "2024-03-31", "q": 2, "pred": 0.909, "actual": 0.0, "n": 4},
  {"period_end": "2024-03-31", "q": 3, "pred": 1.328, "actual": 2.325, "n": 4},
  {"period_end": "2024-03-31", "q": 4, "pred": 3.28, "actual": 3.725, "n": 5},
  {"period_end": "2024-06-30", "q": 1, "pred": 0.735, "actual": 0.371, "n": 5},
  {"period_end": "2024-06-30", "q": 2, "pred": 0.928, "actual": 0.285, "n": 4},
  {"period_end": "2024-06-30", "q": 3, "pred": 1.87, "actual": 1.058, "n": 4},
  {"period_end": "2024-06-30", "q": 4, "pred": 3.799, "actual": 4.313, "n": 5},
  {"period_end": "2024-09-30", "q": 1, "pred": 0.743, "actual": 0.073, "n": 5},
  {"period_end": "2024-09-30", "q": 2, "pred": 0.93, "actual": 0.219, "n": 4},
  {"period_end": "2024-09-30", "q": 3, "pred": 1.536, "actual": 1.251, "n": 4},
  {"period_end": "2024-09-30", "q": 4, "pred": 3.562, "actual": 4.292, "n": 5},
  {"period_end": "2024-12-31", "q": 1, "pred": 0.688, "actual": 0.0, "n": 5},
  {"period_end": "2024-12-31", "q": 2, "pred": 0.985, "actual": 0.357, "n": 5},
  {"period_end": "2024-12-31", "q": 3, "pred": 1.599, "actual": 1.602, "n": 4},
  {"period_end": "2024-12-31", "q": 4, "pred": 3.014, "actual": 4.91, "n": 5},
  {"period_end": "2025-03-31", "q": 1, "pred": 0.64, "actual": 0.03, "n": 5},
  {"period_end": "2025-03-31", "q": 2, "pred": 0.926, "actual": 1.058, "n": 4},
  {"period_end": "2025-03-31", "q": 3, "pred": 1.565, "actual": 1.962, "n": 4},
  {"period_end": "2025-03-31", "q": 4, "pred": 3.674, "actual": 3.769, "n": 5},
  {"period_end": "2025-06-30", "q": 1, "pred": 0.756, "actual": 0.082, "n": 5},
  {"period_end": "2025-06-30", "q": 2, "pred": 1.05, "actual": 0.418, "n": 5},
  {"period_end": "2025-06-30", "q": 3, "pred": 1.631, "actual": 2.819, "n": 4},
  {"period_end": "2025-06-30", "q": 4, "pred": 3.447, "actual": 2.511, "n": 5},
  {"period_end": "2025-09-30", "q": 1, "pred": 0.749, "actual": null, "n": 5},
  {"period_end": "2025-09-30", "q": 2, "pred": 1.155, "actual": null, "n": 5},
  {"period_end": "2025-09-30", "q": 3, "pred": 1.727, "actual": null, "n": 4},
  {"period_end": "2025-09-30", "q": 4, "pred": 3.239, "actual": null, "n": 5},
  {"period_end": "2025-12-31", "q": 1, "pred": 0.763, "actual": null, "n": 5},
  {"period_end": "2025-12-31", "q": 2, "pred": 1.18, "actual": null, "n": 5},
  {"period_end": "2025-12-31", "q": 3, "pred": 1.759, "actual": null, "n": 4},
  {"period_end": "2025-12-31", "q": 4, "pred": 3.683, "actual": null, "n": 5},
  {"period_end": "2026-03-31", "q": 1, "pred": 0.922, "actual": null, "n": 5},
  {"period_end": "2026-03-31", "q": 2, "pred": 1.286, "actual": null, "n": 5},
  {"period_end": "2026-03-31", "q": 3, "pred": 2.137, "actual": null, "n": 4},
  {"period_end": "2026-03-31", "q": 4, "pred": 3.612, "actual": null, "n": 5},
  {"period_end": "2026-06-30", "q": 1, "pred": 1.015, "actual": null, "n": 5},
  {"period_end": "2026-06-30", "q": 2, "pred": 1.349, "actual": null, "n": 5},
  {"period_end": "2026-06-30", "q": 3, "pred": 2.03, "actual": null, "n": 4},
  {"period_end": "2026-06-30", "q": 4, "pred": 3.369, "actual": null, "n": 5}
];

export const naFcMeta = {
  "generated": "2026-08-25",
  "shrink_k": 0.35,
  "high_b": {
    "1": 0.1,
    "2": 0.3
  },
  "mean_window_q": 8,
  "backtest_from": "2021-03-31",
  "horizons": {
    "1": {
      "n": 326,
      "mean_abs": 0.5613,
      "median_abs": 0.2392,
      "p90_abs": 1.3718,
      "naive_mean_abs": 0.5955,
      "naive_median_abs": 0.18,
      "naive_p90_abs": 1.6,
      "q10": -0.9561,
      "q90": 0.6987
    },
    "2": {
      "n": 307,
      "mean_abs": 0.6934,
      "median_abs": 0.3674,
      "p90_abs": 1.5358,
      "naive_mean_abs": 0.75,
      "naive_median_abs": 0.33,
      "naive_p90_abs": 1.858,
      "q10": -1.2773,
      "q90": 0.8713
    }
  },
  "direction": {
    "n": 359,
    "base_rate": 0.1783,
    "auc": 0.5616,
    "top_decile_hit": 0.3714,
    "top_decile_lift": 2.0835,
    "threshold_pp": 0.5
  },
  "formation": {
    "n": 231,
    "horizon_q": 4,
    "mean_abs": 1.1683,
    "corr": 0.4681,
    "bias": -0.2257,
    "actual_mean": 1.4816,
    "band_lo": 0.93,
    "band_hi": -2.3692,
    "quartiles": [
      {
        "q": 1,
        "pred": 0.317666565091395,
        "actual": 0.28692553151144135,
        "n": 58
      },
      {
        "q": 2,
        "pred": 0.6795962019657228,
        "actual": 1.059924550226729,
        "n": 58
      },
      {
        "q": 3,
        "pred": 1.1073798172787461,
        "actual": 1.3299532161781462,
        "n": 57
      },
      {
        "q": 4,
        "pred": 2.916542315809655,
        "actual": 3.2470406214145964,
        "n": 58
      }
    ]
  }
} as const;
