// AUTO-GENERATED by scripts/83_forecast_non_accrual.py — do not edit by hand.
// Forward non-accrual rate per BDC, % of amortized cost, 1 and 2 quarters out.
//
// forecast = na - k*(na - own 8-quarter mean) + b * watchlist-High %
//
// Non-accrual rates are highly persistent (corr 0.77 q/q), so this is
// persistence adjusted for the two measurable effects: mean reversion as
// workouts resolve, and inflow from the watchlist High tier. Coefficients were
// picked by walk-forward grid search; naFcMeta carries the measured accuracy
// against simply carrying the current rate forward, INCLUDING where naive still
// wins. lo/hi are the empirical 10th-90th percentile of walk-forward signed
// errors — calibrated on realised misses, not an assumed distribution.
/* eslint-disable */

export interface NaForecastRow {
  ticker: string; period_end: string;
  na_now: number; na_mean8: number; wl_high_pct: number; has_watchlist: boolean;
  q1_label: string; na_q1: number; lo_q1: number; hi_q1: number;
  q2_label: string; na_q2: number; lo_q2: number; hi_q2: number;
  // Direction, which ranks better than the level does. p_rise is
  // P(rate rises >= 0.5pp next quarter); xh_pp is the share of cost in
  // borrowers ALREADY non-accrual at another BDC — the strongest single
  // input (17x lift at the name level).
  p_rise: number | null; xh_pp: number | null; b90_pp: number | null;
  // HEADLINE: expected NEW non-accrual formation over the next four
  // quarters, % of cost, with an empirical 80% band. Ranks far better
  // than any next-quarter number — see naFcMeta.formation.quartiles.
  form_4q: number | null; form_lo: number | null; form_hi: number | null;
  form_trailing: number | null;
}

export const naForecast: NaForecastRow[] = [
  {"ticker": "NMFC", "period_end": "2026-06-30", "na_now": 2.79, "na_mean8": 2.153, "wl_high_pct": 1.425, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 2.709, "lo_q1": 2.008, "hi_q1": 3.688, "q2_label": "2026-Q4", "na_q2": 2.994, "lo_q2": 2.125, "hi_q2": 4.381, "p_rise": 0.771, "xh_pp": 3.218, "b90_pp": 19.972, "form_4q": 8.199, "form_lo": 6.811, "form_hi": 10.424, "form_trailing": 3.753},
  {"ticker": "FSK", "period_end": "2026-06-30", "na_now": 6.55, "na_mean8": 5.226, "wl_high_pct": 0.0, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 6.087, "lo_q1": 5.385, "hi_q1": 7.065, "q2_label": "2026-Q4", "na_q2": 6.087, "lo_q2": 5.217, "hi_q2": 7.474, "p_rise": 0.353, "xh_pp": 0.0, "b90_pp": 31.69, "form_4q": 6.078, "form_lo": 4.69, "form_hi": 8.303, "form_trailing": 6.115},
  {"ticker": "ARCC", "period_end": "2026-06-30", "na_now": 2.38, "na_mean8": 1.806, "wl_high_pct": 0.93, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 2.272, "lo_q1": 1.57, "hi_q1": 3.251, "q2_label": "2026-Q4", "na_q2": 2.458, "lo_q2": 1.589, "hi_q2": 3.845, "p_rise": 0.536, "xh_pp": 1.779, "b90_pp": 11.222, "form_4q": 4.987, "form_lo": 3.599, "form_hi": 7.212, "form_trailing": 2.759},
  {"ticker": "CGBD", "period_end": "2026-06-30", "na_now": 1.19, "na_mean8": 1.619, "wl_high_pct": 0.731, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 1.413, "lo_q1": 0.711, "hi_q1": 2.392, "q2_label": "2026-Q4", "na_q2": 1.56, "lo_q2": 0.69, "hi_q2": 2.947, "p_rise": 0.501, "xh_pp": 1.736, "b90_pp": 6.344, "form_4q": 4.971, "form_lo": 3.583, "form_hi": 7.196, "form_trailing": 1.804},
  {"ticker": "GBDC", "period_end": "2026-06-30", "na_now": 2.94, "na_mean8": 1.531, "wl_high_pct": 0.213, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 2.468, "lo_q1": 1.766, "hi_q1": 3.447, "q2_label": "2026-Q4", "na_q2": 2.511, "lo_q2": 1.641, "hi_q2": 3.898, "p_rise": 0.212, "xh_pp": 0.375, "b90_pp": 3.927, "form_4q": 4.766, "form_lo": 3.378, "form_hi": 6.991, "form_trailing": 5.033},
  {"ticker": "BXSL", "period_end": "2026-06-30", "na_now": 3.51, "na_mean8": 1.232, "wl_high_pct": 0.462, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 2.759, "lo_q1": 2.057, "hi_q1": 3.738, "q2_label": "2026-Q4", "na_q2": 2.851, "lo_q2": 1.982, "hi_q2": 4.239, "p_rise": 0.307, "xh_pp": 0.655, "b90_pp": 7.431, "form_4q": 4.744, "form_lo": 3.356, "form_hi": 6.969, "form_trailing": 4.77},
  {"ticker": "BCRED", "period_end": "2026-06-30", "na_now": 2.08, "na_mean8": 0.86, "wl_high_pct": 1.216, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 1.775, "lo_q1": 1.073, "hi_q1": 2.753, "q2_label": "2026-Q4", "na_q2": 2.018, "lo_q2": 1.148, "hi_q2": 3.405, "p_rise": 0.28, "xh_pp": 0.405, "b90_pp": 10.098, "form_4q": 4.218, "form_lo": 2.83, "form_hi": 6.443, "form_trailing": 2.971},
  {"ticker": "CCAP", "period_end": "2026-06-30", "na_now": 4.47, "na_mean8": 3.294, "wl_high_pct": 0.598, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 4.118, "lo_q1": 3.416, "hi_q1": 5.097, "q2_label": "2026-Q4", "na_q2": 4.238, "lo_q2": 3.368, "hi_q2": 5.625, "p_rise": 0.223, "xh_pp": 0.234, "b90_pp": 10.974, "form_4q": 3.743, "form_lo": 2.355, "form_hi": 5.968, "form_trailing": 4.766},
  {"ticker": "BBDC", "period_end": "2026-06-30", "na_now": 1.53, "na_mean8": 1.662, "wl_high_pct": 0.349, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 1.611, "lo_q1": 0.909, "hi_q1": 2.59, "q2_label": "2026-Q4", "na_q2": 1.681, "lo_q2": 0.812, "hi_q2": 3.068, "p_rise": 0.223, "xh_pp": 0.216, "b90_pp": 8.892, "form_4q": 3.505, "form_lo": 2.117, "form_hi": 5.73, "form_trailing": 1.344},
  {"ticker": "MAIN", "period_end": "2026-06-30", "na_now": 3.99, "na_mean8": 3.975, "wl_high_pct": 0.711, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 4.056, "lo_q1": 3.354, "hi_q1": 5.035, "q2_label": "2026-Q4", "na_q2": 4.198, "lo_q2": 3.328, "hi_q2": 5.585, "p_rise": 0.26, "xh_pp": 0.387, "b90_pp": 10.176, "form_4q": 3.366, "form_lo": 1.978, "form_hi": 5.59, "form_trailing": 1.752},
  {"ticker": "OCSL", "period_end": "2026-06-30", "na_now": 3.82, "na_mean8": 5.404, "wl_high_pct": 0.642, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 4.439, "lo_q1": 3.737, "hi_q1": 5.417, "q2_label": "2026-Q4", "na_q2": 4.567, "lo_q2": 3.697, "hi_q2": 5.954, "p_rise": 0.257, "xh_pp": 0.589, "b90_pp": 15.741, "form_4q": 3.261, "form_lo": 1.873, "form_hi": 5.485, "form_trailing": 1.533},
  {"ticker": "OTF", "period_end": "2026-06-30", "na_now": 0.58, "na_mean8": 0.28, "wl_high_pct": 0.797, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 0.555, "lo_q1": 0.0, "hi_q1": 1.533, "q2_label": "2026-Q4", "na_q2": 0.714, "lo_q2": 0.0, "hi_q2": 2.101, "p_rise": 0.335, "xh_pp": 0.978, "b90_pp": 9.454, "form_4q": 3.144, "form_lo": 1.756, "form_hi": 5.369, "form_trailing": 0.505},
  {"ticker": "OBDC", "period_end": "2026-06-30", "na_now": 2.84, "na_mean8": 2.055, "wl_high_pct": 0.232, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 2.588, "lo_q1": 1.887, "hi_q1": 3.567, "q2_label": "2026-Q4", "na_q2": 2.635, "lo_q2": 1.765, "hi_q2": 4.022, "p_rise": 0.163, "xh_pp": 0.065, "b90_pp": 5.478, "form_4q": 2.736, "form_lo": 1.348, "form_hi": 4.961, "form_trailing": 2.795},
  {"ticker": "OCIC", "period_end": "2026-06-30", "na_now": 0.35, "na_mean8": 0.367, "wl_high_pct": 0.326, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 0.389, "lo_q1": 0.0, "hi_q1": 1.368, "q2_label": "2026-Q4", "na_q2": 0.454, "lo_q2": 0.0, "hi_q2": 1.841, "p_rise": 0.208, "xh_pp": 0.314, "b90_pp": 5.337, "form_4q": 2.395, "form_lo": 1.007, "form_hi": 4.619, "form_trailing": 1.127},
  {"ticker": "MFIC", "period_end": "2026-06-30", "na_now": 0.0, "na_mean8": 0.0, "wl_high_pct": 1.182, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 0.118, "lo_q1": 0.0, "hi_q1": 1.097, "q2_label": "2026-Q4", "na_q2": 0.355, "lo_q2": 0.0, "hi_q2": 1.742, "p_rise": 0.275, "xh_pp": 0.373, "b90_pp": 23.352, "form_4q": 2.084, "form_lo": 0.696, "form_hi": 4.309, "form_trailing": null},
  {"ticker": "TSLX", "period_end": "2026-06-30", "na_now": 1.92, "na_mean8": 2.636, "wl_high_pct": 0.017, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 2.172, "lo_q1": 1.471, "hi_q1": 3.151, "q2_label": "2026-Q4", "na_q2": 2.176, "lo_q2": 1.306, "hi_q2": 3.563, "p_rise": 0.167, "xh_pp": 0.017, "b90_pp": 7.922, "form_4q": 1.983, "form_lo": 0.595, "form_hi": 4.208, "form_trailing": 1.205},
  {"ticker": "ADS", "period_end": "2026-06-30", "na_now": 0.79, "na_mean8": 0.659, "wl_high_pct": 0.812, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 0.825, "lo_q1": 0.123, "hi_q1": 1.804, "q2_label": "2026-Q4", "na_q2": 0.988, "lo_q2": 0.118, "hi_q2": 2.375, "p_rise": 0.316, "xh_pp": 0.969, "b90_pp": 2.735, "form_4q": 1.831, "form_lo": 0.443, "form_hi": 4.056, "form_trailing": 0.765},
  {"ticker": "HTGC", "period_end": "2026-06-30", "na_now": 0.35, "na_mean8": 1.034, "wl_high_pct": 0.0, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 0.589, "lo_q1": 0.0, "hi_q1": 1.568, "q2_label": "2026-Q4", "na_q2": 0.589, "lo_q2": 0.0, "hi_q2": 1.977, "p_rise": 0.137, "xh_pp": 0.0, "b90_pp": 5.446, "form_4q": 1.67, "form_lo": 0.282, "form_hi": 3.895, "form_trailing": 1.324},
  {"ticker": "ASIF", "period_end": "2026-06-30", "na_now": 0.32, "na_mean8": 0.12, "wl_high_pct": 0.411, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 0.291, "lo_q1": 0.0, "hi_q1": 1.27, "q2_label": "2026-Q4", "na_q2": 0.373, "lo_q2": 0.0, "hi_q2": 1.761, "p_rise": 0.24, "xh_pp": 0.413, "b90_pp": 5.788, "form_4q": 1.51, "form_lo": 0.122, "form_hi": 3.735, "form_trailing": 0.427}
];

// Predicted loss content by quartile, per quarter, across the whole BDC
// universe. Quartiles are cut WITHIN each quarter (a pooled cut would just
// re-rank the universe by calendar time), equal-weighted across the BDCs in
// each bucket. `actual` is the realised 4-quarter formation for the same
// BDCs and is only populated where four quarters have since elapsed.
export interface NaQuartilePoint {
  period_end: string; q: number; pred: number; actual: number | null; n: number;
}

export const naQuartileSeries: NaQuartilePoint[] = [
  {"period_end": "2022-06-30", "q": 1, "pred": 0.465, "actual": 0.084, "n": 4},
  {"period_end": "2022-06-30", "q": 2, "pred": 0.936, "actual": 2.035, "n": 4},
  {"period_end": "2022-06-30", "q": 3, "pred": 1.234, "actual": 1.585, "n": 3},
  {"period_end": "2022-06-30", "q": 4, "pred": 1.608, "actual": 2.486, "n": 4},
  {"period_end": "2022-09-30", "q": 1, "pred": 0.347, "actual": 0.07, "n": 4},
  {"period_end": "2022-09-30", "q": 2, "pred": 0.954, "actual": 0.999, "n": 4},
  {"period_end": "2022-09-30", "q": 3, "pred": 1.513, "actual": 1.631, "n": 4},
  {"period_end": "2022-09-30", "q": 4, "pred": 2.039, "actual": 2.259, "n": 4},
  {"period_end": "2022-12-31", "q": 1, "pred": 0.235, "actual": 0.157, "n": 4},
  {"period_end": "2022-12-31", "q": 2, "pred": 0.993, "actual": 0.919, "n": 4},
  {"period_end": "2022-12-31", "q": 3, "pred": 1.411, "actual": 2.793, "n": 4},
  {"period_end": "2022-12-31", "q": 4, "pred": 2.467, "actual": 2.741, "n": 4},
  {"period_end": "2023-03-31", "q": 1, "pred": 0.536, "actual": 0.353, "n": 5},
  {"period_end": "2023-03-31", "q": 2, "pred": 1.046, "actual": 1.291, "n": 4},
  {"period_end": "2023-03-31", "q": 3, "pred": 1.839, "actual": 2.805, "n": 4},
  {"period_end": "2023-03-31", "q": 4, "pred": 2.958, "actual": 3.713, "n": 4},
  {"period_end": "2023-06-30", "q": 1, "pred": 0.387, "actual": 0.358, "n": 5},
  {"period_end": "2023-06-30", "q": 2, "pred": 1.243, "actual": 2.577, "n": 4},
  {"period_end": "2023-06-30", "q": 3, "pred": 2.035, "actual": 4.027, "n": 4},
  {"period_end": "2023-06-30", "q": 4, "pred": 3.164, "actual": 4.211, "n": 4},
  {"period_end": "2023-09-30", "q": 1, "pred": 0.4, "actual": 1.227, "n": 5},
  {"period_end": "2023-09-30", "q": 2, "pred": 1.864, "actual": 3.736, "n": 4},
  {"period_end": "2023-09-30", "q": 3, "pred": 2.573, "actual": 1.852, "n": 4},
  {"period_end": "2023-09-30", "q": 4, "pred": 3.445, "actual": 3.662, "n": 4},
  {"period_end": "2023-12-31", "q": 1, "pred": 0.298, "actual": 0.853, "n": 5},
  {"period_end": "2023-12-31", "q": 2, "pred": 1.424, "actual": 3.754, "n": 4},
  {"period_end": "2023-12-31", "q": 3, "pred": 2.511, "actual": 1.636, "n": 4},
  {"period_end": "2023-12-31", "q": 4, "pred": 3.744, "actual": 2.649, "n": 4},
  {"period_end": "2024-03-31", "q": 1, "pred": 0.809, "actual": 0.922, "n": 5},
  {"period_end": "2024-03-31", "q": 2, "pred": 2.191, "actual": 2.253, "n": 4},
  {"period_end": "2024-03-31", "q": 3, "pred": 3.12, "actual": 4.174, "n": 4},
  {"period_end": "2024-03-31", "q": 4, "pred": 3.905, "actual": 3.446, "n": 4},
  {"period_end": "2024-06-30", "q": 1, "pred": 0.784, "actual": 0.895, "n": 5},
  {"period_end": "2024-06-30", "q": 2, "pred": 1.989, "actual": 2.091, "n": 4},
  {"period_end": "2024-06-30", "q": 3, "pred": 3.058, "actual": 1.753, "n": 4},
  {"period_end": "2024-06-30", "q": 4, "pred": 4.051, "actual": 4.351, "n": 4},
  {"period_end": "2024-09-30", "q": 1, "pred": 0.974, "actual": 0.482, "n": 5},
  {"period_end": "2024-09-30", "q": 2, "pred": 1.792, "actual": 2.37, "n": 4},
  {"period_end": "2024-09-30", "q": 3, "pred": 2.585, "actual": 1.124, "n": 4},
  {"period_end": "2024-09-30", "q": 4, "pred": 3.734, "actual": 4.789, "n": 4},
  {"period_end": "2024-12-31", "q": 1, "pred": 0.712, "actual": 0.929, "n": 5},
  {"period_end": "2024-12-31", "q": 2, "pred": 1.573, "actual": 1.609, "n": 4},
  {"period_end": "2024-12-31", "q": 3, "pred": 2.334, "actual": 3.229, "n": 4},
  {"period_end": "2024-12-31", "q": 4, "pred": 3.806, "actual": 4.361, "n": 5},
  {"period_end": "2025-03-31", "q": 1, "pred": 1.195, "actual": 1.585, "n": 5},
  {"period_end": "2025-03-31", "q": 2, "pred": 2.073, "actual": 1.954, "n": 4},
  {"period_end": "2025-03-31", "q": 3, "pred": 3.08, "actual": 5.27, "n": 4},
  {"period_end": "2025-03-31", "q": 4, "pred": 3.591, "actual": 2.51, "n": 4},
  {"period_end": "2025-06-30", "q": 1, "pred": 0.985, "actual": 0.969, "n": 5},
  {"period_end": "2025-06-30", "q": 2, "pred": 2.017, "actual": 1.904, "n": 4},
  {"period_end": "2025-06-30", "q": 3, "pred": 3.148, "actual": 3.577, "n": 4},
  {"period_end": "2025-06-30", "q": 4, "pred": 3.773, "actual": 3.595, "n": 5},
  {"period_end": "2025-09-30", "q": 1, "pred": 1.008, "actual": null, "n": 5},
  {"period_end": "2025-09-30", "q": 2, "pred": 2.332, "actual": null, "n": 4},
  {"period_end": "2025-09-30", "q": 3, "pred": 3.254, "actual": null, "n": 4},
  {"period_end": "2025-09-30", "q": 4, "pred": 4.123, "actual": null, "n": 5},
  {"period_end": "2025-12-31", "q": 1, "pred": 1.06, "actual": null, "n": 5},
  {"period_end": "2025-12-31", "q": 2, "pred": 2.317, "actual": null, "n": 4},
  {"period_end": "2025-12-31", "q": 3, "pred": 3.255, "actual": null, "n": 4},
  {"period_end": "2025-12-31", "q": 4, "pred": 4.438, "actual": null, "n": 5},
  {"period_end": "2026-03-31", "q": 1, "pred": 1.762, "actual": null, "n": 5},
  {"period_end": "2026-03-31", "q": 2, "pred": 2.772, "actual": null, "n": 4},
  {"period_end": "2026-03-31", "q": 3, "pred": 3.805, "actual": null, "n": 4},
  {"period_end": "2026-03-31", "q": 4, "pred": 5.02, "actual": null, "n": 5},
  {"period_end": "2026-06-30", "q": 1, "pred": 1.878, "actual": null, "n": 5},
  {"period_end": "2026-06-30", "q": 2, "pred": 3.127, "actual": null, "n": 4},
  {"period_end": "2026-06-30", "q": 3, "pred": 4.052, "actual": null, "n": 4},
  {"period_end": "2026-06-30", "q": 4, "pred": 5.8, "actual": null, "n": 5}
];

export const naFcMeta = {
  "generated": "2026-09-18",
  "shrink_k": 0.35,
  "high_b": {
    "1": 0.1,
    "2": 0.3
  },
  "mean_window_q": 8,
  "backtest_from": "2021-03-31",
  "horizons": {
    "1": {
      "n": 323,
      "mean_abs": 0.5664,
      "median_abs": 0.2413,
      "p90_abs": 1.3419,
      "naive_mean_abs": 0.5984,
      "naive_median_abs": 0.18,
      "naive_p90_abs": 1.588,
      "q10": -0.9788,
      "q90": 0.7018
    },
    "2": {
      "n": 304,
      "mean_abs": 0.7121,
      "median_abs": 0.3781,
      "p90_abs": 1.6148,
      "naive_mean_abs": 0.7554,
      "naive_median_abs": 0.355,
      "naive_p90_abs": 1.835,
      "q10": -1.3872,
      "q90": 0.8695
    }
  },
  "direction": {
    "n": 359,
    "base_rate": 0.1783,
    "auc": 0.5863,
    "top_decile_hit": 0.3143,
    "top_decile_lift": 1.7629,
    "threshold_pp": 0.5
  },
  "formation": {
    "n": 204,
    "horizon_q": 4,
    "mean_abs": 1.2058,
    "corr": 0.518,
    "bias": -0.2549,
    "actual_mean": 2.2224,
    "band_lo": 1.3881,
    "band_hi": -2.2248,
    "quartiles": [
      {
        "q": 1,
        "pred": 0.5391599229876257,
        "actual": 0.7354439506497595,
        "n": 51
      },
      {
        "q": 2,
        "pred": 1.4272776879732738,
        "actual": 2.1327154481567847,
        "n": 51
      },
      {
        "q": 3,
        "pred": 2.3105658914000573,
        "actual": 2.2376051927686604,
        "n": 51
      },
      {
        "q": 4,
        "pred": 3.5929434735597607,
        "actual": 3.783938909624884,
        "n": 51
      }
    ]
  }
} as const;
