// AUTO-GENERATED by scripts/83_forecast_non_accrual.py — do not edit by hand.
// Forward non-accrual rate per BDC, % of amortized cost, 1 and 2 quarters out.
//
// forecast = na - k*(na - own 8-quarter mean) + b * watchlist-High %
//
// Non-accrual rates are highly persistent (corr 0.77 q/q), so this is
// persistence adjusted for the two measurable effects: mean reversion as
// workouts resolve, and inflow from the watchlist High tier. Coefficients were
// picked by walk-forward grid search; naFcMeta carries the measured accuracy
// against simply carrying the current rate forward, INCLUDING where naive still
// wins. lo/hi are the empirical 10th-90th percentile of walk-forward signed
// errors — calibrated on realised misses, not an assumed distribution.
/* eslint-disable */

export interface NaForecastRow {
  ticker: string; period_end: string;
  na_now: number; na_mean8: number; wl_high_pct: number; has_watchlist: boolean;
  q1_label: string; na_q1: number; lo_q1: number; hi_q1: number;
  q2_label: string; na_q2: number; lo_q2: number; hi_q2: number;
  // Direction, which ranks better than the level does. p_rise is
  // P(rate rises >= 0.5pp next quarter); xh_pp is the share of cost in
  // borrowers ALREADY non-accrual at another BDC — the strongest single
  // input (17x lift at the name level).
  p_rise: number | null; xh_pp: number | null; b90_pp: number | null;
  // HEADLINE: expected NEW non-accrual formation over the next four
  // quarters, % of cost, with an empirical 80% band. Ranks far better
  // than any next-quarter number — see naFcMeta.formation.quartiles.
  form_4q: number | null; form_lo: number | null; form_hi: number | null;
  form_trailing: number | null;
}

export const naForecast: NaForecastRow[] = [
  {"ticker": "NMFC", "period_end": "2026-06-30", "na_now": 2.79, "na_mean8": 2.153, "wl_high_pct": 1.425, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 2.709, "lo_q1": 2.008, "hi_q1": 3.688, "q2_label": "2026-Q4", "na_q2": 2.994, "lo_q2": 2.117, "hi_q2": 4.381, "p_rise": 0.767, "xh_pp": 3.218, "b90_pp": 19.972, "form_4q": 8.159, "form_lo": 6.789, "form_hi": 10.446, "form_trailing": 3.753},
  {"ticker": "FSK", "period_end": "2026-06-30", "na_now": 6.55, "na_mean8": 5.226, "wl_high_pct": 0.0, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 6.087, "lo_q1": 5.385, "hi_q1": 7.065, "q2_label": "2026-Q4", "na_q2": 6.087, "lo_q2": 5.21, "hi_q2": 7.474, "p_rise": 0.353, "xh_pp": 0.0, "b90_pp": 31.69, "form_4q": 6.19, "form_lo": 4.82, "form_hi": 8.477, "form_trailing": 6.115},
  {"ticker": "ARCC", "period_end": "2026-06-30", "na_now": 2.38, "na_mean8": 1.806, "wl_high_pct": 0.93, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 2.272, "lo_q1": 1.57, "hi_q1": 3.251, "q2_label": "2026-Q4", "na_q2": 2.458, "lo_q2": 1.581, "hi_q2": 3.845, "p_rise": 0.534, "xh_pp": 1.779, "b90_pp": 11.222, "form_4q": 5.105, "form_lo": 3.735, "form_hi": 7.392, "form_trailing": 2.759},
  {"ticker": "CGBD", "period_end": "2026-06-30", "na_now": 1.22, "na_mean8": 1.647, "wl_high_pct": 0.802, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 1.45, "lo_q1": 0.748, "hi_q1": 2.429, "q2_label": "2026-Q4", "na_q2": 1.61, "lo_q2": 0.733, "hi_q2": 2.997, "p_rise": 0.483, "xh_pp": 1.694, "b90_pp": 6.431, "form_4q": 5.058, "form_lo": 3.687, "form_hi": 7.344, "form_trailing": 1.886},
  {"ticker": "BXSL", "period_end": "2026-06-30", "na_now": 3.51, "na_mean8": 1.232, "wl_high_pct": 0.462, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 2.759, "lo_q1": 2.057, "hi_q1": 3.738, "q2_label": "2026-Q4", "na_q2": 2.851, "lo_q2": 1.975, "hi_q2": 4.239, "p_rise": 0.306, "xh_pp": 0.655, "b90_pp": 7.431, "form_4q": 4.583, "form_lo": 3.213, "form_hi": 6.869, "form_trailing": 4.77},
  {"ticker": "GBDC", "period_end": "2026-06-30", "na_now": 2.94, "na_mean8": 1.531, "wl_high_pct": 0.213, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 2.468, "lo_q1": 1.766, "hi_q1": 3.447, "q2_label": "2026-Q4", "na_q2": 2.511, "lo_q2": 1.634, "hi_q2": 3.898, "p_rise": 0.212, "xh_pp": 0.375, "b90_pp": 3.927, "form_4q": 4.383, "form_lo": 3.013, "form_hi": 6.67, "form_trailing": 5.033},
  {"ticker": "BCRED", "period_end": "2026-06-30", "na_now": 2.08, "na_mean8": 0.86, "wl_high_pct": 1.216, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 1.775, "lo_q1": 1.073, "hi_q1": 2.753, "q2_label": "2026-Q4", "na_q2": 2.018, "lo_q2": 1.141, "hi_q2": 3.405, "p_rise": 0.279, "xh_pp": 0.405, "b90_pp": 10.098, "form_4q": 4.176, "form_lo": 2.806, "form_hi": 6.463, "form_trailing": 2.971},
  {"ticker": "CCAP", "period_end": "2026-06-30", "na_now": 4.47, "na_mean8": 3.294, "wl_high_pct": 0.598, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 4.118, "lo_q1": 3.416, "hi_q1": 5.097, "q2_label": "2026-Q4", "na_q2": 4.238, "lo_q2": 3.361, "hi_q2": 5.625, "p_rise": 0.222, "xh_pp": 0.234, "b90_pp": 10.974, "form_4q": 3.836, "form_lo": 2.466, "form_hi": 6.123, "form_trailing": 4.766},
  {"ticker": "BBDC", "period_end": "2026-06-30", "na_now": 1.53, "na_mean8": 1.662, "wl_high_pct": 0.349, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 1.611, "lo_q1": 0.909, "hi_q1": 2.59, "q2_label": "2026-Q4", "na_q2": 1.681, "lo_q2": 0.804, "hi_q2": 3.068, "p_rise": 0.222, "xh_pp": 0.216, "b90_pp": 8.892, "form_4q": 3.476, "form_lo": 2.106, "form_hi": 5.763, "form_trailing": 1.344},
  {"ticker": "MAIN", "period_end": "2026-06-30", "na_now": 3.99, "na_mean8": 3.975, "wl_high_pct": 0.724, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 4.057, "lo_q1": 3.355, "hi_q1": 5.036, "q2_label": "2026-Q4", "na_q2": 4.202, "lo_q2": 3.325, "hi_q2": 5.589, "p_rise": 0.26, "xh_pp": 0.387, "b90_pp": 10.176, "form_4q": 3.354, "form_lo": 1.984, "form_hi": 5.641, "form_trailing": 1.752},
  {"ticker": "OCSL", "period_end": "2026-06-30", "na_now": 3.82, "na_mean8": 5.404, "wl_high_pct": 0.642, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 4.439, "lo_q1": 3.737, "hi_q1": 5.417, "q2_label": "2026-Q4", "na_q2": 4.567, "lo_q2": 3.69, "hi_q2": 5.954, "p_rise": 0.257, "xh_pp": 0.589, "b90_pp": 15.741, "form_4q": 3.104, "form_lo": 1.734, "form_hi": 5.39, "form_trailing": 1.533},
  {"ticker": "OTF", "period_end": "2026-06-30", "na_now": 0.58, "na_mean8": 0.28, "wl_high_pct": 0.797, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 0.555, "lo_q1": 0.0, "hi_q1": 1.533, "q2_label": "2026-Q4", "na_q2": 0.714, "lo_q2": 0.0, "hi_q2": 2.101, "p_rise": 0.333, "xh_pp": 0.978, "b90_pp": 9.454, "form_4q": 3.041, "form_lo": 1.671, "form_hi": 5.328, "form_trailing": 0.505},
  {"ticker": "OBDC", "period_end": "2026-06-30", "na_now": 2.84, "na_mean8": 2.055, "wl_high_pct": 0.232, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 2.588, "lo_q1": 1.887, "hi_q1": 3.567, "q2_label": "2026-Q4", "na_q2": 2.635, "lo_q2": 1.758, "hi_q2": 4.022, "p_rise": 0.163, "xh_pp": 0.065, "b90_pp": 5.478, "form_4q": 2.674, "form_lo": 1.304, "form_hi": 4.96, "form_trailing": 2.795},
  {"ticker": "OCIC", "period_end": "2026-06-30", "na_now": 0.35, "na_mean8": 0.367, "wl_high_pct": 0.326, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 0.389, "lo_q1": 0.0, "hi_q1": 1.368, "q2_label": "2026-Q4", "na_q2": 0.454, "lo_q2": 0.0, "hi_q2": 1.841, "p_rise": 0.208, "xh_pp": 0.314, "b90_pp": 5.337, "form_4q": 2.408, "form_lo": 1.038, "form_hi": 4.694, "form_trailing": 1.127},
  {"ticker": "TSLX", "period_end": "2026-06-30", "na_now": 1.92, "na_mean8": 2.636, "wl_high_pct": 0.017, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 2.172, "lo_q1": 1.471, "hi_q1": 3.151, "q2_label": "2026-Q4", "na_q2": 2.176, "lo_q2": 1.299, "hi_q2": 3.563, "p_rise": 0.166, "xh_pp": 0.017, "b90_pp": 7.922, "form_4q": 2.013, "form_lo": 0.643, "form_hi": 4.3, "form_trailing": 1.205},
  {"ticker": "MFIC", "period_end": "2026-06-30", "na_now": 0.0, "na_mean8": 0.0, "wl_high_pct": 1.182, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 0.118, "lo_q1": 0.0, "hi_q1": 1.097, "q2_label": "2026-Q4", "na_q2": 0.355, "lo_q2": 0.0, "hi_q2": 1.742, "p_rise": 0.275, "xh_pp": 0.373, "b90_pp": 23.352, "form_4q": 2.009, "form_lo": 0.639, "form_hi": 4.295, "form_trailing": null},
  {"ticker": "ADS", "period_end": "2026-06-30", "na_now": 0.79, "na_mean8": 0.659, "wl_high_pct": 0.812, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 0.825, "lo_q1": 0.123, "hi_q1": 1.804, "q2_label": "2026-Q4", "na_q2": 0.988, "lo_q2": 0.111, "hi_q2": 2.375, "p_rise": 0.314, "xh_pp": 0.969, "b90_pp": 2.735, "form_4q": 1.84, "form_lo": 0.47, "form_hi": 4.127, "form_trailing": 0.765},
  {"ticker": "HTGC", "period_end": "2026-06-30", "na_now": 0.35, "na_mean8": 1.034, "wl_high_pct": 0.0, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 0.589, "lo_q1": 0.0, "hi_q1": 1.568, "q2_label": "2026-Q4", "na_q2": 0.589, "lo_q2": 0.0, "hi_q2": 1.977, "p_rise": 0.137, "xh_pp": 0.0, "b90_pp": 5.446, "form_4q": 1.658, "form_lo": 0.288, "form_hi": 3.945, "form_trailing": 1.324},
  {"ticker": "ASIF", "period_end": "2026-06-30", "na_now": 0.32, "na_mean8": 0.12, "wl_high_pct": 0.411, "has_watchlist": true, "q1_label": "2026-Q3", "na_q1": 0.291, "lo_q1": 0.0, "hi_q1": 1.27, "q2_label": "2026-Q4", "na_q2": 0.373, "lo_q2": 0.0, "hi_q2": 1.761, "p_rise": 0.24, "xh_pp": 0.413, "b90_pp": 5.788, "form_4q": 1.6, "form_lo": 0.23, "form_hi": 3.886, "form_trailing": 0.427}
];

// Predicted loss content by quartile, per quarter, across the whole BDC
// universe. Quartiles are cut WITHIN each quarter (a pooled cut would just
// re-rank the universe by calendar time), equal-weighted across the BDCs in
// each bucket. `actual` is the realised 4-quarter formation for the same
// BDCs and is only populated where four quarters have since elapsed.
export interface NaQuartilePoint {
  period_end: string; q: number; pred: number; actual: number | null; n: number;
}

export const naQuartileSeries: NaQuartilePoint[] = [
  {"period_end": "2022-06-30", "q": 1, "pred": 0.458, "actual": 0.084, "n": 4},
  {"period_end": "2022-06-30", "q": 2, "pred": 0.958, "actual": 2.035, "n": 4},
  {"period_end": "2022-06-30", "q": 3, "pred": 1.233, "actual": 1.585, "n": 3},
  {"period_end": "2022-06-30", "q": 4, "pred": 1.727, "actual": 2.486, "n": 4},
  {"period_end": "2022-09-30", "q": 1, "pred": 0.32, "actual": 0.07, "n": 4},
  {"period_end": "2022-09-30", "q": 2, "pred": 0.958, "actual": 0.999, "n": 4},
  {"period_end": "2022-09-30", "q": 3, "pred": 1.481, "actual": 1.631, "n": 4},
  {"period_end": "2022-09-30", "q": 4, "pred": 2.054, "actual": 2.295, "n": 4},
  {"period_end": "2022-12-31", "q": 1, "pred": 0.298, "actual": 0.218, "n": 4},
  {"period_end": "2022-12-31", "q": 2, "pred": 0.962, "actual": 0.903, "n": 4},
  {"period_end": "2022-12-31", "q": 3, "pred": 1.375, "actual": 2.748, "n": 4},
  {"period_end": "2022-12-31", "q": 4, "pred": 2.509, "actual": 2.76, "n": 4},
  {"period_end": "2023-03-31", "q": 1, "pred": 0.581, "actual": 0.353, "n": 5},
  {"period_end": "2023-03-31", "q": 2, "pred": 0.963, "actual": 1.291, "n": 4},
  {"period_end": "2023-03-31", "q": 3, "pred": 1.755, "actual": 2.555, "n": 4},
  {"period_end": "2023-03-31", "q": 4, "pred": 2.951, "actual": 3.963, "n": 4},
  {"period_end": "2023-06-30", "q": 1, "pred": 0.441, "actual": 0.358, "n": 5},
  {"period_end": "2023-06-30", "q": 2, "pred": 1.136, "actual": 4.314, "n": 4},
  {"period_end": "2023-06-30", "q": 3, "pred": 2.0, "actual": 2.29, "n": 4},
  {"period_end": "2023-06-30", "q": 4, "pred": 3.047, "actual": 4.262, "n": 4},
  {"period_end": "2023-09-30", "q": 1, "pred": 0.485, "actual": 1.227, "n": 5},
  {"period_end": "2023-09-30", "q": 2, "pred": 1.811, "actual": 4.035, "n": 4},
  {"period_end": "2023-09-30", "q": 3, "pred": 2.528, "actual": 1.553, "n": 4},
  {"period_end": "2023-09-30", "q": 4, "pred": 3.326, "actual": 3.704, "n": 4},
  {"period_end": "2023-12-31", "q": 1, "pred": 0.387, "actual": 0.853, "n": 5},
  {"period_end": "2023-12-31", "q": 2, "pred": 1.315, "actual": 3.754, "n": 4},
  {"period_end": "2023-12-31", "q": 3, "pred": 2.495, "actual": 1.636, "n": 4},
  {"period_end": "2023-12-31", "q": 4, "pred": 3.642, "actual": 2.695, "n": 4},
  {"period_end": "2024-03-31", "q": 1, "pred": 0.86, "actual": 0.922, "n": 5},
  {"period_end": "2024-03-31", "q": 2, "pred": 2.126, "actual": 2.253, "n": 4},
  {"period_end": "2024-03-31", "q": 3, "pred": 2.999, "actual": 5.466, "n": 4},
  {"period_end": "2024-03-31", "q": 4, "pred": 3.773, "actual": 2.24, "n": 4},
  {"period_end": "2024-06-30", "q": 1, "pred": 0.883, "actual": 0.895, "n": 5},
  {"period_end": "2024-06-30", "q": 2, "pred": 1.92, "actual": 2.091, "n": 4},
  {"period_end": "2024-06-30", "q": 3, "pred": 2.973, "actual": 3.05, "n": 4},
  {"period_end": "2024-06-30", "q": 4, "pred": 3.876, "actual": 3.105, "n": 4},
  {"period_end": "2024-09-30", "q": 1, "pred": 1.017, "actual": 0.482, "n": 5},
  {"period_end": "2024-09-30", "q": 2, "pred": 1.754, "actual": 2.37, "n": 4},
  {"period_end": "2024-09-30", "q": 3, "pred": 2.546, "actual": 1.124, "n": 4},
  {"period_end": "2024-09-30", "q": 4, "pred": 3.589, "actual": 4.845, "n": 4},
  {"period_end": "2024-12-31", "q": 1, "pred": 0.772, "actual": 1.14, "n": 5},
  {"period_end": "2024-12-31", "q": 2, "pred": 1.556, "actual": 1.345, "n": 4},
  {"period_end": "2024-12-31", "q": 3, "pred": 2.287, "actual": 3.229, "n": 4},
  {"period_end": "2024-12-31", "q": 4, "pred": 3.71, "actual": 4.403, "n": 5},
  {"period_end": "2025-03-31", "q": 1, "pred": 1.24, "actual": 1.585, "n": 5},
  {"period_end": "2025-03-31", "q": 2, "pred": 1.996, "actual": 1.954, "n": 4},
  {"period_end": "2025-03-31", "q": 3, "pred": 3.027, "actual": 3.099, "n": 4},
  {"period_end": "2025-03-31", "q": 4, "pred": 3.551, "actual": 4.703, "n": 4},
  {"period_end": "2025-06-30", "q": 1, "pred": 1.026, "actual": 1.264, "n": 5},
  {"period_end": "2025-06-30", "q": 2, "pred": 1.98, "actual": 1.536, "n": 4},
  {"period_end": "2025-06-30", "q": 3, "pred": 3.122, "actual": 3.359, "n": 4},
  {"period_end": "2025-06-30", "q": 4, "pred": 3.727, "actual": 3.786, "n": 5},
  {"period_end": "2025-09-30", "q": 1, "pred": 1.022, "actual": null, "n": 5},
  {"period_end": "2025-09-30", "q": 2, "pred": 2.3, "actual": null, "n": 4},
  {"period_end": "2025-09-30", "q": 3, "pred": 3.188, "actual": null, "n": 4},
  {"period_end": "2025-09-30", "q": 4, "pred": 4.039, "actual": null, "n": 5},
  {"period_end": "2025-12-31", "q": 1, "pred": 1.079, "actual": null, "n": 5},
  {"period_end": "2025-12-31", "q": 2, "pred": 2.296, "actual": null, "n": 4},
  {"period_end": "2025-12-31", "q": 3, "pred": 3.151, "actual": null, "n": 4},
  {"period_end": "2025-12-31", "q": 4, "pred": 4.443, "actual": null, "n": 5},
  {"period_end": "2026-03-31", "q": 1, "pred": 1.773, "actual": null, "n": 5},
  {"period_end": "2026-03-31", "q": 2, "pred": 2.723, "actual": null, "n": 4},
  {"period_end": "2026-03-31", "q": 3, "pred": 3.792, "actual": null, "n": 4},
  {"period_end": "2026-03-31", "q": 4, "pred": 4.992, "actual": null, "n": 5},
  {"period_end": "2026-06-30", "q": 1, "pred": 1.904, "actual": null, "n": 5},
  {"period_end": "2026-06-30", "q": 2, "pred": 3.043, "actual": null, "n": 4},
  {"period_end": "2026-06-30", "q": 3, "pred": 3.968, "actual": null, "n": 4},
  {"period_end": "2026-06-30", "q": 4, "pred": 5.819, "actual": null, "n": 5}
];

export const naFcMeta = {
  "generated": "2026-09-18",
  "shrink_k": 0.35,
  "high_b": {
    "1": 0.1,
    "2": 0.3
  },
  "mean_window_q": 8,
  "backtest_from": "2021-03-31",
  "horizons": {
    "1": {
      "n": 323,
      "mean_abs": 0.5709,
      "median_abs": 0.2422,
      "p90_abs": 1.3419,
      "naive_mean_abs": 0.601,
      "naive_median_abs": 0.2,
      "naive_p90_abs": 1.612,
      "q10": -0.9788,
      "q90": 0.7018
    },
    "2": {
      "n": 304,
      "mean_abs": 0.7141,
      "median_abs": 0.3709,
      "p90_abs": 1.6148,
      "naive_mean_abs": 0.7574,
      "naive_median_abs": 0.355,
      "naive_p90_abs": 1.864,
      "q10": -1.3872,
      "q90": 0.8769
    }
  },
  "direction": {
    "n": 359,
    "base_rate": 0.1783,
    "auc": 0.5865,
    "top_decile_hit": 0.3143,
    "top_decile_lift": 1.7629,
    "threshold_pp": 0.5
  },
  "formation": {
    "n": 204,
    "horizon_q": 4,
    "mean_abs": 1.2263,
    "corr": 0.5024,
    "bias": -0.2943,
    "actual_mean": 2.2319,
    "band_lo": 1.3701,
    "band_hi": -2.2867,
    "quartiles": [
      {
        "q": 1,
        "pred": 0.580020276553828,
        "actual": 0.7304488942600531,
        "n": 51
      },
      {
        "q": 2,
        "pred": 1.3986510440944415,
        "actual": 2.0875312389585896,
        "n": 51
      },
      {
        "q": 3,
        "pred": 2.2677570529415694,
        "actual": 2.3634932030198272,
        "n": 51
      },
      {
        "q": 4,
        "pred": 3.5040171054603397,
        "actual": 3.7462436621646225,
        "n": 51
      }
    ]
  }
} as const;
