// AUTO-GENERATED by scripts/50_export_dashboard_data.py — do not edit by hand.
// Per-cohort-year outcomes of cash→PIK flips, measured 4 quarters after the
// flip. Tranche-level using loan_history.loan_id (each loan tranche tracked
// separately rather than collapsed to the borrower).
//
//   flips        # loan-tranches we observed flipping cash→PIK in this year
//   cured        # back to cash-pay 4 quarters later
//   pik_strong   # still PIK at T+4, mark ≥ 90¢ of par (steady)
//   pik_weak     # still PIK at T+4, mark 80–90¢ of par (mild stress)
//   pik_distress # still PIK at T+4, mark < 80¢ of par (deteriorated)
//   exited       # no observation at T+4 (refi / paydown / write-off / sale)
// Years with fewer than 10 flips omitted.

export interface PIKCascadeRow {
  year: string;
  flips: number;
  cured: number;
  pik_strong: number;
  pik_weak: number;
  pik_distress: number;
  exited: number;
  pct_cured: number;
  pct_pik_strong: number;
  pct_pik_weak: number;
  pct_pik_distress: number;
  pct_exited: number;
}

export const pikCascade: PIKCascadeRow[] = [
  { year: "2015", flips: 18, cured: 3, pik_strong: 10, pik_weak: 2, pik_distress: 0, exited: 3, pct_cured: 16.67, pct_pik_strong: 55.56, pct_pik_weak: 11.11, pct_pik_distress: 0.00, pct_exited: 16.67 },
  { year: "2016", flips: 19, cured: 1, pik_strong: 10, pik_weak: 4, pik_distress: 0, exited: 4, pct_cured: 5.26, pct_pik_strong: 52.63, pct_pik_weak: 21.05, pct_pik_distress: 0.00, pct_exited: 21.05 },
  { year: "2017", flips: 12, cured: 2, pik_strong: 4, pik_weak: 0, pik_distress: 0, exited: 6, pct_cured: 16.67, pct_pik_strong: 33.33, pct_pik_weak: 0.00, pct_pik_distress: 0.00, pct_exited: 50.00 },
  { year: "2018", flips: 17, cured: 3, pik_strong: 4, pik_weak: 0, pik_distress: 1, exited: 9, pct_cured: 17.65, pct_pik_strong: 23.53, pct_pik_weak: 0.00, pct_pik_distress: 5.88, pct_exited: 52.94 },
  { year: "2019", flips: 42, cured: 13, pik_strong: 9, pik_weak: 2, pik_distress: 2, exited: 16, pct_cured: 30.95, pct_pik_strong: 21.43, pct_pik_weak: 4.76, pct_pik_distress: 4.76, pct_exited: 38.10 },
  { year: "2020", flips: 190, cured: 31, pik_strong: 72, pik_weak: 9, pik_distress: 13, exited: 65, pct_cured: 16.32, pct_pik_strong: 37.89, pct_pik_weak: 4.74, pct_pik_distress: 6.84, pct_exited: 34.21 },
  { year: "2021", flips: 148, cured: 34, pik_strong: 59, pik_weak: 3, pik_distress: 17, exited: 35, pct_cured: 22.97, pct_pik_strong: 39.86, pct_pik_weak: 2.03, pct_pik_distress: 11.49, pct_exited: 23.65 },
  { year: "2022", flips: 203, cured: 44, pik_strong: 85, pik_weak: 4, pik_distress: 19, exited: 51, pct_cured: 21.67, pct_pik_strong: 41.87, pct_pik_weak: 1.97, pct_pik_distress: 9.36, pct_exited: 25.12 },
  { year: "2023", flips: 383, cured: 81, pik_strong: 158, pik_weak: 12, pik_distress: 35, exited: 97, pct_cured: 21.15, pct_pik_strong: 41.25, pct_pik_weak: 3.13, pct_pik_distress: 9.14, pct_exited: 25.33 },
  { year: "2024", flips: 486, cured: 140, pik_strong: 197, pik_weak: 13, pik_distress: 37, exited: 99, pct_cured: 28.81, pct_pik_strong: 40.53, pct_pik_weak: 2.67, pct_pik_distress: 7.61, pct_exited: 20.37 },
  { year: "2025", flips: 644, cured: 109, pik_strong: 246, pik_weak: 14, pik_distress: 32, exited: 243, pct_cured: 16.93, pct_pik_strong: 38.20, pct_pik_weak: 2.17, pct_pik_distress: 4.97, pct_exited: 37.73 },
  { year: "2026", flips: 231, cured: 0, pik_strong: 8, pik_weak: 0, pik_distress: 0, exited: 223, pct_cured: 0.00, pct_pik_strong: 3.46, pct_pik_weak: 0.00, pct_pik_distress: 0.00, pct_exited: 96.54 }
];
