// AUTO-GENERATED by scripts/50_export_dashboard_data.py — do not edit by hand.
// Per-cohort-year outcomes of cash→PIK flips, measured 4 quarters after the
// flip. Tranche-level using loan_history.loan_id (each loan tranche tracked
// separately rather than collapsed to the borrower).
//
//   flips        # loan-tranches we observed flipping cash→PIK in this year
//   cured        # back to cash-pay 4 quarters later
//   pik_strong   # still PIK at T+4, mark ≥ 90¢ of par (steady)
//   pik_weak     # still PIK at T+4, mark 80–90¢ of par (mild stress)
//   pik_distress # still PIK at T+4, mark < 80¢ of par (deteriorated)
//   exited       # no observation at T+4 (refi / paydown / write-off / sale)
// Years with fewer than 10 flips omitted.

export interface PIKCascadeRow {
  year: string;
  flips: number;
  cured: number;
  pik_strong: number;
  pik_weak: number;
  pik_distress: number;
  exited: number;
  pct_cured: number;
  pct_pik_strong: number;
  pct_pik_weak: number;
  pct_pik_distress: number;
  pct_exited: number;
}

export const pikCascade: PIKCascadeRow[] = [
  { year: "2019", flips: 20, cured: 0, pik_strong: 12, pik_weak: 0, pik_distress: 2, exited: 6, pct_cured: 0.00, pct_pik_strong: 60.00, pct_pik_weak: 0.00, pct_pik_distress: 10.00, pct_exited: 30.00 },
  { year: "2020", flips: 108, cured: 33, pik_strong: 35, pik_weak: 6, pik_distress: 4, exited: 30, pct_cured: 30.56, pct_pik_strong: 32.41, pct_pik_weak: 5.56, pct_pik_distress: 3.70, pct_exited: 27.78 },
  { year: "2021", flips: 37, cured: 5, pik_strong: 17, pik_weak: 1, pik_distress: 14, exited: 0, pct_cured: 13.51, pct_pik_strong: 45.95, pct_pik_weak: 2.70, pct_pik_distress: 37.84, pct_exited: 0.00 },
  { year: "2022", flips: 53, cured: 10, pik_strong: 29, pik_weak: 3, pik_distress: 1, exited: 10, pct_cured: 18.87, pct_pik_strong: 54.72, pct_pik_weak: 5.66, pct_pik_distress: 1.89, pct_exited: 18.87 },
  { year: "2023", flips: 144, cured: 32, pik_strong: 51, pik_weak: 20, pik_distress: 23, exited: 18, pct_cured: 22.22, pct_pik_strong: 35.42, pct_pik_weak: 13.89, pct_pik_distress: 15.97, pct_exited: 12.50 },
  { year: "2024", flips: 262, cured: 47, pik_strong: 101, pik_weak: 22, pik_distress: 40, exited: 52, pct_cured: 17.94, pct_pik_strong: 38.55, pct_pik_weak: 8.40, pct_pik_distress: 15.27, pct_exited: 19.85 },
  { year: "2025", flips: 202, cured: 20, pik_strong: 34, pik_weak: 10, pik_distress: 19, exited: 119, pct_cured: 9.90, pct_pik_strong: 16.83, pct_pik_weak: 4.95, pct_pik_distress: 9.41, pct_exited: 58.91 },
  { year: "2026", flips: 168, cured: 0, pik_strong: 0, pik_weak: 0, pik_distress: 0, exited: 168, pct_cured: 0.00, pct_pik_strong: 0.00, pct_pik_weak: 0.00, pct_pik_distress: 0.00, pct_exited: 100.00 }
];
