// AUTO-GENERATED by scripts/50_export_dashboard_data.py — do not edit by hand.
// Per-cohort-year outcomes of cash→PIK flips, measured 4 quarters after the
// flip. Tranche-level using loan_history.loan_id (each loan tranche tracked
// separately rather than collapsed to the borrower).
//
//   flips        # loan-tranches we observed flipping cash→PIK in this year
//   cured        # back to cash-pay 4 quarters later
//   pik_strong   # still PIK at T+4, mark ≥ 90¢ of par (steady)
//   pik_weak     # still PIK at T+4, mark 80–90¢ of par (mild stress)
//   pik_distress # still PIK at T+4, mark < 80¢ of par (deteriorated)
//   exited       # no observation at T+4 (refi / paydown / write-off / sale)
// Years with fewer than 10 flips omitted.

export interface PIKCascadeRow {
  year: string;
  flips: number;
  cured: number;
  pik_strong: number;
  pik_weak: number;
  pik_distress: number;
  exited: number;
  pct_cured: number;
  pct_pik_strong: number;
  pct_pik_weak: number;
  pct_pik_distress: number;
  pct_exited: number;
}

export const pikCascade: PIKCascadeRow[] = [
  { year: "2019", flips: 27, cured: 4, pik_strong: 13, pik_weak: 0, pik_distress: 2, exited: 8, pct_cured: 14.81, pct_pik_strong: 48.15, pct_pik_weak: 0.00, pct_pik_distress: 7.41, pct_exited: 29.63 },
  { year: "2020", flips: 115, cured: 33, pik_strong: 40, pik_weak: 7, pik_distress: 4, exited: 31, pct_cured: 28.70, pct_pik_strong: 34.78, pct_pik_weak: 6.09, pct_pik_distress: 3.48, pct_exited: 26.96 },
  { year: "2021", flips: 40, cured: 6, pik_strong: 17, pik_weak: 2, pik_distress: 14, exited: 1, pct_cured: 15.00, pct_pik_strong: 42.50, pct_pik_weak: 5.00, pct_pik_distress: 35.00, pct_exited: 2.50 },
  { year: "2022", flips: 58, cured: 10, pik_strong: 36, pik_weak: 4, pik_distress: 1, exited: 7, pct_cured: 17.24, pct_pik_strong: 62.07, pct_pik_weak: 6.90, pct_pik_distress: 1.72, pct_exited: 12.07 },
  { year: "2023", flips: 178, cured: 33, pik_strong: 77, pik_weak: 22, pik_distress: 22, exited: 24, pct_cured: 18.54, pct_pik_strong: 43.26, pct_pik_weak: 12.36, pct_pik_distress: 12.36, pct_exited: 13.48 },
  { year: "2024", flips: 259, cured: 52, pik_strong: 99, pik_weak: 19, pik_distress: 35, exited: 54, pct_cured: 20.08, pct_pik_strong: 38.22, pct_pik_weak: 7.34, pct_pik_distress: 13.51, pct_exited: 20.85 },
  { year: "2025", flips: 212, cured: 21, pik_strong: 34, pik_weak: 10, pik_distress: 18, exited: 129, pct_cured: 9.91, pct_pik_strong: 16.04, pct_pik_weak: 4.72, pct_pik_distress: 8.49, pct_exited: 60.85 },
  { year: "2026", flips: 165, cured: 0, pik_strong: 0, pik_weak: 0, pik_distress: 0, exited: 165, pct_cured: 0.00, pct_pik_strong: 0.00, pct_pik_weak: 0.00, pct_pik_distress: 0.00, pct_exited: 100.00 }
];
