// AUTO-GENERATED by scripts/50_export_dashboard_data.py — do not edit by hand.
// Per-sector credit metrics for the most recent reliable quarter (≥10 BDCs
// reporting). Sectors normalized from free-text SOI industry strings via a
// canonical-sector map; "Unclassified" = no industry tag in the SOI; "Other"
// = industry tag didn't match any of our canonical sectors.
//
// Mark-based metrics use a debt-shape filter (par ≈ cost) to exclude equity
// share-count noise — same approach as the main credit_quality export.

export interface SectorCredit {
  sector: string;
  period_end: string;
  n_positions: number;
  total_cost_b: number;
  debt_cost_b: number;
  pct_below_95: number;
  pct_below_90: number;
  pct_non_accrual: number;
  pct_pik: number;
}

export const sectorCredit: SectorCredit[] = [
  { sector: "Software & IT", period_end: "2026-06-30", n_positions: 2409, total_cost_b: 68.970, debt_cost_b: 60.502, pct_below_95: 22.01, pct_below_90: 14.97, pct_non_accrual: 3.00, pct_pik: 18.65 },
  { sector: "Healthcare", period_end: "2026-06-30", n_positions: 2002, total_cost_b: 50.330, debt_cost_b: 43.542, pct_below_95: 17.41, pct_below_90: 11.76, pct_non_accrual: 2.50, pct_pik: 20.96 },
  { sector: "Professional Services", period_end: "2026-06-30", n_positions: 2012, total_cost_b: 43.940, debt_cost_b: 41.204, pct_below_95: 12.56, pct_below_90: 5.12, pct_non_accrual: 0.69, pct_pik: 9.08 },
  { sector: "Industrial", period_end: "2026-06-30", n_positions: 1281, total_cost_b: 26.177, debt_cost_b: 24.103, pct_below_95: 11.68, pct_below_90: 9.48, pct_non_accrual: 3.29, pct_pik: 9.29 },
  { sector: "Other", period_end: "2026-06-30", n_positions: 1122, total_cost_b: 24.187, debt_cost_b: 17.631, pct_below_95: 17.81, pct_below_90: 13.98, pct_non_accrual: 0.49, pct_pik: 11.18 },
  { sector: "Insurance", period_end: "2026-06-30", n_positions: 534, total_cost_b: 15.997, debt_cost_b: 13.228, pct_below_95: 10.22, pct_below_90: 1.49, pct_non_accrual: 0.58, pct_pik: 14.38 },
  { sector: "Financial Services", period_end: "2026-06-30", n_positions: 702, total_cost_b: 15.377, debt_cost_b: 10.573, pct_below_95: 8.69, pct_below_90: 3.04, pct_non_accrual: 0.02, pct_pik: 11.88 },
  { sector: "Consumer / Retail", period_end: "2026-06-30", n_positions: 772, total_cost_b: 12.036, debt_cost_b: 11.020, pct_below_95: 15.77, pct_below_90: 8.75, pct_non_accrual: 4.11, pct_pik: 13.09 },
  { sector: "Unclassified", period_end: "2026-06-30", n_positions: 302, total_cost_b: 11.429, debt_cost_b: 5.402, pct_below_95: 1.88, pct_below_90: 0.54, pct_non_accrual: 0.32, pct_pik: 3.42 },
  { sector: "Media & Entertainment", period_end: "2026-06-30", n_positions: 271, total_cost_b: 8.024, debt_cost_b: 6.186, pct_below_95: 6.28, pct_below_90: 3.66, pct_non_accrual: 1.49, pct_pik: 20.72 },
  { sector: "Materials & Chemicals", period_end: "2026-06-30", n_positions: 202, total_cost_b: 4.607, debt_cost_b: 4.254, pct_below_95: 9.28, pct_below_90: 1.13, pct_non_accrual: 0.77, pct_pik: 7.06 },
  { sector: "Utilities & Energy", period_end: "2026-06-30", n_positions: 154, total_cost_b: 4.560, debt_cost_b: 3.867, pct_below_95: 3.17, pct_below_90: 1.90, pct_non_accrual: 2.62, pct_pik: 2.72 },
  { sector: "Real Estate", period_end: "2026-06-30", n_positions: 98, total_cost_b: 4.357, debt_cost_b: 3.523, pct_below_95: 13.78, pct_below_90: 7.47, pct_non_accrual: 3.10, pct_pik: 20.15 }
];
