// AUTO-GENERATED by scripts/51_export_early_warning.py — do not edit by hand.
// Predictive back-test: for each signal / tier, the share of pre-non-accrual
// positions carrying it that went on to NON-ACCRUAL (rate_na) or to
// non-accrual-OR-marked-below-80 (rate_bad) within 4 quarters, vs the base
// rate across all positions. `lift` = rate / base rate. Coverage floor 2018.

export interface BacktestRow {
  signal: string; n: number;
  rate_bad: number; rate_na: number;
  lift_bad: number | null; lift_na: number | null;
}
export const signalBacktest: BacktestRow[] = [
  {"signal": "ALL (base rate)", "n": 103569, "rate_bad": 5.7, "rate_na": 2.5, "lift_bad": 1.0, "lift_na": 1.0},
  {"signal": "mark < 90c", "n": 7421, "rate_bad": 41.7, "rate_na": 13.9, "lift_bad": 7.3, "lift_na": 5.7},
  {"signal": "mark < 80c", "n": 2620, "rate_bad": 68.5, "rate_na": 21.8, "lift_bad": 11.9, "lift_na": 8.9},
  {"signal": "mark falling ≥3pt QoQ", "n": 5180, "rate_bad": 30.0, "rate_na": 12.2, "lift_bad": 5.2, "lift_na": 5.0},
  {"signal": "falling 2 quarters", "n": 845, "rate_bad": 56.0, "rate_na": 24.6, "lift_bad": 9.7, "lift_na": 10.0},
  {"signal": "cash→PIK flip", "n": 1043, "rate_bad": 26.4, "rate_na": 15.7, "lift_bad": 4.6, "lift_na": 6.4},
  {"signal": "PIK severe", "n": 3455, "rate_bad": 20.4, "rate_na": 15.1, "lift_bad": 3.6, "lift_na": 6.1},
  {"signal": "amend-and-extend", "n": 5178, "rate_bad": 7.7, "rate_na": 4.2, "lift_bad": 1.3, "lift_na": 1.7},
  {"signal": "spread cut", "n": 4087, "rate_bad": 6.4, "rate_na": 3.2, "lift_bad": 1.1, "lift_na": 1.3},
  {"signal": "NA at another BDC", "n": 605, "rate_bad": 74.7, "rate_na": 73.1, "lift_bad": 13.0, "lift_na": 29.8},
  {"signal": "NA elsewhere + mark < 90c", "n": 128, "rate_bad": 85.9, "rate_na": 81.2, "lift_bad": 15.0, "lift_na": 33.1},
  {"signal": "tier: Watch", "n": 6679, "rate_bad": 32.1, "rate_na": 11.2, "lift_bad": 5.6, "lift_na": 4.5},
  {"signal": "tier: Elevated", "n": 1923, "rate_bad": 58.9, "rate_na": 26.9, "lift_bad": 10.2, "lift_na": 11.0},
  {"signal": "tier: High", "n": 359, "rate_bad": 81.9, "rate_na": 53.5, "lift_bad": 14.2, "lift_na": 21.8}
];
