// AUTO-GENERATED by bdc_inventory/scripts/79_export_site_meta.py — do not edit.
export const siteMeta = {
  "latest_period": "2026-06-30",
  "latest_quarter": "2026 Q2",
  "n_bdcs": 19,
  "n_filings": 509,
  "dataset_periods": {
    "core": {
      "first_period": "2013-12-31",
      "latest_period": "2026-06-30"
    },
    "long_tail": {
      "max": "2025-12-31",
      "independently_revalidated": false
    }
  },
  "issuer_latest_periods": {
    "ADS": "2026-06-30",
    "ARCC": "2026-06-30",
    "ASIF": "2026-06-30",
    "BBDC": "2026-06-30",
    "BCRED": "2026-06-30",
    "BXSL": "2026-06-30",
    "CCAP": "2026-06-30",
    "CGBD": "2026-06-30",
    "FSK": "2026-06-30",
    "GBDC": "2026-06-30",
    "HTGC": "2026-06-30",
    "MAIN": "2026-06-30",
    "MFIC": "2026-06-30",
    "NMFC": "2026-06-30",
    "OBDC": "2026-06-30",
    "OCIC": "2026-06-30",
    "OCSL": "2026-06-30",
    "OTF": "2026-06-30",
    "TSLX": "2026-06-30"
  },
  "release_id": "bdc-76d1b63b1ec84c6e8d08c676",
  "generated_at": "2026-09-26",
  "checked_at": "2026-09-26T01:15:45-04:00",
  "validation_scope": "Automated consistency checks: data files well-formed and consistent, database invariants, and each BDC's latest book against the filing's reported total investments. Not an independent audit of every loan or event."
};
