// AUTO-GENERATED by scripts/50_export_dashboard_data.py — do not edit by hand.
// Per-sponsor rollup from bdctransparency.io's company-sponsor mapping
// intersected with our /borrowers index. Sponsors with no companies in our
// indexed universe are omitted.

export interface SponsorIndex {
  sponsor_slug: string;
  sponsor: string;
  n_companies: number;      // count of companies in our index attributed to this sponsor
  total_fv: number;         // sum of latest-quarter FV across those companies, USD
  avg_holders: number;      // mean # of BDC holders per attributed company
}

export const sponsors: SponsorIndex[] = [
  {"sponsor_slug": "vista-equity-partners", "sponsor": "Vista Equity Partners", "n_companies": 10, "total_fv": 1070682000.0, "avg_holders": 2.7},
  {"sponsor_slug": "bain-capital", "sponsor": "Bain Capital", "n_companies": 7, "total_fv": 940075000.0, "avg_holders": 2.2857142857142856},
  {"sponsor_slug": "hellman-friedman", "sponsor": "Hellman & Friedman", "n_companies": 3, "total_fv": 911311000.0, "avg_holders": 3.6666666666666665},
  {"sponsor_slug": "thoma-bravo", "sponsor": "Thoma Bravo", "n_companies": 8, "total_fv": 882409000.0, "avg_holders": 3.0},
  {"sponsor_slug": "insight-partners", "sponsor": "Insight Partners", "n_companies": 10, "total_fv": 625903000.0, "avg_holders": 2.5},
  {"sponsor_slug": "permira", "sponsor": "Permira", "n_companies": 5, "total_fv": 592221000.0, "avg_holders": 3.0},
  {"sponsor_slug": "ta-associates", "sponsor": "TA Associates", "n_companies": 8, "total_fv": 536787000.0, "avg_holders": 2.625},
  {"sponsor_slug": "tpg-capital", "sponsor": "TPG Capital", "n_companies": 7, "total_fv": 481590000.0, "avg_holders": 2.5714285714285716},
  {"sponsor_slug": "blackstone", "sponsor": "Blackstone", "n_companies": 4, "total_fv": 435170000.0, "avg_holders": 2.25},
  {"sponsor_slug": "francisco-partners", "sponsor": "Francisco Partners", "n_companies": 6, "total_fv": 368630000.0, "avg_holders": 2.5},
  {"sponsor_slug": "thl-partners", "sponsor": "THL Partners", "n_companies": 2, "total_fv": 326665000.0, "avg_holders": 1.0},
  {"sponsor_slug": "gi-partners", "sponsor": "GI Partners", "n_companies": 5, "total_fv": 319527000.0, "avg_holders": 2.6},
  {"sponsor_slug": "hg", "sponsor": "Hg", "n_companies": 3, "total_fv": 285447000.0, "avg_holders": 1.6666666666666667},
  {"sponsor_slug": "clearlake-capital-group", "sponsor": "Clearlake Capital Group", "n_companies": 6, "total_fv": 284836000.0, "avg_holders": 2.1666666666666665},
  {"sponsor_slug": "genstar-capital", "sponsor": "Genstar Capital", "n_companies": 5, "total_fv": 271507000.0, "avg_holders": 2.0},
  {"sponsor_slug": "nordic-capital", "sponsor": "Nordic Capital", "n_companies": 1, "total_fv": 241441000.0, "avg_holders": 3.0},
  {"sponsor_slug": "hggc", "sponsor": "HGGC", "n_companies": 1, "total_fv": 177357000.0, "avg_holders": 2.0},
  {"sponsor_slug": "elliott-private-equity", "sponsor": "Elliott Private Equity", "n_companies": 3, "total_fv": 148334000.0, "avg_holders": 2.3333333333333335},
  {"sponsor_slug": "five-arrows", "sponsor": "Five Arrows", "n_companies": 1, "total_fv": 137137000.0, "avg_holders": 2.0},
  {"sponsor_slug": "goldman-sachs", "sponsor": "Goldman Sachs", "n_companies": 2, "total_fv": 128631000.0, "avg_holders": 2.0},
  {"sponsor_slug": "bc-partners", "sponsor": "BC Partners", "n_companies": 1, "total_fv": 108300000.0, "avg_holders": 1.0},
  {"sponsor_slug": "h-i-g-capital", "sponsor": "H.I.G. Capital", "n_companies": 1, "total_fv": 104500000.0, "avg_holders": 1.0},
  {"sponsor_slug": "warburg-pincus", "sponsor": "Warburg Pincus", "n_companies": 3, "total_fv": 100384000.0, "avg_holders": 1.6666666666666667},
  {"sponsor_slug": "centerbridge-partners", "sponsor": "Centerbridge Partners", "n_companies": 2, "total_fv": 89730000.0, "avg_holders": 2.0},
  {"sponsor_slug": "crosspoint-capital-partners", "sponsor": "Crosspoint Capital Partners", "n_companies": 1, "total_fv": 78746000.0, "avg_holders": 2.0},
  {"sponsor_slug": "new-mountain-capital", "sponsor": "New Mountain Capital", "n_companies": 2, "total_fv": 75732000.0, "avg_holders": 2.0},
  {"sponsor_slug": "advent-international", "sponsor": "Advent International", "n_companies": 1, "total_fv": 72735000.0, "avg_holders": 2.0},
  {"sponsor_slug": "stone-point-capital", "sponsor": "Stone Point Capital", "n_companies": 2, "total_fv": 43302000.0, "avg_holders": 2.5},
  {"sponsor_slug": "psg", "sponsor": "PSG", "n_companies": 1, "total_fv": 39686000.0, "avg_holders": 2.0},
  {"sponsor_slug": "silver-lake", "sponsor": "Silver Lake", "n_companies": 1, "total_fv": 29199000.0, "avg_holders": 2.0},
  {"sponsor_slug": "leonard-green-partners", "sponsor": "Leonard Green & Partners", "n_companies": 1, "total_fv": 28684000.0, "avg_holders": 2.0},
  {"sponsor_slug": "berkshire-partners", "sponsor": "Berkshire Partners", "n_companies": 1, "total_fv": 23298000.0, "avg_holders": 2.0},
  {"sponsor_slug": "eqt", "sponsor": "EQT", "n_companies": 1, "total_fv": 22990000.0, "avg_holders": 3.0},
  {"sponsor_slug": "kkr", "sponsor": "KKR", "n_companies": 1, "total_fv": 20658000.0, "avg_holders": 2.0},
  {"sponsor_slug": "accel-kkr", "sponsor": "Accel-KKR", "n_companies": 1, "total_fv": 19300000.0, "avg_holders": 2.0},
  {"sponsor_slug": "apax-partners", "sponsor": "Apax Partners", "n_companies": 2, "total_fv": 17238000.0, "avg_holders": 2.0},
  {"sponsor_slug": "arlington-capital-partners", "sponsor": "Arlington Capital Partners", "n_companies": 1, "total_fv": 16638000.0, "avg_holders": 2.0},
  {"sponsor_slug": "k1-investment-management", "sponsor": "K1 Investment Management", "n_companies": 1, "total_fv": 9190000.0, "avg_holders": 2.0},
  {"sponsor_slug": "veritas-capital", "sponsor": "Veritas Capital", "n_companies": 1, "total_fv": 3936000.0, "avg_holders": 2.0},
  {"sponsor_slug": "skyknight", "sponsor": "SkyKnight", "n_companies": 1, "total_fv": 1043000.0, "avg_holders": 2.0},
  {"sponsor_slug": "charlesbank-capital-partners", "sponsor": "Charlesbank Capital Partners", "n_companies": 1, "total_fv": 1043000.0, "avg_holders": 2.0},
  {"sponsor_slug": "reverence-capital-partners", "sponsor": "Reverence Capital Partners", "n_companies": 1, "total_fv": 655000.0, "avg_holders": 2.0}
];
