// AUTO-GENERATED by scripts/50_export_dashboard_data.py — do not edit by hand.
// Per-sponsor rollup from bdctransparency.io's company-sponsor mapping
// intersected with our /borrowers index. Sponsors with no companies in our
// indexed universe are omitted.

export interface SponsorIndex {
  sponsor_slug: string;
  sponsor: string;
  n_companies: number;      // count of companies in our index attributed to this sponsor
  total_fv: number;         // sum of latest-quarter FV across those companies, USD
  avg_holders: number;      // mean # of BDC holders per attributed company
}

export const sponsors: SponsorIndex[] = [
  {"sponsor_slug": "thoma-bravo", "sponsor": "Thoma Bravo", "n_companies": 8, "total_fv": 1745429000.0, "avg_holders": 3.0},
  {"sponsor_slug": "vista-equity-partners", "sponsor": "Vista Equity Partners", "n_companies": 10, "total_fv": 1160862000.0, "avg_holders": 2.7},
  {"sponsor_slug": "hellman-friedman", "sponsor": "Hellman & Friedman", "n_companies": 3, "total_fv": 1014529000.0, "avg_holders": 3.6666666666666665},
  {"sponsor_slug": "bain-capital", "sponsor": "Bain Capital", "n_companies": 6, "total_fv": 1004678000.0, "avg_holders": 2.5},
  {"sponsor_slug": "insight-partners", "sponsor": "Insight Partners", "n_companies": 9, "total_fv": 896283000.0, "avg_holders": 2.6666666666666665},
  {"sponsor_slug": "ta-associates", "sponsor": "TA Associates", "n_companies": 7, "total_fv": 664149000.0, "avg_holders": 2.7142857142857144},
  {"sponsor_slug": "tpg-capital", "sponsor": "TPG Capital", "n_companies": 7, "total_fv": 643618000.0, "avg_holders": 2.5714285714285716},
  {"sponsor_slug": "permira", "sponsor": "Permira", "n_companies": 5, "total_fv": 614668000.0, "avg_holders": 3.0},
  {"sponsor_slug": "clearlake-capital-group", "sponsor": "Clearlake Capital Group", "n_companies": 6, "total_fv": 546334000.0, "avg_holders": 2.1666666666666665},
  {"sponsor_slug": "francisco-partners", "sponsor": "Francisco Partners", "n_companies": 5, "total_fv": 482083000.0, "avg_holders": 2.8},
  {"sponsor_slug": "blackstone", "sponsor": "Blackstone", "n_companies": 4, "total_fv": 465093000.0, "avg_holders": 2.25},
  {"sponsor_slug": "nordic-capital", "sponsor": "Nordic Capital", "n_companies": 2, "total_fv": 404287000.0, "avg_holders": 2.5},
  {"sponsor_slug": "gi-partners", "sponsor": "GI Partners", "n_companies": 4, "total_fv": 250803000.0, "avg_holders": 2.5},
  {"sponsor_slug": "thl-partners", "sponsor": "THL Partners", "n_companies": 1, "total_fv": 236955000.0, "avg_holders": 1.0},
  {"sponsor_slug": "h-i-g-capital", "sponsor": "H.I.G. Capital", "n_companies": 2, "total_fv": 214400000.0, "avg_holders": 1.0},
  {"sponsor_slug": "new-mountain-capital", "sponsor": "New Mountain Capital", "n_companies": 2, "total_fv": 200171000.0, "avg_holders": 2.0},
  {"sponsor_slug": "genstar-capital", "sponsor": "Genstar Capital", "n_companies": 3, "total_fv": 191574000.0, "avg_holders": 2.3333333333333335},
  {"sponsor_slug": "pacific-equity-partners", "sponsor": "Pacific Equity Partners", "n_companies": 1, "total_fv": 187554000.0, "avg_holders": 1.0},
  {"sponsor_slug": "hggc", "sponsor": "HGGC", "n_companies": 1, "total_fv": 166368000.0, "avg_holders": 2.0},
  {"sponsor_slug": "elliott-private-equity", "sponsor": "Elliott Private Equity", "n_companies": 2, "total_fv": 151327000.0, "avg_holders": 2.5},
  {"sponsor_slug": "five-arrows", "sponsor": "Five Arrows", "n_companies": 1, "total_fv": 143256000.0, "avg_holders": 2.0},
  {"sponsor_slug": "goldman-sachs", "sponsor": "Goldman Sachs", "n_companies": 2, "total_fv": 137831000.0, "avg_holders": 2.0},
  {"sponsor_slug": "marlin-equity-partners", "sponsor": "Marlin Equity Partners", "n_companies": 1, "total_fv": 136000000.0, "avg_holders": 1.0},
  {"sponsor_slug": "astorg", "sponsor": "Astorg", "n_companies": 1, "total_fv": 110565000.0, "avg_holders": 2.0},
  {"sponsor_slug": "k1-investment-management", "sponsor": "K1 Investment Management", "n_companies": 1, "total_fv": 108881000.0, "avg_holders": 2.0},
  {"sponsor_slug": "bc-partners", "sponsor": "BC Partners", "n_companies": 1, "total_fv": 108300000.0, "avg_holders": 1.0},
  {"sponsor_slug": "centerbridge-partners", "sponsor": "Centerbridge Partners", "n_companies": 1, "total_fv": 88950000.0, "avg_holders": 2.0},
  {"sponsor_slug": "haveli-investments", "sponsor": "Haveli Investments", "n_companies": 1, "total_fv": 87300000.0, "avg_holders": 1.0},
  {"sponsor_slug": "crosspoint-capital-partners", "sponsor": "Crosspoint Capital Partners", "n_companies": 1, "total_fv": 78746000.0, "avg_holders": 2.0},
  {"sponsor_slug": "advent-international", "sponsor": "Advent International", "n_companies": 1, "total_fv": 72571000.0, "avg_holders": 2.0},
  {"sponsor_slug": "stone-point-capital", "sponsor": "Stone Point Capital", "n_companies": 2, "total_fv": 43302000.0, "avg_holders": 2.5},
  {"sponsor_slug": "apax-partners", "sponsor": "Apax Partners", "n_companies": 1, "total_fv": 43135000.0, "avg_holders": 2.0},
  {"sponsor_slug": "psg", "sponsor": "PSG", "n_companies": 1, "total_fv": 41086000.0, "avg_holders": 2.0},
  {"sponsor_slug": "accel-kkr", "sponsor": "Accel-KKR", "n_companies": 1, "total_fv": 37700000.0, "avg_holders": 2.0},
  {"sponsor_slug": "eqt", "sponsor": "EQT", "n_companies": 1, "total_fv": 31143000.0, "avg_holders": 3.0},
  {"sponsor_slug": "silver-lake", "sponsor": "Silver Lake", "n_companies": 1, "total_fv": 29199000.0, "avg_holders": 2.0},
  {"sponsor_slug": "warburg-pincus", "sponsor": "Warburg Pincus", "n_companies": 1, "total_fv": 26000000.0, "avg_holders": 2.0},
  {"sponsor_slug": "berkshire-partners", "sponsor": "Berkshire Partners", "n_companies": 1, "total_fv": 23298000.0, "avg_holders": 2.0},
  {"sponsor_slug": "kkr", "sponsor": "KKR", "n_companies": 1, "total_fv": 21505000.0, "avg_holders": 2.0},
  {"sponsor_slug": "skyknight", "sponsor": "SkyKnight", "n_companies": 1, "total_fv": 20343000.0, "avg_holders": 2.0},
  {"sponsor_slug": "charlesbank-capital-partners", "sponsor": "Charlesbank Capital Partners", "n_companies": 1, "total_fv": 20343000.0, "avg_holders": 2.0},
  {"sponsor_slug": "hg", "sponsor": "Hg", "n_companies": 1, "total_fv": 13937000.0, "avg_holders": 3.0}
];
