// AUTO-GENERATED by scripts/50_export_dashboard_data.py (scripts/vintage_engine.py).
// Do not edit by hand.
// MARK-BASED LOSS PROXY by vintage — not realized loss-given-default.
// Uses the same loans, vintages and distress exits as the cumulative-default
// curves (industry rollup). For each loan that left the book in distress
// (last mark < 0.85, or ever non-accrual / below 80¢ before exiting):
//   mark_loss = last reported fair value − last reported cost (USD, all pieces)
// Filings do not disclose sale prices or recoveries, so this is the markdown
// at the last filing before the loan disappeared. Small n_distress = noisy:
// mark_loss_pct is null below 10 distress exits, and a net markUP (last fair
// value above cost) is shown as 0%, never as a negative loss.
//
//   n_loans_total   loans dated to this vintage
//   n_exited        loans no longer on their holder's latest schedule
//   n_distress      of those, exits in distress
//   distress_cost_b last reported cost of the distress exits, $bn
//   mark_loss_b     last fair value − last cost across them, $bn (negative = loss)
//   mark_loss_pct   max(0, −mark_loss_b / distress_cost_b × 100); null below 10 exits

export interface VintageLGD {
  vintage_year: number; n_loans_total: number; n_exited: number; n_distress: number;
  cost_exited_b: number; distress_cost_b: number; mark_loss_b: number;
  pct_exited: number; pct_distress: number; mark_loss_pct: number | null;
}

export const vintageLGD: VintageLGD[] = [
  {"vintage_year": 2018, "n_loans_total": 1045, "n_exited": 895, "n_distress": 50, "cost_exited_b": 16.0891, "distress_cost_b": 0.9886, "mark_loss_b": -0.3293, "pct_exited": 85.65, "pct_distress": 4.78, "mark_loss_pct": 33.31},
  {"vintage_year": 2019, "n_loans_total": 1072, "n_exited": 886, "n_distress": 42, "cost_exited_b": 17.6031, "distress_cost_b": 1.1206, "mark_loss_b": -0.3557, "pct_exited": 82.65, "pct_distress": 3.92, "mark_loss_pct": 31.74},
  {"vintage_year": 2020, "n_loans_total": 1035, "n_exited": 820, "n_distress": 50, "cost_exited_b": 18.6874, "distress_cost_b": 0.9581, "mark_loss_b": -0.3029, "pct_exited": 79.23, "pct_distress": 4.83, "mark_loss_pct": 31.62},
  {"vintage_year": 2021, "n_loans_total": 2793, "n_exited": 1779, "n_distress": 133, "cost_exited_b": 40.2185, "distress_cost_b": 3.8343, "mark_loss_b": -1.4306, "pct_exited": 63.69, "pct_distress": 4.76, "mark_loss_pct": 37.31},
  {"vintage_year": 2022, "n_loans_total": 2384, "n_exited": 1406, "n_distress": 117, "cost_exited_b": 30.2938, "distress_cost_b": 1.5942, "mark_loss_b": -0.5201, "pct_exited": 58.98, "pct_distress": 4.91, "mark_loss_pct": 32.62},
  {"vintage_year": 2023, "n_loans_total": 2098, "n_exited": 1023, "n_distress": 38, "cost_exited_b": 18.2564, "distress_cost_b": 0.6632, "mark_loss_b": -0.2543, "pct_exited": 48.76, "pct_distress": 1.81, "mark_loss_pct": 38.35},
  {"vintage_year": 2024, "n_loans_total": 3030, "n_exited": 1089, "n_distress": 7, "cost_exited_b": 18.9408, "distress_cost_b": 0.0231, "mark_loss_b": -0.0079, "pct_exited": 35.94, "pct_distress": 0.23, "mark_loss_pct": null},
  {"vintage_year": 2025, "n_loans_total": 2575, "n_exited": 564, "n_distress": 8, "cost_exited_b": 9.1385, "distress_cost_b": 0.0858, "mark_loss_b": -0.0543, "pct_exited": 21.9, "pct_distress": 0.31, "mark_loss_pct": null}
];
