// AUTO-GENERATED by scripts/77_score_golden_set.py — do not edit by hand.
// Dating check against a SMALL hand-picked reference set of public financings.
// Not a representative accuracy benchmark; always show with its sample size.

export interface GoldenScore { n: number; exact?: number; within_1y?: number;
  pct_within_1y?: number; mean_err_years?: number; mae_years?: number; }

export const vintageGolden = {
  "scored_on": "2026-09-26",
  "caveat": "Small reference set, not a representative accuracy benchmark: hand-picked public financings matched to our loans by borrower name.",
  "n_reference_rows": 87,
  "n_reference_financings_matched": 85,
  "n_reference_rows_unmatched": 2,
  "n_conflicting_loans_excluded": 22,
  "overall": {
    "n": 667,
    "exact": 390,
    "within_1y": 472,
    "pct_within_1y": 70.8,
    "mean_err_years": 0.12,
    "mae_years": 1.16
  },
  "high_conf": {
    "n": 265,
    "exact": 188,
    "within_1y": 208,
    "pct_within_1y": 78.5,
    "mean_err_years": -0.0,
    "mae_years": 0.83
  },
  "by_bucket": {
    "borrowed": {
      "n": 191,
      "exact": 126,
      "within_1y": 142,
      "pct_within_1y": 74.3,
      "mean_err_years": 0.19,
      "mae_years": 0.95
    },
    "corrected": {
      "n": 45,
      "exact": 28,
      "within_1y": 28,
      "pct_within_1y": 62.2,
      "mean_err_years": -1.0,
      "mae_years": 1.0
    },
    "disclosed": {
      "n": 207,
      "exact": 123,
      "within_1y": 139,
      "pct_within_1y": 67.1,
      "mean_err_years": 0.06,
      "mae_years": 1.37
    },
    "inferred": {
      "n": 110,
      "exact": 48,
      "within_1y": 76,
      "pct_within_1y": 69.1,
      "mean_err_years": 0.45,
      "mae_years": 1.23
    },
    "name_matched": {
      "n": 114,
      "exact": 65,
      "within_1y": 87,
      "pct_within_1y": 76.3,
      "mean_err_years": 0.25,
      "mae_years": 1.14
    }
  },
  "by_source": {
    "dera_lower_bound": {
      "n": 18,
      "exact": 6,
      "within_1y": 12,
      "pct_within_1y": 66.7,
      "mean_err_years": 0.89,
      "mae_years": 1.11
    },
    "first_obs_discount_clip": {
      "n": 1,
      "exact": 0,
      "within_1y": 0,
      "pct_within_1y": 0.0,
      "mean_err_years": -2.0,
      "mae_years": 2.0
    },
    "first_obs_maturity_clip": {
      "n": 23,
      "exact": 5,
      "within_1y": 10,
      "pct_within_1y": 43.5,
      "mean_err_years": 0.43,
      "mae_years": 1.91
    },
    "first_obs_reliable": {
      "n": 64,
      "exact": 34,
      "within_1y": 51,
      "pct_within_1y": 79.7,
      "mean_err_years": 0.61,
      "mae_years": 0.86
    },
    "ltail_enriched": {
      "n": 16,
      "exact": 16,
      "within_1y": 16,
      "pct_within_1y": 100.0,
      "mean_err_years": 0.0,
      "mae_years": 0.0
    },
    "own_acq": {
      "n": 207,
      "exact": 123,
      "within_1y": 139,
      "pct_within_1y": 67.1,
      "mean_err_years": 0.06,
      "mae_years": 1.37
    },
    "tenor_model": {
      "n": 22,
      "exact": 9,
      "within_1y": 15,
      "pct_within_1y": 68.2,
      "mean_err_years": 0.09,
      "mae_years": 1.55
    },
    "xbdc_borrow": {
      "n": 191,
      "exact": 126,
      "within_1y": 142,
      "pct_within_1y": 74.3,
      "mean_err_years": 0.19,
      "mae_years": 0.95
    },
    "xbdc_borrow_loose": {
      "n": 80,
      "exact": 43,
      "within_1y": 59,
      "pct_within_1y": 73.8,
      "mean_err_years": 0.15,
      "mae_years": 1.38
    },
    "xbdc_earlier_peer": {
      "n": 45,
      "exact": 28,
      "within_1y": 28,
      "pct_within_1y": 62.2,
      "mean_err_years": -1.0,
      "mae_years": 1.0
    }
  }
} as {
  scored_on: string; caveat: string; n_reference_rows: number;
  n_reference_financings_matched: number; n_reference_rows_unmatched: number;
  n_conflicting_loans_excluded: number; overall: GoldenScore; high_conf: GoldenScore;
  by_bucket: Record<string, GoldenScore>; by_source: Record<string, GoldenScore>;
};
