// AUTO-GENERATED by scripts/50_export_dashboard_data.py (scripts/vintage_engine.py).
// Do not edit by hand.
// MARK-BASED LOSS PROXY by vintage — not realized loss-given-default.
// Uses the same loans, vintages and distress exits as the cumulative-default
// curves (industry rollup). For each loan that left the book in distress
// (last mark < 0.85, or ever non-accrual / below 80¢ before exiting):
//   mark_loss = last reported fair value − last reported cost (USD, all pieces)
// Filings do not disclose sale prices or recoveries, so this is the markdown
// at the last filing before the loan disappeared. Small n_distress = noisy:
// mark_loss_pct is null below 10 distress exits, and a net markUP (last fair
// value above cost) is shown as 0%, never as a negative loss.
//
//   n_loans_total   loans dated to this vintage
//   n_exited        loans no longer on their holder's latest schedule
//   n_distress      of those, exits in distress
//   distress_cost_b last reported cost of the distress exits, $bn
//   mark_loss_b     last fair value − last cost across them, $bn (negative = loss)
//   mark_loss_pct   max(0, −mark_loss_b / distress_cost_b × 100); null below 10 exits

export interface VintageLGD {
  vintage_year: number; n_loans_total: number; n_exited: number; n_distress: number;
  cost_exited_b: number; distress_cost_b: number; mark_loss_b: number;
  pct_exited: number; pct_distress: number; mark_loss_pct: number | null;
}

export const vintageLGD: VintageLGD[] = [
  {"vintage_year": 2018, "n_loans_total": 1033, "n_exited": 884, "n_distress": 50, "cost_exited_b": 15.971, "distress_cost_b": 0.9786, "mark_loss_b": -0.3325, "pct_exited": 85.58, "pct_distress": 4.84, "mark_loss_pct": 33.98},
  {"vintage_year": 2019, "n_loans_total": 1066, "n_exited": 881, "n_distress": 37, "cost_exited_b": 17.3583, "distress_cost_b": 0.9315, "mark_loss_b": -0.2932, "pct_exited": 82.65, "pct_distress": 3.47, "mark_loss_pct": 31.48},
  {"vintage_year": 2020, "n_loans_total": 1035, "n_exited": 820, "n_distress": 49, "cost_exited_b": 18.6903, "distress_cost_b": 1.0763, "mark_loss_b": -0.3029, "pct_exited": 79.23, "pct_distress": 4.73, "mark_loss_pct": 28.15},
  {"vintage_year": 2021, "n_loans_total": 2800, "n_exited": 1786, "n_distress": 146, "cost_exited_b": 40.5506, "distress_cost_b": 4.0061, "mark_loss_b": -1.5032, "pct_exited": 63.79, "pct_distress": 5.21, "mark_loss_pct": 37.52},
  {"vintage_year": 2022, "n_loans_total": 2400, "n_exited": 1424, "n_distress": 125, "cost_exited_b": 30.4912, "distress_cost_b": 1.9281, "mark_loss_b": -0.6297, "pct_exited": 59.33, "pct_distress": 5.21, "mark_loss_pct": 32.66},
  {"vintage_year": 2023, "n_loans_total": 2095, "n_exited": 1024, "n_distress": 41, "cost_exited_b": 18.2586, "distress_cost_b": 0.6577, "mark_loss_b": -0.2704, "pct_exited": 48.88, "pct_distress": 1.96, "mark_loss_pct": 41.11},
  {"vintage_year": 2024, "n_loans_total": 3032, "n_exited": 1091, "n_distress": 14, "cost_exited_b": 19.0001, "distress_cost_b": 0.0776, "mark_loss_b": -0.0097, "pct_exited": 35.98, "pct_distress": 0.46, "mark_loss_pct": 12.54},
  {"vintage_year": 2025, "n_loans_total": 2586, "n_exited": 569, "n_distress": 13, "cost_exited_b": 9.183, "distress_cost_b": 0.3116, "mark_loss_b": -0.1365, "pct_exited": 22.0, "pct_distress": 0.5, "mark_loss_pct": 43.8}
];
