// AUTO-GENERATED by scripts/50_export_dashboard_data.py — do not edit by hand.
// Per-vintage aggregates from the loan_exits table. Vintages 2014–2024.
//
//   n_loans_total       loans in our parsed data vintage-tagged to this year
//   n_exited            exited (any reason) — refis, paydowns, sales, write-offs
//   n_distress          exit_in_distress flag set (mark < 0.85 at exit, ever
//                       NA, or ever below 80 before exit)
//   cost_exited_b       sum of last-observed cost across all exited loans, $B
//   distress_cost_b     sum of last_cost across distress exits, $B
//   realized_loss_b     sum of (last_fv - last_cost) across distress exits, $B
//                       (negative = realized loss; positive can occur on refis
//                       that exit above original cost)
//   lgd_pct             implied LGD = -realized_loss_b / distress_cost_b, %

export interface VintageLGD {
  vintage_year: number;
  n_loans_total: number;
  n_exited: number;
  n_distress: number;
  cost_exited_b: number;
  distress_cost_b: number;
  realized_loss_b: number;
  pct_exited: number;
  pct_distress: number;
  lgd_pct: number;
}

export const vintageLGD: VintageLGD[] = [
  { vintage_year: 2014, n_loans_total: 69, n_exited: 60, n_distress: 10, cost_exited_b: 272.452, distress_cost_b: 9.142, realized_loss_b: -4.106, pct_exited: 86.96, pct_distress: 14.49, lgd_pct: 44.91 },
  { vintage_year: 2015, n_loans_total: 115, n_exited: 97, n_distress: 18, cost_exited_b: 580.445, distress_cost_b: 124.056, realized_loss_b: -62.531, pct_exited: 84.35, pct_distress: 15.65, lgd_pct: 50.41 },
  { vintage_year: 2016, n_loans_total: 121, n_exited: 104, n_distress: 18, cost_exited_b: 1106.925, distress_cost_b: 159.852, realized_loss_b: -28.927, pct_exited: 85.95, pct_distress: 14.88, lgd_pct: 18.10 },
  { vintage_year: 2017, n_loans_total: 323, n_exited: 297, n_distress: 36, cost_exited_b: 1774.982, distress_cost_b: 226.591, realized_loss_b: -124.411, pct_exited: 91.95, pct_distress: 11.15, lgd_pct: 54.91 },
  { vintage_year: 2018, n_loans_total: 346, n_exited: 302, n_distress: 18, cost_exited_b: 2202.479, distress_cost_b: 119.110, realized_loss_b: -25.010, pct_exited: 87.28, pct_distress: 5.20, lgd_pct: 21.00 },
  { vintage_year: 2019, n_loans_total: 303, n_exited: 249, n_distress: 10, cost_exited_b: 2695.113, distress_cost_b: 89.091, realized_loss_b: -49.130, pct_exited: 82.18, pct_distress: 3.30, lgd_pct: 55.15 },
  { vintage_year: 2020, n_loans_total: 268, n_exited: 197, n_distress: 10, cost_exited_b: 2190.240, distress_cost_b: 103.177, realized_loss_b: -15.965, pct_exited: 73.51, pct_distress: 3.73, lgd_pct: 15.47 },
  { vintage_year: 2021, n_loans_total: 990, n_exited: 578, n_distress: 44, cost_exited_b: 10899.640, distress_cost_b: 810.851, realized_loss_b: -216.827, pct_exited: 58.38, pct_distress: 4.44, lgd_pct: 26.74 },
  { vintage_year: 2022, n_loans_total: 532, n_exited: 298, n_distress: 27, cost_exited_b: 4972.141, distress_cost_b: 312.732, realized_loss_b: -67.102, pct_exited: 56.02, pct_distress: 5.08, lgd_pct: 21.46 },
  { vintage_year: 2023, n_loans_total: 302, n_exited: 148, n_distress: 4, cost_exited_b: 2344.920, distress_cost_b: 43.312, realized_loss_b: -10.713, pct_exited: 49.01, pct_distress: 1.32, lgd_pct: 24.73 },
  { vintage_year: 2024, n_loans_total: 1170, n_exited: 599, n_distress: 5, cost_exited_b: 20374.166, distress_cost_b: 16.735, realized_loss_b: -5.124, pct_exited: 51.20, pct_distress: 0.43, lgd_pct: 30.62 }
];
