// AUTO-GENERATED by scripts/77_score_golden_set.py — do not edit by hand.
// Dating check against a SMALL hand-picked reference set of public financings.
// Not a representative accuracy benchmark; always show with its sample size.

export interface GoldenScore { n: number; exact?: number; within_1y?: number;
  pct_within_1y?: number; mean_err_years?: number; mae_years?: number; }

export const vintageGolden = {
  "scored_on": "2026-09-25",
  "caveat": "Small reference set, not a representative accuracy benchmark: hand-picked public financings matched to our loans by borrower name.",
  "n_reference_rows": 87,
  "n_reference_financings_matched": 85,
  "n_reference_rows_unmatched": 2,
  "n_conflicting_loans_excluded": 20,
  "overall": {
    "n": 711,
    "exact": 421,
    "within_1y": 510,
    "pct_within_1y": 71.7,
    "mean_err_years": 0.16,
    "mae_years": 1.14
  },
  "high_conf": {
    "n": 270,
    "exact": 186,
    "within_1y": 210,
    "pct_within_1y": 77.8,
    "mean_err_years": 0.07,
    "mae_years": 0.89
  },
  "by_bucket": {
    "borrowed": {
      "n": 182,
      "exact": 115,
      "within_1y": 134,
      "pct_within_1y": 73.6,
      "mean_err_years": 0.35,
      "mae_years": 1.07
    },
    "corrected": {
      "n": 42,
      "exact": 26,
      "within_1y": 26,
      "pct_within_1y": 61.9,
      "mean_err_years": -1.02,
      "mae_years": 1.02
    },
    "disclosed": {
      "n": 233,
      "exact": 144,
      "within_1y": 162,
      "pct_within_1y": 69.5,
      "mean_err_years": 0.12,
      "mae_years": 1.28
    },
    "inferred": {
      "n": 110,
      "exact": 48,
      "within_1y": 75,
      "pct_within_1y": 68.2,
      "mean_err_years": 0.48,
      "mae_years": 1.25
    },
    "name_matched": {
      "n": 144,
      "exact": 88,
      "within_1y": 113,
      "pct_within_1y": 78.5,
      "mean_err_years": 0.1,
      "mae_years": 0.97
    }
  },
  "by_source": {
    "dera_lower_bound": {
      "n": 20,
      "exact": 7,
      "within_1y": 13,
      "pct_within_1y": 65.0,
      "mean_err_years": 0.7,
      "mae_years": 1.1
    },
    "first_obs_discount_clip": {
      "n": 1,
      "exact": 0,
      "within_1y": 0,
      "pct_within_1y": 0.0,
      "mean_err_years": -2.0,
      "mae_years": 2.0
    },
    "first_obs_maturity_clip": {
      "n": 20,
      "exact": 5,
      "within_1y": 9,
      "pct_within_1y": 45.0,
      "mean_err_years": 0.25,
      "mae_years": 1.85
    },
    "first_obs_reliable": {
      "n": 61,
      "exact": 29,
      "within_1y": 46,
      "pct_within_1y": 75.4,
      "mean_err_years": 0.74,
      "mae_years": 1.0
    },
    "ltail_enriched": {
      "n": 21,
      "exact": 21,
      "within_1y": 21,
      "pct_within_1y": 100.0,
      "mean_err_years": 0.0,
      "mae_years": 0.0
    },
    "own_acq": {
      "n": 233,
      "exact": 144,
      "within_1y": 162,
      "pct_within_1y": 69.5,
      "mean_err_years": 0.12,
      "mae_years": 1.28
    },
    "tenor_model": {
      "n": 28,
      "exact": 14,
      "within_1y": 20,
      "pct_within_1y": 71.4,
      "mean_err_years": 0.18,
      "mae_years": 1.32
    },
    "xbdc_borrow": {
      "n": 182,
      "exact": 115,
      "within_1y": 134,
      "pct_within_1y": 73.6,
      "mean_err_years": 0.35,
      "mae_years": 1.07
    },
    "xbdc_borrow_loose": {
      "n": 103,
      "exact": 60,
      "within_1y": 79,
      "pct_within_1y": 76.7,
      "mean_err_years": 0.0,
      "mae_years": 1.15
    },
    "xbdc_earlier_peer": {
      "n": 42,
      "exact": 26,
      "within_1y": 26,
      "pct_within_1y": 61.9,
      "mean_err_years": -1.02,
      "mae_years": 1.02
    }
  }
} as {
  scored_on: string; caveat: string; n_reference_rows: number;
  n_reference_financings_matched: number; n_reference_rows_unmatched: number;
  n_conflicting_loans_excluded: number; overall: GoldenScore; high_conf: GoldenScore;
  by_bucket: Record<string, GoldenScore>; by_source: Record<string, GoldenScore>;
};
